### ISSUE TITLE
Frontend: Sprachstrings für Notiz (in Editor für Beiträge, Reiter "Veröffentlichen") fehlen

### ISSUE THREAD

**Issue by gerryfrancis** [joomlagerman/joomla#1016]
### Was soll eingefügt werden
`COM_CONTENT_FIELD_NOTE_DESC="Eine optionale Notiz zur Anzeige in der Artikelliste."`
`COM_CONTENT_FIELD_NOTE_LABEL="Notiz"`

### Wo wird/werden der/die deutsche(n) Sprachstring(s) nicht angezeigt (Frontend/Backend)
Frontend

### Joomla Version & Version der deutschen Sprachdatei
3.9.16/3.9.16.1

**Comment by tecpromotion** [comment]
thanks @gerryfrancis

**Comment by gerryfrancis** [comment]
@tecpromotion _Ich_ habe zu danken! :)
