### ISSUE TITLE
"_QQ_" wird nicht mehr benötigt

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#104]
Hi @sisko1990 

wie möchtest du das hier bei URLs und CSS Dingen machen? `"_QQ_"` oder `"` im Text haben wir ja inzwischen `&bdquo;text&ldquo;`

>`<a href="_QQ_"http://community.joomla.org/blogs/leadership/1798-raising-the-bar-on-security.html"_QQ_">`
can be written
`<a href="http://community.joomla.org/blogs/leadership/1798-raising-the-bar-on-security.html">`
same for a span:
`<span class="_QQ_"term"_QQ_">`
can be 
`<span class="term">`
`"_QQ_"` can still be used
In text, for example to highlight a term, we can use
`"_QQ_" special wording"_QQ_"`
or
`&quot;special wording&quot;`

https://github.com/joomla/joomla-cms/pull/5862
https://github.com/joomla-projects/com_localise/issues/257

**Comment by sisko1990** [comment]
Muss ich mir noch überlegen...
