### ISSUE TITLE
Sync der Installationsdatei für Joomla 3.4 

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#105]
Die Datei
https://github.com/joomlagerman/joomla/blob/master/installation/language/de-DE/de-DE.ini

... hat Änderungen gegenüber der derzeitigen Version in der staging / master branche:
https://github.com/joomla/joomla-cms/blob/master/installation/language/de-DE/de-DE.ini

Joomla 3.4 wurde für den 17. Februar 2015 vorausgesagt:

**Comment by zero-24** [comment]
Reminder :smile: der 17. Februar (Karnevalsdienstag :smile:) ist aktuell geplantes Releasedatum: http://www.joomla.org/announcements/release-news/5583-joomla-3-4-beta-2-released.html

**Comment by sisko1990** [comment]
Habe JM angeschrieben. Werde das schließen, sobald ich eine positive Antwort von ihm habe.

**Comment by sisko1990** [comment]
So ist drin.

**Comment by zero-24** [comment]
@sisko1990 Müsste in der de-DE.xml nicht `<version>3.4.0</version>` stehen anstatt `<version>3.3.2</version>`?

https://github.com/joomla/joomla-cms/commit/180c4d2825b11472b8fc9cd0220489ca4514e16d

Selbiges für:
`<metafile version="3.2" client="installation">`

`<metafile version="3.4" client="installation">`

oder?

**Comment by sisko1990** [comment]
Hätte ich früher auch so gemacht, aber JM hat das immer so gehandhabt, das die Versionsnummer sich nur ändert, wenn es Änderungen gab. Und doie letzte Änderung war bei der Version 3.3.2.
Bezüglich der XML-Zeile: Ich glaube gar nicht, das die irgendwo bei der Installation ausgewertet wird, den auch alle anderen Sprachdateien haben diesen Eintrag [glaube auch, dass das nur die Minimalversion angeben sollte, wo man es installieren kann - bin mir da aber auch nicht mehr ganz sicher.]

**Comment by zero-24** [comment]
>nur ändert, wenn es Änderungen gab. Und doie letzte Änderung war bei der Version 3.3.2.

Die PDO Stings (`PDOMYSQL` & `INSTL_DATABASE_COULD_NOT_CREATE_DATABASE` & `INSTL_DATABASE_INVALID_PDOMYSQL_VERSION`) sind in 3.4 hinzu gekommen. :smile: 

Siehe: https://github.com/joomla/joomla-cms/pull/4123/files

**Comment by sisko1990** [comment]
naja... davon wird die Welt nicht untergehen, vor allem wir das ja auch nirgendwo angezeigt (und nach der Installation wird es eh gelöscht)

**Comment by zero-24** [comment]
Nein da hast du recht :smile:
