### ISSUE TITLE
Labels und Milestone

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#108]
Hi @sisko1990 ,

bei den folgenden 3 PRs gibt es keinen Milestone und Label ist das gewollt?

https://github.com/joomlagerman/joomla/pull/107
https://github.com/joomlagerman/joomla/pull/103
https://github.com/joomlagerman/joomla/pull/95

**Comment by sisko1990** [comment]
Nö. Habe ich schlicht vergessen. Danke für den Hinweis.
