### ISSUE TITLE
[4.0] Haupt Kontrollzentrum vs. Kontrollzentrum

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1118]
https://github.com/joomlagerman/joomla/blob/8050c7b64c36c03ce8e4319f2029af1a9b5e9b2b/administrator/language/de-DE/mod_menu.ini#L31

"Haupt Kontrollzentrum"?

Besser nur "Kontrollzentrum" ?

![2020-06-14_19-58-38](https://user-images.githubusercontent.com/1752513/84600441-855d9500-ae79-11ea-9fb6-526574fd0a3a.png)

**Comment by tecpromotion** [comment]
@joomlagerman/reviewer

**Comment by zero-24** [comment]
Ich würde nur `Kontrollzentrum` benutzen

**Comment by paternax** [comment]
Warum nicht den neuen Begriff Dashboard aus dem Englischen übernehmen?
Wie sollen denn die anderen 5 Dashboards übersetzt werden?

**Comment by tecpromotion** [comment]
> Warum nicht den neuen Begriff Dashboard aus dem Englischen übernehmen?
> Wie sollen denn die anderen 5 Dashboards übersetzt werden?

Bisher haben wir in Joomla 3.x ein "Kontrollzentrum" beim Öffnen der Administration.

**Comment by paternax** [comment]
Das ist schon klar. Aber das Home Dashboard hat ja noch einige Geschwister bekommen. Was ist da geplant?
Benutzer-Kontrollzentrum, Menü-Kontrollzentrum...
Der Begriff Dashboard hat ja auch im Deutschen Einzug gehalten.

**Comment by tecpromotion** [comment]
> Das ist schon klar. Aber das Home Dashboard hat ja noch einige Geschwister bekommen. Was ist da geplant?
> Benutzer-Kontrollzentrum, Menü-Kontrollzentrum...
> Der Begriff Dashboard hat ja auch im Deutschen Einzug gehalten.

Bisher noch nichts geplant. Wir sind für Vorschläge aus der Community offen @paternax

**Comment by paternax** [comment]
Dann fange ich mal an:
1. Dashboard
2. Cockpit
3. Überblick
4. Übersicht
5. Zentrum

1. Dashboard finde ich am besten, es hat sich auch im deutschen Sprachgebrauch eingebürgert. Jeder veröffentlicht ein Corona-Dashboard, es gibt Google-Dashboards usw. Wobei Dashboard meist auch eine graphische Komponente impliziert, die wir nicht haben.
2. Cockpit ist vielleicht etwas hochtrabend
3. + 4. Überblick und Übersicht sind wohl am ehrlichsten, weil wir es ja hauptsächlich mit "Linksammlungen" zu tun haben.
5. Zentrum würde das Kontrollzentrum aufnehmen und dann fortführen: Benutzerzentrum, Inhaltszentrum.... Wobei das "System-Dashboard" eigentlich zum Kontrollzentrum werden müsste, weil dort vor allem Links zur Konfiguration, Installation etc. zu finden sind.

**Comment by tecpromotion** [comment]
Nachdem nun auch im Core mit https://github.com/joomlagerman/joomla/issues/1223 aus Controlpanel das Home Dashboard wurde...

Was haltet ihr von **Dashboard** ganz simple?
Die anderen haben wir schon mit Dashboard **Name** übersetzt.

Feedback @joomlagerman/reviewer @paternax @webgras @SniperSister @Hackwar

**Comment by zero-24** [comment]
:+1: für Dashboard

**Comment by webgras** [comment]
ich bin auch für Dashboard, das wird sonst zu lange (finde ich).

**Comment by tecpromotion** [comment]
first PR #1366 for Issue #1223
