### ISSUE TITLE
[4.0] Weiterleitung vs Umleitung

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1121]
https://github.com/joomlagerman/joomla/blob/8050c7b64c36c03ce8e4319f2029af1a9b5e9b2b/administrator/language/de-DE/mod_menu.ini#L114
Das hatte mich drauf gebracht.

![2020-06-14_20-29-06](https://user-images.githubusercontent.com/1752513/84601034-c9529900-ae7d-11ea-9fa4-2acc07824ad0.png)

Wir verwenden in com_redirect (/administrator/index.php?option=com_redirect) nicht einheitlich Umleitung oder Weiterleitung.

Wir sollten uns auf eins einigen.

Meinungen jemand dazu? @joomlagerman/reviewer @SniperSister @chmst @Hackwar @webgras @coolcat-creations @

**Comment by chmst** [comment]
In den Lexika steht als Übersetzung immer "Weiterleitung". Es klingt auch besser.

**Comment by zero-24** [comment]
Weiterleitungen hört sich gut an.
