### ISSUE TITLE
[3.x] delete word "Full" from pkg_de-DE.xml

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1161]
Wir haben keine halbvoll, ganz voll oder Full Packages (mehr).

https://github.com/joomlagerman/joomla/blob/8d7a51c747ed2723eaa70171837d04c3822bf8e0/pkg_de-DE.xml#L17

Wort löschen @zero-24 ?

**Comment by zero-24** [comment]
> Wir haben keine halbvoll, ganz voll oder Full Packages (mehr).

![image](https://user-images.githubusercontent.com/2596554/87467449-3fcaee00-c618-11ea-9f93-40b5bead07a8.png)

hmm wir haben schon noch unterschiedliche Pakete also einmal mit core und einmal ohne oder?

**Comment by tecpromotion** [comment]
> hmm wir haben schon noch unterschiedliche Pakete also einmal mit core und einmal ohne oder?

Geht da mehr um die Ausgabe wenn jemand das Sprachpaket im Backend installiert.
Da passt das einfach nicht mehr. Ist historisch bedingt mal so gewesen.

**Comment by zero-24** [comment]
An der stelle können wir es gerne raus nehmen :)
