### ISSUE TITLE
[3.x] Unification of spelling language key/content in com_languages

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1162]
### Was soll verbessert / korrigiert werden

Vereinheitlichung der Strings

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend

### Was wäre eine bessere Übersetzung / Bezeichnung

Einheitlich Sprachschlüssel
Einheitlich Inhalt

### Joomla Version & Version der deutschen Sprachdatei

3.9.20

### Zusätzlichen Informationen

<img width="1298" alt="sprachoverride" src="https://user-images.githubusercontent.com/1752513/87461127-3f2d5a00-c60e-11ea-9cc4-11b41e9029d0.png">
Danke an Horst A. für den Hinweis auf FB

**Comment by zero-24** [comment]
hmm ich würde sagen `Sprachschlüssel` und `Inhalt` passen am besten oder?

**Comment by zero-24** [comment]
PR: https://github.com/joomlagerman/joomla/pull/1163
