### ISSUE TITLE
[3.10] Aktualisierung vs. Update

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1172]
### Was soll verbessert / korrigiert werden

Derzeit haben wir einen wilden Mix (historisch)

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend

### Was wäre eine bessere Übersetzung / Bezeichnung

tbd

### Joomla Version & Version der deutschen Sprachdatei

3.10 und folgende

### Zusätzlichen Informationen

#1168

**Comment by tecpromotion** [comment]
fyi @drmenzelit @richard67

**Comment by zero-24** [comment]
hmm `Windows Update` (Windows), `Nach Updates wird gesucht..` (Android), `Ausstehende Updates` (Android), `Softwareupdate` (Apple), `Nach Updates suchen ...` (Apple), `Laden und installieren` (Apple)

Würde für mich für `Update` sprechen.

**Comment by richard67** [comment]
@zero-24 Das ist auch auch mein Ansatz.

**Comment by richard67** [comment]
Wenn man die deutschen Sprachdateien auf der Kommandozeile z.B. mit `findstr /s /i /c:"aktualisier" *.ini` (Windows CMD) bzw. `find ./ -type f -name "*\.ini" -exec grep -iHn "aktualisier" {} \;` (Linux Shell) durchsucht, findet man zwar auch ein paar irrelevante Stellen wo "Aktualisierung" bzw. "aktualisieren" usw. passt, weil in anderem Zusammenhang als Core- oder Package-Updates, aber man findet auch alle, die man näher untersuchen sollte.

**Comment by tecpromotion** [comment]
@richard67 Ja oder in PHPStorm einfach suchen... viele Wege.

Aber dann wäre der Vorschlag von @zero-24 und mir das für den Pre-Update-Checker in 3.10 zu machen und dann ab 4.x konsequent.

**Comment by richard67** [comment]
> Aber dann wäre der Vorschlag von @zero-24 und mir das für den Pre-Update-Checker in 3.10 zu machen und dann ab 4.x konsequent.

Pre-Update-Checker wäre dann ok mit #1168 , richtig?

**Comment by tecpromotion** [comment]
> > Aber dann wäre der Vorschlag von @zero-24 und mir das für den Pre-Update-Checker in 3.10 zu machen und dann ab 4.x konsequent.
> 
> Pre-Update-Checker wäre dann ok mit #1168 , richtig?

Unser Vorschlag das dann mit 1172 gerade zu ziehen da es mehr ist als der #1168 und auch ggf. weitere Files betrifft.
Ist dann irgendwie sauberer wenn #1172 das fixed.
OK?

**Comment by tecpromotion** [comment]
Machen wir aus Aktualisierungsquellen dann Update-Quellen?
Bspw. https://github.com/joomlagerman/joomla/blob/ac0b9aabd2017d9dec602ac92f4298664554bf33/administrator/language/de-DE/de-DE.com_installer.ini#L16-L17 und viele weitere Stellen?

**Comment by richard67** [comment]
Wäre dafür, com_installer und com_joomlaupdate u. evtl. sonstwo. Aber noch mal: Für J4, oder für 3.10? Ist mir noch nicht klar.

**Comment by tecpromotion** [comment]
Denke die beiden ab 3.10 inkl. Pre-Update_Check natürlich.

**Comment by chmst** [comment]
Vorsichtige Frage: Reicht es nicht, Quelle zu sagen?
