### ISSUE TITLE
Milestone 3.4.0v2?

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#118]
Hi @sisko1990 ,

ich hab gerade gesehen das es einen 3.4.0v2 milestone gibt.

In den nächsten Tagen wird schon 3.4.1 kommen: https://groups.google.com/forum/#!topic/joomla-dev-cms/w9q2Q_1TpzE

Möchtest du vorher noch eine 3.4.0v2 Version raus bringen?

**Comment by sisko1990** [comment]
Nein, den lege ich immer erst an, falls ich ihn rausbringen will. Habe ihn aber jetzt umbenannt.

**Comment by zero-24** [comment]
:+1:
