### ISSUE TITLE
[3.10] unification of singular _1

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1222]
### Was soll verbessert / korrigiert werden

Derzeit wird 1 bzw. %d bei Einzahl verwendet.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

beide

### Was wäre eine bessere Übersetzung / Bezeichnung

Ganz weg bze. Ein/Eine

### Joomla Version & Version der deutschen Sprachdatei

> 3.10

**Comment by tecpromotion** [comment]
mit 59 Stimmen hat die Community für diese Variante gestimmt:

COM_BANNERS_BANNERS_N_ITEMS_PUBLISHED_1="Banner wurde veröffentlicht!"

**Comment by tecpromotion** [comment]
@max123kl hast du Lust und Zeit, für den https://github.com/joomlagerman/joomla/tree/3.10-dev Branch dir das mal anzusehen?

**Comment by max123kl** [comment]
@tecpromotion, danke für die  Einladung.

Betroffen ist ausschließlich die Datei `/administrator/language/de-DE/de-De.com_banners.ini ` (richtig?)
Diese beiden Strings steuern die entsprechende Ausgabe:
```
COM_BANNERS_BANNERS_N_ITEMS_PUBLISHED="%d Banner wurden veröffentlicht!"
COM_BANNERS_BANNERS_N_ITEMS_PUBLISHED_1="%d Banner wurde veröffentlicht!"
```

Wenn ich mir das aus Sicht einen (neuen) Users betrachte würde ich bei 3 bzw. 1 veröffentlichtem Banner folgende Meldungen erhalten:
"3 Banner wurden veröffentlicht!"  
"1 Banner wurde veröffentlicht!"  
Wenn man dem Voting folgen würde, hieße die Zeile: "_Banner wurde veröffentlicht!_"   

Mir fehlt da, im Vergleich zum vorherigen String, die Anzahl, um die möglichen Varianten stimmig auszudrücken.
Wie im ursprünglichen Vorschlag vorgesehen, ist es in dt. Texten üblich _kleine_ Zahlwerte als **Zahlwörter** zu schreiben.
Deshalb plädiere ich für folgende Form:  
`COM_BANNERS_BANNERS_N_ITEMS_PUBLISHED_1="Ein Banner wurde veröffentlicht!"`
(Entfernen der Variablen und ohne die weibliche Form "/Eine")

**Comment by tecpromotion** [comment]
Hallo @max123kl 
Nein, betroffen sind ALLE Dateien die solche Sprachstrings enthalten.

im Terminal `$ grep -hnr "N_ITEMS_PUBLISHED_1" .` findet folgende Zeilen:

`./administrator/language/de-DE/de-DE.com_languages.ini:113:COM_LANGUAGES_N_ITEMS_PUBLISHED_1="%d Inhaltssprache wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_users.ini:272:COM_USERS_NOTES_N_ITEMS_PUBLISHED_1="%d Benutzerhinweis wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_menus.ini:204:COM_MENUS_N_ITEMS_PUBLISHED_1="%d Menüeintrag wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_banners.ini:22:COM_BANNERS_BANNERS_N_ITEMS_PUBLISHED_1="%d Banner wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_banners.ini:51:COM_BANNERS_CLIENTS_N_ITEMS_PUBLISHED_1="%d Kunde wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_contact.ini:283:COM_CONTACT_N_ITEMS_PUBLISHED_1="%d Kontakt wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_plugins.ini:33:COM_PLUGINS_N_ITEMS_PUBLISHED_1="Das Plugin wurde aktiviert!"
./administrator/language/de-DE/de-DE.com_content.ini:155:COM_CONTENT_N_ITEMS_PUBLISHED_1="%s Beitrag wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_modules.ini:120:COM_MODULES_N_ITEMS_PUBLISHED_1="%d Modul wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_finder.ini:212:COM_FINDER_N_ITEMS_PUBLISHED_1="%d Eintrag wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_weblinks.ini:106:COM_WEBLINKS_N_ITEMS_PUBLISHED_1="%d Weblink wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_categories.ini:67:COM_CATEGORIES_N_ITEMS_PUBLISHED_1="%d Kategorie wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_messages.ini:57:COM_MESSAGES_N_ITEMS_PUBLISHED_1="Nachricht wurde als „gelesen“ markiert!"
./administrator/language/de-DE/de-DE.com_fields.ini:55:COM_FIELDS_FIELD_N_ITEMS_PUBLISHED_1="%d Feld wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_fields.ini:86:COM_FIELDS_GROUP_N_ITEMS_PUBLISHED_1="%d Feldgruppe wurden veröffentlicht!"
./administrator/language/de-DE/de-DE.com_newsfeeds.ini:115:COM_NEWSFEEDS_N_ITEMS_PUBLISHED_1="Der Newsfeed wurde veröffentlicht!"
./administrator/language/de-DE/de-DE.com_tags.ini:122:COM_TAGS_N_ITEMS_PUBLISHED_1="%d Schlagwort veröffentlicht!"
./administrator/language/de-DE/de-DE.com_redirect.ini:78:COM_REDIRECT_N_ITEMS_PUBLISHED_1="Link wurden aktiviert!"`

Wir hatten dazu eine Umfrage gestartet und die Benutzer wünschen sich keine Zahl/Ziffer oder Zahlwörter vorne.
Sprich aus "Der Newsfeed wurde veröffentlicht!" wird "Newsfeed wurde veröffentlicht!" etc.

**Comment by max123kl** [comment]
> Wir hatten dazu eine Umfrage gestartet ...

Kannst du mir den Link zur Umfrage nennen?

Dann müssten alle diese Strings angepasst werden?
Aber sind diese Strings in den vielen Varianten nicht dazu da, um auf sprachliche Eigenheiten eingehen zu können?

Wenn das generell sprachlich richtig gut zu lösen wäre, dann könnte man ja auch Variablen für die meisten Strings einsetzen. Das Ergebnis wären Sätze wie beim G...-Translator in seinen Anfängen.
Bsp.
COM_REDIRECT_N_ITEMS_PUBLISHED_1="Link wurden aktiviert!" 
COM_FIELDS_GROUP_N_ITEMS_PUBLISHED_1="%d Feldgruppe wurden veröffentlicht!" **(%d wird hier zu 1)**

Wenn man generell den Artikel (bestimmt, unbestimmt oder Zahlwort) vor dem Substantiv entfernt kommt in vielen Fällen eine Satzkrücke heraus.
Ziel sollte doch sein, dass der resultierende String, im Kontext auf der anzeigenden Seite einen möglichst leicht zu erfassenden Sinn ergibt. 
Viel zu oft werden diese Bildschirmausgaben in der Eile überlesen oder weggeklickt.
Ich persönlich würde viel öfter mit Textauszeichnungen (strong/italic) arbeiten um die Aufmerksamkeit zu erhöhen, aber das ist ein anderes Thema.

**Comment by tecpromotion** [comment]
Umfrage war auf FB in der Joomla! D-A-CH Gruppe.

Es hier nur um die "Ein/Eine" Strings. Da kann keine %d verwendet werden, da diese nicht "mehr" übergeben wird.
Dies ist nur noch für Strings > 1 und da machen wir es ja genauso auch weiterhin.

Es gibt auch keine mehreren Varianten. 
COM_REDIRECT_N_ITEMS_PUBLISHED_1="Link wurden aktiviert!" wird zu COM_REDIRECT_N_ITEMS_PUBLISHED_1="Link wurde aktiviert!"
Also einfach den String natürlich prüfen aber wirklich nur die Singular Strings die es hier betrifft anpassen.

**Comment by max123kl** [comment]
OK, verstanden.
Soll das jetzt so umgesetzt werden?

**Comment by tecpromotion** [comment]
Ja, das wäre klasse.
