### ISSUE TITLE
Anpassen/Ergänzen der  Datei administrator/language/de-DE/joomla.ini

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1245]
### Was soll verbessert / korrigiert werden
Anpassen/Ergänzen der  Datei administrator/language/de-DE/joomla.ini
Siehe PR #1248

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
im Backend

### Was wäre eine bessere Übersetzung / Bezeichnung
In den letzten Tagen wurde bei Joomla-Cms die o.a. Datei geändert.
Es sind diverse Übersetzungs-Strings entfallen und einige wurden eingefügt.

### Joomla Version & Version der deutschen Sprachdatei
Branch 4.0-dev

### Zusätzlichen Informationen
Unbenutzte Strings wurden auskommentiert.
Die Reihenfolge der Strings wurde an die der Source-Datei angepasst.

**Comment by zero-24** [comment]
Hi, welche strings hast du korrigiert? Wenn du bei der PR den target brach 4.0-dev auswählst sollte es auch besser angezeigt werden.

Wenn du deinen brach wiederherstellst kann ich den branch auch für dich anpassen.

**Comment by max123kl** [comment]
Danke für deine Antwort und dein Angebot,
ich werde aber zuerst selbst versuchen den Fehler zu beheben.
Da ich euer Repo schon eine ganze Weile verfolge, sind die Commits der letzten Monate in meinen PR gerutscht.
Ich denke mit einem "git reset --hard ..." sollte der Verlauf bereinigt sein. 

Falls das nicht funktioniert, komme ich gerne auf dein Angebot zurück.

Zwischenzeitlich stelle ich die Datei in meinen Webspace zum [Download](http://zsitetst.bplaced.net/uploads/joomla.ini) ein.

**Comment by zero-24** [comment]
Du hast beide PRs gegen den "master" branch geschickt. Die 4er sind aber im 4.0-dev branch. ;)

**Comment by zero-24** [comment]
> Zwischenzeitlich stelle ich die Datei in meinen Webspace zum Download ein.

sieht so aus als wäre der zeichensatz da nicht richtig? Hab da ne ganze menge an `fÃ¼r` `NÃ¤chster`

**Comment by zero-24** [comment]
PR: https://github.com/joomlagerman/joomla/pull/1248 Danke @max123kl
