### ISSUE TITLE
[4.0] Diskrepanz in Dateinamen

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1251]
### Dateinamen entsprechen nicht der Core-Version
**Core** administrator/language/**en-GB** —> administrator/language/**de-DE**
mod_user.ini —> mod_users.ini
mod_user.sys.ini —> mod_users.sys.ini

Fix durch PR #1252

**Comment by tecpromotion** [comment]
Hallo @max123kl 
dafür gibt es einen Grund und offene Issues. Bitte die nicht anfassen.
