### ISSUE TITLE
[4.0] Missing language-icon in installer

### ISSUE THREAD

**Issue by nadjak77** [joomlagerman/joomla#1322]
### Was soll verbessert / korrigiert werden
Im Installer fehlt das Icon bei der Sprachauswahl
![grafik](https://user-images.githubusercontent.com/37655645/96338933-94578c80-1091-11eb-9c94-c3588dd6a728.png)

**Comment by tecpromotion** [comment]
@nadjak77 dies fehlt leider bereits im Core in der Beta 4 und ist somit leider kein Bug hier.
