### ISSUE TITLE
[4.0] Hauptbeitrag vs Haupteintrag

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1352]
https://github.com/joomlagerman/joomla/blob/c33af4be74bbca2df1c96909bf90ee5e71360c6a/api/language/de-DE/joomla.ini#L83-L88

Hier wird Hauptbeitrag verwendet, was im Kontext com_content korrekt ist.
Da wir derzeit einen Artikel mit Beitrag gleichsetzen.
Allerdings wird die Variable auch bei com_contact verwendet und da ist Hauptbeitrag irreführend.

<img width="810" alt="Bildschirmfoto 2020-10-18 um 21 47 14" src="https://user-images.githubusercontent.com/1752513/96378333-8e45d680-118b-11eb-94a7-0761098e03e8.png">

Vorschlag wäre die Strings, sowie in api/, mit Haupteintrag zu übersetzen.

@joomlagerman/reviewer Meinungen?

**Comment by zero-24** [comment]
> Vorschlag wäre die Strings, sowie in api/, mit Haupteintrag zu übersetzen.

👍

**Comment by zero-24** [comment]
Done here: https://github.com/joomlagerman/joomla/pull/1358
