### ISSUE TITLE
[4.0] administrator/language/de-DE/com_admin.ini vs. core

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1355]
### Was soll verbessert / korrigiert werden

administrator/language/de-DE/com_admin.ini is not in sync with core version

### Joomla Version & Version der deutschen Sprachdatei

4.0

### Zusätzlichen Informationen

diffchecker.com

**Comment by max123kl** [comment]
Wenn gewünscht könnte ich die Datei synchronisieren
