### ISSUE TITLE
[4.0] API language & build script

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#1382]
Hi,

das build script und die XML muss um das api sprachpaket erweitert werden:

```
<file type="language" client="api" id="de-DE">api_de-DE.zip</file>
```
https://github.com/joomlagerman/joomla/blob/4.0-dev/pkg_de-DE.xml#L61

Build tools: https://github.com/joomlagerman/team/tree/master/Hilfsprogramme/Release/

Vorher sollten wir aber klären wie unser neuer build workflow aussehen soll und ob es vielleicht sinn macht ein PHP build script zu schreiben oder etwas ganz anderes zu verwenden.

Wenn möglich sollte dieser neue workflow auch für 3.x funktionieren.

**Comment by tecpromotion** [comment]
Schauen wir uns das die Woche mal an @zero-24 ?

**Comment by tecpromotion** [comment]
@zero-24 hier sollten wir die nächsten Schritte mal durchgehen.
