### ISSUE TITLE
[4.0] will fix minor color contrast (part 2)

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1390]
### Was soll verbessert / korrigiert werden
Wegen des geringen Kontrasts zur Background-Farbe sind (vermutlich alle) nachfolgede Textstellen schlecht lesbar.
Dies ist eine Erweiterung zum bereits gefixten PR #1369

Es gibt noch insgesamt 15 weitere Fundstellen in 12 der de-DE .ini-Dateien mit der Text-Auszeichnung "lightblue", welche in den Core-Dateien nicht (mehr) zu finden sind.

### Joomla Version & Version der deutschen Sprachdatei
J4.0

Folgende Dateien sind betroffen:
- [x] /administrator/language/de-DE/com_config.ini
- [x] /administrator/language/de-DE/com_languages.ini
- [x] /administrator/language/de-DE/com_redirect.ini
- [x] /administrator/language/de-DE/com_users.ini
- [x] /administrator/language/de-DE/joomla.ini
- [x] /administrator/language/de-DE/plg_system_updatenotification.ini
- [x] /administrator/language/de-DE/plg_system_updatenotification.sys.ini
- [x] /api/language/de-DE/joomla.ini
- [x] /language/de-DE/mod_articles_categories.ini
- [x] /language/de-DE/mod_articles_category.ini
- [x] /language/de-DE/mod_banners.ini
- [x] /language/de-DE/mod_feed.in

**Comment by zero-24** [comment]
PR: https://github.com/joomlagerman/joomla/pull/1391 Danke.
