### ISSUE TITLE
[4.0] will fix minor color contrast (part 3) "blue"

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1392]
### Was soll verbessert / korrigiert werden
Dies ist eine Erweiterung zum bereits gefixten PR #1369

Die Farbauszeichung "blue" wird in den Core .ini Dateien nur einmal verwendet in der Datei:
`/plugins/sampledata/testing/language/en-GB/en-GB.plg_sampledata_testing.ini`
Diese Datei wird **nicht** für das deutsche Sprachpaket übersetzt.

Es gibt aber insgesamt 6 weitere Fundstellen in 5 der de-DE .ini-Dateien mit der Text-Auszeichnung "blue", welche in den Core-Dateien nicht (mehr) zu finden sind.

Diese Farbe wird aber von der Joomla CI **nicht** verwendet.
Falls auf eine Farbauszeichnung nicht verzichtet werden kann, sollte man die Farbe, entsprechend der CI verwenden ("color: #2a69b8;\" oder "color: #132f53;\").

### Joomla Version & Version der deutschen Sprachdatei
J4.0

- [x] /administrator/language/de-DE/plg_finder_content.ini
- [x] /administrator/language/de-DE/plg_finder_content.sys.ini
- [x] /installation/language/de-DE/joomla.ini
- [x] /language/de-DE/mod_articles_category.ini
- [ ] /language/de-DE/mod_related_items.ini

@tecpromotion  @zero-24 
Wie ist eure Meinung ? 
Auf Farbe verzichten?

**Comment by tecpromotion** [comment]
Ja, ich denke Farben in einem barrierefreien Template zu verwenden, wäre eher ungünstig. Raus damit @max123kl

**Comment by tecpromotion** [comment]
Und sampledata nutzen wir derzeit nicht.

**Comment by zero-24** [comment]
> Diese Datei wird nicht für das deutsche Sprachpaket übersetzt.

Ja die sample daten sind  noch ein offener Issue: https://github.com/joomlagerman/joomla/issues/851 

Aber ich denke auch das kann erstmal aus.

**Comment by max123kl** [comment]
Dieses Issue betrifft nur die „blauen“ Textstellen.
Bei „lightblue“ hatte ich die Unterstreichung schon entfernt.
Aus typografischer Sicht sind auch Unterstreichungen als Text-Auszeichnungen wenig hilfreich.
Ich gehe davon aus, dass das auch hier so gemacht werden sollte.

Beim Durchforsten sind mir noch 30 weitere Dateien aufgefallen, die alle mind. eine Unterstreichung enthalten, die nicht im Core vorhanden ist. Sie haben sowohl "red" als auch "green" als Farbwerte und ev. noch andere. Ich muss das aber noch genauer prüfen, ob die Farbe dort notwendig/sinnvoll ist. 
ggf. kommt noch „part 4“

**Comment by zero-24** [comment]
Soweit ich weiß wurden damals die Unterstreichungen und Farben eingebaut um einen weiteren Indikator auf die Themen zu setzen ich würde nicht alle raus nehmen sondern nur da wo sie keinen Sinn mehr machen.

**Comment by max123kl** [comment]
Unterstreichungen würde ich persönlich gerne komplett wegnehmen.
Als zusätzlichen Indikator könnte man bestimmte Textstellen invertierten (Hintergrund- und Vordergrundfarbe tauschen)

**Comment by zero-24** [comment]
Ich bin da leidenschaftslos ich denke nur das wir an einigen stellen weiterhin einen besonderen visuellen Hinweis geben sollten, wie genau das am besten passt, da bin ich offen :)

**Comment by tecpromotion** [comment]
Mache gerne einen PR @max123kl 
Ich schaue mir die an und dann sollten wir das situativ machen. 
In einigen Fällen ist es sehr hilfreich nicht das gleiche wie der Core zu machen.

**Comment by max123kl** [comment]
Die Anpassung für `/installation/language/de-DE/joomla.ini` halte ich für überflüssig – kann aber auch nicht schaden.

Ich finde einfach den Screen nicht in dem der folgende Sprachstring angezeigt wird:
`language/de-DE/de-DE.mod_related_items.ini` L07

Der String könnte/sollte eigentlich hier auftauchen (lt. [JDOC Help Screen](https://docs.joomla.org/Help4.x:Site_Modules:_Articles_-_Related#Module_Tab))
System → Manage Panel → Site Modules → Neu/Edit → Beiträge - Verwandte

Ich mache mal einen [WiP] PR dazu

**Comment by zero-24** [comment]
PR: https://github.com/joomlagerman/joomla/pull/1399
