### ISSUE TITLE
Text für COM_USERS_RESET_REQUEST_LABEL ist missverständlich

### ISSUE THREAD

**Issue by UliTheGrey** [joomlagerman/joomla#1396]
### Was soll verbessert / korrigiert werden
COM_USERS_RESET_REQUEST_LABEL="Bitte eine E-Mail-Adresse für das Benutzerkonto eingeben. Ein Bestätigungscode wird dann an diese verschickt. Sobald der Code vorliegt, kann ein neues Passwort für das Benutzerkonto festgelegt werden."

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Frontend

### Was wäre eine bessere Übersetzung / Bezeichnung
COM_USERS_RESET_REQUEST_LABEL="Bitte die E-Mail-Adresse des Benutzerkontos eingeben. Ein Bestätigungscode wird dann an diese verschickt. Sobald der Code vorliegt, kann ein neues Passwort für das Benutzerkonto festgelegt werden."

### Joomla Version & Version der deutschen Sprachdatei
3.10-dev
joomla/language/de-DE/de-DE.com_users.ini

### Zusätzlichen Informationen
Siehe auch Eintrag unter COM_USERS_FIELD_PASSWORD_RESET_DESC, da ist es schon richtig.

**Comment by zero-24** [comment]
Vielen Dank @UliTheGrey ich hab hier eine PR für die Änderung gemacht: https://github.com/joomlagerman/joomla/pull/1398
