### ISSUE TITLE
[4.0] missing string in mod_breadcrumps.ini

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1397]
### Was soll verbessert / korrigiert werden

- [ ]  /language/de-DE/mod_breadcrumps.ini
Datei ist **nicht** mit Core-Datei synchron

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend

### Was wäre eine bessere Übersetzung / Bezeichnung
eine Zeile einfügen – eine andere Zeile löschen

### Joomla Version & Version der deutschen Sprachdatei
J4

**Comment by zero-24** [comment]
Machst du einen PR @max123kl ? Die Datei muss uns dann untergegangen sein beim initialen syncen?

**Comment by max123kl** [comment]
Ja, könnte ich, bin aber gerade noch an "part 3 und 4" des letzten Issues.
Falls es eilt, kannst du aber gerne übernehmen

**Comment by zero-24** [comment]
eilt nicht wollte nur doppelte Arbeit vermeiden. Ich assigne dich mal

**Comment by zero-24** [comment]
PR #1400
