### ISSUE TITLE
[4.0] will fix text decoration (part 4 of #1369)

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1401]
### Was soll verbessert / korrigiert werden
Text-Auszeichnung "underline" + Farbwert ersetzen
es sind ca. 30 Dateien betroffen, bei denen im Gegensatz zu den Core-Dateien eine solche Formatierung verwendet wird.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Frontend/Backend

### Was wäre eine bessere Übersetzung / Bezeichnung
Es ist zu prüfen welche alternative Text-Auszeichnung an den betroffenen Stellen verwendet werden kann.

### Joomla Version & Version der deutschen Sprachdatei
J4.0

### Zusätzlichen Informationen
Ich schlage vor einen [WiP] PR zu öffnen und dort die Detail-Diskussion zu führen.
Wäre das OK?

**Comment by zero-24** [comment]
Gute Idee, wie in dem anderen Issue gesagt das wurde damals bewusst gemacht ubd da wo es sinnvoll ist sollten wir uns für Joomla 4 etwas überlegen
