### ISSUE TITLE
[4.0] Fehlende Übersetzung im Backend - Dashboard

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1403]
### Was soll verbessert / korrigiert werden
Die Labels der Panels auf dem Dashboard sind noch nicht übersetzt

![DashboardA](https://user-images.githubusercontent.com/853497/97802223-2f2f9980-1c42-11eb-93c3-c4bf6c7a444c.png)

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend

### Was wäre eine bessere Übersetzung / Bezeichnung
Die betroffene(n) Datei(en) sind zu ermitteln

### Joomla Version & Version der deutschen Sprachdatei
J 4.0

### Zusätzlichen Informationen
Screenshot genommen von: 
"frischer" J4-Beta5 + separate DE-Beta3 + Commit-Snapshot 5e595a0 (PR #1399)

**Comment by zero-24** [comment]
Das sind die Label der Module. Wenn Joomla mit dem deutschen Paket installiert werden dann übersetzen wir die wenn nur die Sprache installiert wird machen wir das nicht, da wir ja möglicherweise nur eine von vielen Sprachen sind ;)

Das Paket meine ich: https://github.com/joomlagerman/joomla/releases/download/4.0.0v1-beta3/Joomla_4.0.0-Beta5-Full_Package_German_beta3.zip

ggf. fehlen ein paar Übersetzungen hier müsste man aber testen. Hier ist unser code: https://github.com/joomlagerman/joomla/blob/4.0-dev/installation/sql/mysql/localise.sql#L51

**Comment by max123kl** [comment]
> wenn nur die Sprache installiert wird machen wir das nicht,
Das erklärt, warum ich zuerst über 150 Fundstellen hatte als ich für das Issue #1402 recherchiert hatte. Da war zuerst das deutsch/englische Kombi-Paket installiert.
Müssen denn dort die CH-, AU- ... -Strings für das andere Issue auch aktualisiert werden?

Ich verstehe zu wenig davon, wie die Pakete generiert werden müssen – aber wenn du sagst, dass beim reinen Sprach-Paket die Labels der Module nicht übersetzt sind aber doch beim Kombi-Paket, dann verstehe ich den Sinn nicht ganz.

Wenn man aus dem Kombi-Paket oder aus dem engl. Core-Paket + n Sprachen die Backend-Sprache nach DE wechselt, dann sollte, meiner Meinung nach, alles (falls möglich und sinnvoll) auch in Deutsch dargestellt werden. Gerade Neulinge, denen die Begriffe ev. noch nicht so geläufig sind, werden auf diese Art nur unnötig verwirrt.

**Comment by zero-24** [comment]
Genau das passiert. Wenn du unser full Paket installierst werden die Modultitel übersetzt. Wenn jemand den englischen Core und dann die deutsche Sprache installiert dann nicht.

de-CH de-AT sind fast 1:1 kopien von de-DE unter joomlagerman/team sind die aktuellen scripts dafür.

**Comment by tecpromotion** [comment]
Close? @max123kl und @zero-24

**Comment by max123kl** [comment]
close
