### ISSUE TITLE
[4.0] missing language string(s) in /admin.../com_users.ini (file not in sync with core)

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1419]
### Was soll verbessert / korrigiert werden
mind. ein Language-String fehlt in der de-Datei im Vergleich zur Core-Datei
administrator/language/en-GB/com_users.ini
`COM_USERS_CONFIG_FIELD_NEW_USER_TYPE_LABEL="New User Registration Group"` Line 50

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend

### Joomla Version & Version der deutschen Sprachdatei
4.0

### Zusätzlichen Informationen
erste flüchtige Überprüfung zeigt weitere asynchrone Zeilen

**Comment by tecpromotion** [comment]
@max123kl bitte einen Diff machen, danke.

**Comment by max123kl** [comment]
Ich habe leider keine Idee wie ich aus 2 verschiedenen Repos ein "git diff" machen kann.
Was ich tun kann, ist mit Hilfe von Notepad++ bzw. Diffmerge einen Dateivergleich zu starten. Leider sind die farblichen Hervorhebungen nicht eindeutig, sodass noch einige an "Handarbeit" anfällt.
Falls das OK ist, würde ich einen PR mit der korrigierten Datei starten.

**Comment by tecpromotion** [comment]
Bitte file basiert.

Nutze einfach www.diffchecker.com dafür.

**Comment by max123kl** [comment]
> Nutze einfach www.diffchecker.com dafür.

Sorry, aber die Web-Version zeigt mir (ohne einen Account oder die Desktop-Version) die Unterschiede noch weniger differenziert wie meine bisherigen Tools.
