### ISSUE TITLE
[4.0] Unterschiedliche Übersetzung in com_contact.ini

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1450]
### Was soll verbessert / korrigiert werden
folgender Sprach-String ist in [/administrator/language/de-DE/com_contact.ini#L126](https://github.com/joomlagerman/joomla/blob/ae8b7ae90e33f44c392441fc9e04cfd6087c2d44/administrator/language/de-DE/com_contact.ini#L126) so übersetzt:
`COM_CONTACT_FIELD_USER_CUSTOM_FIELDS_SHOW_LABEL="Eigene Feldgruppen anzeigen"`

Der gleiche String ist in V3.9x so übersetzt:
`COM_CONTACT_FIELD_USER_CUSTOM_FIELDS_SHOW_LABEL="Eigene Felder anzeigen"`
### Wo wird der Sprach-String angezeigt (Frontend/Backend)
Backend

### Was wäre eine bessere Übersetzung / Bezeichnung
Der erläuternde Text der entsprechenden [Hilfe-Seite in JDOC](https://docs.joomla.org/Help4.x:Contacts:_New_or_Edit#Display) passt besser zu der Übersetzung aus V3.9x

Wenn der erläuternde Text noch immer aktuell ist, dann könnte im Core-Sprach-String ein Slash `/` fehlen:
`COM_CONTACT_FIELD_USER_CUSTOM_FIELDS_SHOW_LABEL="User Custom Field Groups"`
würde zu:
`COM_CONTACT_FIELD_USER_CUSTOM_FIELDS_SHOW_LABEL="User Custom Field/Groups"`
### Joomla Version & Version der deutschen Sprachdatei
V4.0 und 3.9.x

**Comment by tecpromotion** [comment]
Es sind **Feldgruppen** gemeint.
Ein `/` wäre falsch.

**Comment by tecpromotion** [comment]
Da es in 3.9 aber noch so im Original ist: https://github.com/joomla/joomla-cms/blob/d3b544e92b04e6421cd683602e6535eb470ba276/administrator/language/en-GB/en-GB.com_contact.ini#L231
und dann erst mit 4.0 angepasst wurde, sehe ich hier keinen Grund für eine Anpassung, oder?

**Comment by max123kl** [comment]
Der zugehörige Text auf der 4.0 Hilfeseite lautet:

> **Show User Custom Fields.** Show user custom fields which belong to all or only selected field groups.

Die Beschriftung des Auswahlfeldes lautet jetzt: "User Custom Field Groups"
dann müsste die engl. Hilfeseite entsprechend angepasst werden. 
Etwa so:

> **Show User Custom Field Groups.** Show user custom fields which belong to all or only selected field groups.

richtig?

**Comment by tecpromotion** [comment]
Ticket wird geschlossen.
