### ISSUE TITLE
[4.0] Workflow - Titel 	Überleitungs-Liste: Genehmigung Blogbeiträge

### ISSUE THREAD

**Issue by paternax** [joomlagerman/joomla#1471]
### Was soll verbessert / korrigiert werden
Die Überschrift der "transitions" Liste heißt Überleitungs-Liste. Um es konsistent zu beschreiben sollte es Übergangsliste heißen

### Was wäre eine bessere Übersetzung / Bezeichnung

Übergangsliste

**Comment by tecpromotion** [comment]
Machst du direkt einen PR @paternax ?

**Comment by tecpromotion** [comment]
@paternax magst du einen PR machen? Soll ich?

**Comment by tecpromotion** [comment]
Danke @paternax 
Ich habe mit #1563 einen PR angelegt.
