### ISSUE TITLE
[4.0] Workflow vs. Stufe

### ISSUE THREAD

**Issue by paternax** [joomlagerman/joomla#1472]
### Was soll verbessert / korrigiert werden

![grafik](https://user-images.githubusercontent.com/10668343/101397242-b967bf00-38cc-11eb-9e15-f72c00f80713.png)

**Comment by tecpromotion** [comment]
@paternax brauchen wir hier noch Context? Was machen wir mit diesem Issue?

**Comment by bembelimen** [comment]
Mit "stage" ist weniger eine Stufe gemeint sondern eher "Phase", "Abschnitt", "Zustand", "Stand", "Schritt"

**Comment by AK-CCM** [comment]
Den Begriff "Stufe" finde ich zu unspezifisch. Wie wäre es mit "Entwicklungsstufe" oder "Entwicklungsphase"?

**Comment by coolcat-creations** [comment]
Phase finde ich super...Oder Meilenstein

**Comment by chmst** [comment]
Ich glaub "Phase" wäre das beste. Da passt auch das Wort "Übergang" und es ist kurz.

**Comment by tecpromotion** [comment]
Da Issue #1476 und Issue #2006 sich auch mit Workflow beschäftigen, wäre es wohl einfacher EINEN PR zu erstelllen.
Es wäre super, wenn wir das in den RC6 (geplant 10.08.2021) schon haben.

**Comment by chmst** [comment]
Ich habe mal durchgeschaut.

Stufe durch Phase zu ersetzen ist eigentlich überall möglich - nur ein Sache ist die "Grundstufe". Die wird zu "Grundphase". 

Alternativ "Ausgangsphase"?

**Comment by max123kl** [comment]
> Alternativ "Ausgangsphase"?

wie wäre es mit "Startphase"?

**Comment by tecpromotion** [comment]
> > Alternativ "Ausgangsphase"?
> 
> 
> 
> wie wäre es mit "Startphase"?
> 
> 

Bitte nicht im geschlossenen issue kommentieren. 
Einfach im PR #2017
