### ISSUE TITLE
[4.0] Beitragsoptionen - Unterkategorien-beschreibung

### ISSUE THREAD

**Issue by paternax** [joomlagerman/joomla#1475]
### Was soll verbessert / korrigiert werden
Beitragsoptionen
Reiter Kategorie und Kategorien
Eintrag: Unterkategorien-beschreibung

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend

### Was wäre eine bessere Übersetzung / Bezeichnung
Unterkategorien-Beschreibung oder noch besser in einem Wort: Unterkategorienbeschreibung

**Comment by chmst** [comment]
Beschreibung der Unterkategorien ?

**Comment by tecpromotion** [comment]
@paternax magst du einen PR machen?

**Comment by tecpromotion** [comment]
@paternax ich habe einen PR angelegt. #1562
