### ISSUE TITLE
[4.0] - Workflow: Standard Workflow und Standard Stufe - zur Diskussion

### ISSUE THREAD

**Issue by paternax** [joomlagerman/joomla#1476]
### Was soll verbessert / korrigiert werden
Beim Workflow kommt an zwei Stellen der Begriff Standard vor. Zu einem gibt es den Standard-Workflow, der wenn nicht anders festlegt ist, verwendet wird. Zum anderen die Standard-Stufe. Diese ist allerdings kein "richtiger" Standard, sondern eher ein Startpunkt für den Workflow.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend -> Workflow

### Was wäre eine bessere Übersetzung / Bezeichnung
die Standard-Stufe würde ich Startstufe nennen

**Comment by tecpromotion** [comment]
@paternax gehört das zu #1472 ?

**Comment by tecpromotion** [comment]
closed. please se #1472
