### ISSUE TITLE
[4.0] PLG_SYSTEM_ACCESSIBILITY_MENU_TITLE

### ISSUE THREAD

**Issue by AK-CCM** [joomlagerman/joomla#1509]
### Was soll verbessert / korrigiert werden
Barrierefreiheitsoptionen

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
frontend+backend

### Was wäre eine bessere Übersetzung / Bezeichnung
Bedienhilfen

### Joomla Version & Version der deutschen Sprachdatei
‎v4 Beta 6 & v3.9.23.1

### Zusätzlichen Informationen
Reasons: The word component "Barriere" is negative associated and the compound word "Barrierefreiheitsoptionen" is quite long. Furthermore "Barrierefreiheit" is often mistaken for usability.

![2021-01-08-accessibility-options](https://user-images.githubusercontent.com/33413085/104059509-c3474f80-51f5-11eb-9344-fdad447c1680.png)

**Comment by tecpromotion** [comment]
@AK-CCM 
I have decided to use operating aids instead of operating aids, as there are considerably more hits on them in the search engines.

**Comment by AK-CCM** [comment]
"operating aids instead of operating aids" – what?
Please use the German terms in your feedback.

**Comment by tecpromotion** [comment]
:)

Ich habe statt Bedienhilfen im PR #1518 Bedienungshilfen verwendet. In geschlossenen Issues bitte keine Kommentare schreiben, das macht wenig Sinn. Einfach dann im referenzierten PR schreiben, solange dieser noch offen ist.
