### ISSUE TITLE
[4.0] PLG_SYSTEM_ACCESSIBILITY – font size

### ISSUE THREAD

**Issue by AK-CCM** [joomlagerman/joomla#1510]
### Was soll verbessert / korrigiert werden

Textgröße erhöhen
Textgröße verkleinern

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

frontend/backend

### Was wäre eine bessere Übersetzung / Bezeichnung

Schrift vergrößern
Schrift verkleinern

### Joomla Version & Version der deutschen Sprachdatei

v4 Beta 6 & v3.9.23.1

### Zusätzlichen Informationen
The compound word "Textgröße" isn't listed at dict.cc, duden.de (!), de.langenscheidt.com, de.pons.com, openthesaurus.de or the German Wiktionary. Only at dwds.de an entry exists. The term "text size" is used for "font size". The most common translation for that is "Schriftgröße".

To better distinguish the two menu items from "Zeichenabstand erhöhen" and "Zeichenabstand verringern" (Issue #1511), I recommend using the verbs "vergrößern" and "verkleinern" respectively – they fits better to the loupe icons too.

![2021-01-08-accessibility-font-size](https://user-images.githubusercontent.com/33413085/104065876-c3991800-5200-11eb-9013-20beb2bd75d5.png)

**Comment by chmst** [comment]
Schrift vergrößern / verkleinern
