### ISSUE TITLE
[4.0] PLG_SYSTEM_ACCESSIBILITY – character spacing

### ISSUE THREAD

**Issue by AK-CCM** [joomlagerman/joomla#1511]
### Was soll verbessert / korrigiert werden

Textabstand vergrößern
Textabstand verringern

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

frontend/backend

### Was wäre eine bessere Übersetzung / Bezeichnung

Zeichenabstand erhöhen
Zeichenabstand verringern

### Joomla Version & Version der deutschen Sprachdatei

v4 Beta 6 & v3.9.23.1

### Zusätzlichen Informationen

deepl.com, dict.cc, dict.leo.org and translate.google.de translate "character spacing" with "Zeichenabstand". This is the most common term for that and it should be used – "Buchstabenabstand" or "Typenabstand" is quite rarer used.

To better distinguish the two menu items from "Schrift vergrößern" and "Schrift verkleinern" (Issue #1510), I recommend using the verbs "erhöhen" and "verringern" respectively.

![2021-01-08-accessibility-character-spacing](https://user-images.githubusercontent.com/33413085/104066500-ccd6b480-5201-11eb-9bca-d67cb00c82b5.png)

**Comment by chmst** [comment]
Zeichenabstand
