### ISSUE TITLE
[4.0] PLG_SYSTEM_ACCESSIBILITY – big mouse pointer

### ISSUE THREAD

**Issue by AK-CCM** [joomlagerman/joomla#1512]
### Was soll verbessert / korrigiert werden

Großer Cursor

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Frontend/Backend

### Was wäre eine bessere Übersetzung / Bezeichnung

Großer Mauszeiger

### Joomla Version & Version der deutschen Sprachdatei

v4 Beta 6 & v3.9.23.1

### Zusätzlichen Informationen

The term "cursor" is a blinked line at the row bottom which fits most with the translation "Schreibmarke". But here is a term needed for aa mouse pointer. For that "Mauszeiger" is the most common term and it should be used here.

![2021-01-08-accessibility-big-mouse-pointer](https://user-images.githubusercontent.com/33413085/104066851-60a88080-5202-11eb-92d1-2d8806264772.png)

**Comment by chmst** [comment]
Großer Mauszeiger
