### ISSUE TITLE
[4.0] PLG_SYSTEM_ACCESSIBILITY – text 2 speech

### ISSUE THREAD

**Issue by AK-CCM** [joomlagerman/joomla#1514]
### Was soll verbessert / korrigiert werden

Text zu Sprache

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend/Frontend

### Was wäre eine bessere Übersetzung / Bezeichnung

Text vorlesen lassen

### Joomla Version & Version der deutschen Sprachdatei

v4 Beta 6 & v3.9.23.1

### Zusätzlichen Informationen

"Text zu Sprache" reads somewhat abstractly and is therefore more difficult to understand. Therefore, I would like to suggest the German translation "Text vorlesen lassen" or short "Text vorlesen" for "Text 2 Speech".

![2021-01-08-accessibility-text2speech](https://user-images.githubusercontent.com/33413085/104082001-e512f780-5232-11eb-8d84-c349df219c2d.png)

**Comment by chmst** [comment]
"Text vorlesen"
