### ISSUE TITLE
Sync the installations datei

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#152]
Hi Jan,

die Installations datei muss gesynct werden ;)

z.B. https://github.com/joomlagerman/joomla/commit/5109303e75a656a2026f8f5da6277a22013dbc8d

**Comment by sisko1990** [comment]
Weiß ich. Für 3.5 muss da eh geschehen ... Denke ich dran.

**Comment by zero-24** [comment]
:+1:
