### ISSUE TITLE
[4.0] Vereinheitlichung der Übersetzung von "Toolbar"

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1572]
### Was soll verbessert / korrigiert werden
In den JDOC-Hilfeseiten wird "Toolbar" zu "Symbolleiste" übersetzt.
Da auf den Bildschirmmasken keine Werkzeuge abgebildet sind, finde ich den Begriff "Symbolleiste" besser als "Werkzeugleiste"

Während in `/administrator/language/de-DE/tpl_atum.ini` und `/administrator/language/de-DE/tpl_atum.sys.ini` momentan der Begriff ""Symbolleiste" verwendet wird ist an anderen Stellen von "Werkzeugleiste" bzw. "Toolbar" die Rede.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Frontend und Backend

### Joomla Version & Version der deutschen Sprachdatei
J 4.0

### Zusätzlichen Informationen
insgesamt sind 11 Dateien betroffen (PR ist vorbereitet)

EDIT:
Ich sehe gerade, dass für J3.x #1559 gemergt wurde.
(falls mein Vorschlag Zustimmung findet, würde ich diesen PR auch vorbereiten)

**Comment by tecpromotion** [comment]
What do you think

@Hackwar @SniperSister @coolcat-creations @chmst @webgras @astridx @paternax @zero-24 @coolwebcreations

**Comment by chmst** [comment]
Ich finde alle Begriffe falsch, in englisch sind sie schon falsch (es ist kein Toolbar) und daher kann es keine korrekte Übersetzung geben. 
Meine Meinung ist: Es werden Aktionen angeboten, also sollte es Aktionsleiste heissen.

**Comment by max123kl** [comment]
Bisher wird auf den Hilfeseiten überwiegend "Werkzeugleiste" verwendet.

Zunehmend ist "Symbolleiste" zu finden und seltener auch "Werkzeugkasten" oder "Toolbar".
Ich weiß nicht, ob es richtig wäre noch einen weiteren Begriff einzuführen, den ich selbst auch als treffender empfinde.
Es wären sicher über hundert Seiten davon betroffen.
[J3.x-Hilfeseiten](https://docs.joomla.org/Help39:Help_screens/de)
[J4.x-Hilfeseiten](https://docs.joomla.org/Help4.x:Help_screens)
Vielleicht sollten wir uns vorher mit [Mike Brandner](https://volunteers.joomla.org/teams/documentation-working-group) abstimmen.

**Comment by chmst** [comment]
Es war eine persönliche Meinung. Vielleicht wäre auch eine FB-Umfrage anbebracht, dann wissen wir wei die user denken

**Comment by tecpromotion** [comment]
> Es war eine persönliche Meinung. Vielleicht wäre auch eine FB-Umfrage anbebracht, dann wissen wir wei die user denken

Ich erstelle einen entsprechenden Post.

**Comment by astridx** [comment]
> ### Was soll verbessert / korrigiert werden
> In den JDOC-Hilfeseiten wird "Toolbar" zu "Symbolleiste" übersetzt.

Ist das geplant? Im Moment finde ich den Begriff Werkzeugleiste oft. Insbesondere in Überschriften. Zum Beispiel hier: https://docs.joomla.org/Help39:Menus_Menu_Item_Manager_Edit/de#Werkzeugleiste

**Comment by tecpromotion** [comment]
> > ### Was soll verbessert / korrigiert werden
> > In den JDOC-Hilfeseiten wird "Toolbar" zu "Symbolleiste" übersetzt.
> 
> Ist das geplant? Im Moment finde ich den Begriff Werkzeugleiste oft. Insbesondere in Überschriften. Zum Beispiel hier: https://docs.joomla.org/Help39:Menus_Menu_Item_Manager_Edit/de#Werkzeugleiste

Wir haben eine sehr gewachsene und wilde Mischung aus vielen Bezeichnungen.
Wir sollten es versuchen zu vereinheitlichen. Das hilft uns, jemanden der Support macht und unseren Nutzern. Wenn wir mit 4 oder mehr Bezeichnungen arbeiten, dann weiß niemand was wann wo gemeint ist.

**Comment by tecpromotion** [comment]
> Vielleicht wäre auch eine FB-Umfrage anbebracht, dann wissen wir wei die user denken

https://www.facebook.com/groups/joomla.deutschland/permalink/1780908105416321/

**Comment by astridx** [comment]
> > > ### Was soll verbessert / korrigiert werden
> > > In den JDOC-Hilfeseiten wird "Toolbar" zu "Symbolleiste" übersetzt.
> > 
> > 
> > Ist das geplant? Im Moment finde ich den Begriff Werkzeugleiste oft. Insbesondere in Überschriften. Zum Beispiel hier: https://docs.joomla.org/Help39:Menus_Menu_Item_Manager_Edit/de#Werkzeugleiste
> 
> Wir haben eine sehr gewachsene und wilde Mischung aus vielen Bezeichnungen.
> Wir sollten es versuchen zu vereinheitlichen. Das hilft uns, jemanden der Support macht und unseren Nutzern. Wenn wir mit 4 oder mehr Bezeichnungen arbeiten, dann weiß niemand was wann wo gemeint ist.


Wenn ich das richtig verstehe ist es bei jdocs ebenfalls in der Planung. 

Dann  ist in meinen Augen die Abstimmung mit Mike wichtig. Nicht jdocs auf "Werzeugleiste" vereinheitlicht und Joomla das gleiche "Symbolleiste" nenne.

**Comment by tecpromotion** [comment]
@coolwebcreations deine Meinung dazu?

**Comment by tecpromotion** [comment]
Stand heute:

Speichern, Speichern & Schließen, Abbrechen etc. haben wir schon lange als Werkzeugsymbole geführt. 
Und bis auf Ausnahmen die noch vereinheitlicht gehören wird mehr **Werkzeugleiste** verwendet.

**Comment by coolwebcreations** [comment]
Ich bin auch dafür, es einheitlich bei "Werkzeugleiste" zu lassen. Damit wäre die Bezeichnung wie bei den früheren Joomla Versionen gleich und auch wiederzuerkennen. In den JDocs ist auch Werkzeugleiste die am häufigsten verwendete Übersetzung, sollte dort aber auch vereinheitlicht werden.

**Comment by coolwebcreations** [comment]
Update: 
Nach Abstimmung und Recherche bin ich eher für Toolbar, was die meisten User auch so benutzen.
Die JDocs Übersetzungen müssten entsprechend angepasst werden.

**Comment by tecpromotion** [comment]
Die Anmerkungen von @kitepascal haben mich nachdenklich gemacht.
Und es ist richtig, wir müssen das aus verschiedenen Kontexten betrachten.

Ich werde verschiedene PRs machen um das langsam aufzuräumen. Mit der Gießkanne klappt das hierbei nicht.

**Comment by kitepascal** [comment]
Die Admin-Modulposition und Entwickler jDocs auf Toolbar anzupassen, ist sicherlich richtig und nötig. Die können allesamt Englisch.

In Anwender jDocs, Hilfeartikeln in Sachen Bedienung und in Beschreibungen kann es ruhig bei Werkzeugleiste bleiben. Denn die ist entgegen J3 in der Mobilansicht eh nirgends mehr betitelt/beschriftet. Abgesehen von der Admin Modul Seite, wo man als unbedarfter Anwender "eigentlich" eh nichts verloren hat.

Werkzeugleiste ist eher ein beschreibender Begriff, als ein einheitlich festgelegter.

Werkzeugleiste versteht Oma Finchen bei ihrem Joomla Einstieg wahrscheinlich besser als Toolbar.
Nur sollte man immer dann, wenn die 'JTOOLBAR' gemeint ist, auch bei Werkzeugleiste oder Toolbar bleiben. 
Nicht mit Symbolleiste und auch besser nicht mit Aktionsleiste anfangen.

Bis auf COM_CACHE_PURGE_INSTRUCTIONS "Toolbar" und den Ausreißer im Atum "Symbolleiste" gab es bisher überhaupt keinen Mix, keine Unhgereimtheiten in Joomla selbst dahingehend.

Umso mehr in den jDocs.

Symbolleiste kann man weiterhin beim Accessibility Plugin verwenden, das ist ja nicht die JTOOLBAR.
Oder auch bei Editor Symbolen.


Im Support heißt es "Öffne Erweiterungen -> Verwalten -> Datenbank und klicke auf den Reparieren Button.
Die Begriffe Toolbar/Werkzeugleiste kommen da in der Kommunikation quasi überhaupt nicht  vor.

**Comment by paternax** [comment]
Super analysiert und ausgeführt von @kitepascal. Vernünftig für Anwender den etablierten und verständlichen Begriff "Werkzeugleiste" zu belassen und für die Entwickler und Modulposition "Toolbar" zu verwenden

**Comment by tecpromotion** [comment]
Dafür schreibe ich gerade mehrere PRs. Danke allen für die Ideen und den Austausch.

**Comment by max123kl** [comment]
Ich denke, dass jetzt eine vernünftige Lösung gefunden wurde. 
Kann geschlossen werden!

@coolwebcreations 
Gibt es ev. ein Skript / einen Bot, womit die Korrektur in den Jommla Hilfeseiten und anderen JDOC Dateien halbwegs automatisiert werden kann?
Antwort gerne auch per Mail

**Comment by tecpromotion** [comment]
> Ich denke, dass jetzt eine vernünftige Lösung gefunden wurde.
> Kann geschlossen werden!

Nein, das ist nicht erledigt. Ich gehe gerade alle Strings durch und mache mehrere PRs, wie geschrieben.

**Comment by max123kl** [comment]
Ich hatte gemeint, dass eine Lösung gefunden wurde, nicht dass sie schon umgesetzt ist.

In meinem [Toolbar-Branch](https://github.com/max123kl/joomla-DE/tree/toolbar) hatte ich den Wechsel zu "Symbolleiste" vorbereitet. Vielleicht hilft die betreffenden Dateien zu finden oder ich könnte davon einen PR machen (entsprechend der gefundenen Lösung).
