### ISSUE TITLE
"Vielen" in com_users.ini

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1590]
### Was soll verbessert / korrigiert werden

Es werden derzeit viele Mails und Texte im Format

Hallo X,
Vielen Dank....

geschrieben. Bspw. COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_BODY_NOPW

Hier muss "Vielen" klein geschrieben werden.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

both

### Was wäre eine bessere Übersetzung / Bezeichnung

Hallo X,
vielen Dank...

### Joomla Version & Version der deutschen Sprachdatei

3 und 4

### Zusätzlichen Informationen

Danke @HLeithner

**Comment by HLeithner** [comment]
thanks
