### ISSUE TITLE
[4.0 ] Vorschlag Anmelden vs. Einloggen

### ISSUE THREAD

**Issue by crimle** [joomlagerman/joomla#1612]
### Was soll verbessert / korrigiert werden

JGLOBAL_YOU_MUST_LOGIN_FIRST = Bitte zuerst anmelden! 
JLOGIN = Anmelden
JLOGOUT = Abmelden
und weitere Vorkommnisse,,,

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Front-End und Back-End 

### Was wäre eine bessere Übersetzung / Bezeichnung
JGLOBAL_YOU_MUST_LOGIN_FIRST = Bitte zuerst einloggen! 
JLOGIN = Einloggen
JLOGOUT = Ausloggen

### Joomla Version & Version der deutschen Sprachdatei
3.9.25v1 und 4.0

### Zusätzlichen Informationen
Nach meinem Sprachverständnis betrifft Anmeldung oder Abmeldung die Teilnahme bzw. Nicht-Teilnahme an einer Veranstaltung oder einem Kurs. Einloggen und Ausloggen ist meiner Meinung nach viel genauer.

**Comment by tecpromotion** [comment]
Ab 4.0 gerne.
Für 3.9/3.10 ist die Literatur schon geschrieben, das würde nur schwierig umsetzbar sein.

**Comment by crimle** [comment]
Schon klar. Kein Problem! Danke!

**Comment by tecpromotion** [comment]
Hallo @crimle 
Ich würde das hier mal schließen, Interesse scheint aus der Community nicht vorhanden zu sein.
