### ISSUE TITLE
Hinweis auf forum.joomla.de

### ISSUE THREAD

**Issue by SniperSister** [joomlagerman/joomla#162]
Wäre es möglich, im Backend-Hilfe-Menü auf forum.joomla.de hinzuweisen?

**Comment by sisko1990** [comment]
Prinzipiell: Ja. Kann ich aber nicht über die Sprachdatei steuern, dort kann ich nur einen Int-Wert eingeben, siehe (administrator/modules/mod_menu/tmpl/default_enabled.php):
`if ($lang->hasKey('MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM_VALUE') && JText::_('MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM_VALUE') != '')
        {
                $forum_url = 'http://forum.joomla.org/viewforum.php?f=' . (int) JText::_('MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM_VALUE');
                $lang->setDebug($debug);
                $menu->addChild(new JMenuNode(JText::_('MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM'), $forum_url, 'class:help-forum', false, '_blank'));
        }`
Wenn man eine eigene URL bzw. ein eigenes Support-Forum angeben will, muss man einen Wert im Admin-Menü unter „Erweitert“ -> „Eigenes Supportforum“ angeben. Dass kann ich aber nicht via Sprachdatei regeln ...
