### ISSUE TITLE
Crowdin als Übersetzungsplatform?

### ISSUE THREAD

**Issue by TheSoulrester** [joomlagerman/joomla#1628]
### Was soll verbessert / korrigiert werden
Der Übersetzungsprozess

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
--

### Was wäre eine bessere Übersetzung / Bezeichnung
--

### Joomla Version & Version der deutschen Sprachdatei
--

### Zusätzlichen Informationen
Ich fände es vlt. etwas einfacher, wenn man z.B. den Prozess der Übersetzung anders gestalten könnte. Vlt. ist die Platform Crowdin ein Begriff?

Hierüber können Entwickler ihre Sprachdateien anbieten, um die Community die Möglichkeit zu geben, die Texte zu übersetzen. Das schöne: es gibt auch eine Github Integration, mit welcher man (nach Validierung z.B. ernannter Personen) die übersetzten Texte in das/ein Github Repo übertragen kann. Genauso ist es aber auch möglich, automatisch und dynamisch neue Sprach-Strings von Github zu importieren. Somit ist man immer auf dem aktuellen Stand.

Hat jetzt jemand einen neuen Vorschlag, kann man den einbringen und ernannte Personen entscheiden in übersichtlicher Form, ob die Änderung approved oder rejected wird.

In der Regel ist Crowdin für (kommerzielle) Entwickler kostenpflichtig, für Non-Profit Projekte hingegen gibt es die Features kostenlos. Hier mal ein Link: https://crowdin.com/page/open-source-project-setup-request

Auch das Github Repo Joomla-CMS scheint ein eigenes Crowdin zu besitzen: https://crowdin.com/project/joomla-cms

Grüße,

**Comment by zero-24** [comment]
Hi, ja es gibt Bestrebungen im Joomla Project crowdin (in der Enterprise version) als tool anzubieten und in den Prozess zu integrieren.

Es gibt aber noch einige Probleme die gelöst werden müssen und zumindest wir werden voraussichtlich nicht ganz von GitHub weg kommen da wir noch weitere Themen haben z.B. wir machen Pakete für 4 Sprachen aus einem repo. Crodwin unterstützt keine PHP und JS Dateien welche aber für joomla Sprachen benötigt werden.. etc.

Die Idee ist das es ab einem gewissen Punkt eine Synchronisation zwischen unserem GitHub repo und dem Joomla Crowdin Enterprise repo gibt, aber da sind wir noch nicht und das ist auch nicht etwas was wir als JGerman aktiv pushen da hängen wir an dem was das Joomla Projekt hier macht.

Unsere Prozesse haben wir inzwischen soweit optimiert das wir für jede Änderung im Core hier einen issue bekommen und dann in Ruhe schauen können was davon alles betroffen ist. So ist auch der Rückblick auf die Core PR Änderungen möglich, also auch jenseits des Strings welcher geändert wird und das sind mWn Dinge die Crowdin auch nicht bieten kann.

**Comment by comradekingu** [comment]
Gonna spare you my German, but why use Crowdin?

https://docs.weblate.org/en/latest/formats.html
https://docs.weblate.org/en/latest/admin/continuous.html?highlight=github#automatically-receiving-changes-from-github
