### ISSUE TITLE
Kalender Übersetzung

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#175]
https://github.com/joomlagerman/joomla/blob/master/media/system/js/fields/calendar-locales/de.js

```
	AM : "AM",
	PM :  "PM",
	am : "am",
	pm : "pm",
```

Sollten wir das nicht mit vormittags und nachmittags übersetzen? Ich hab aber auch noch nicht geschaut ob und wo das genau angezeigt wird.

ggf. auch `nm.` und `vm.` oder `nachm.` & `vorm.` ?

**Comment by sisko1990** [comment]
Diese Strings werden bei Ländern mit 24 Std. nicht verwendet. Ich finde sie nachher auch nicht in der Oberfläche und auch andere Sprachdateien (de-IT) haben sie daher so stehen gelassen.

**Comment by zero-24** [comment]
Ah ok :+1:
