### ISSUE TITLE
[4.0] globale Konfiguration_Kontakte_Formular

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1786]
### Was soll verbessert / korrigiert werden
COM_CONTACT_FIELD_CAPTCHA_LABEL="<a href=\"https://de.wikipedia.org/wiki/CAPTCHA\" target=\"_blank\" rel=\"noopener noreferrer\">Captcha</a> für Kontakte aktivieren"
in `administrator/language/de-DE/com_contact.ini`

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend

### Was wäre eine bessere Übersetzung / Bezeichnung
![Konfiguration_Kontakt_Formular_A](https://user-images.githubusercontent.com/853497/119985776-650fe300-bfc3-11eb-82cf-b519c2aa79a6.png)

### Joomla Version & Version der deutschen Sprachdatei
J4 beta

### Zusätzlichen Informationen
Mich stört etwas, dass die engl. Version dort nicht von einem „Formular“ spricht.
~~Mit eurer Zustimmung könnte die Änderung in den PR #1785 mit eingearbeitet werden~~

**Comment by tecpromotion** [comment]
@max123kl mach hier bitte ggf. einen eigenen PR. Das sollten wir nicht mixen.

Allerdings bezieht sich das ja ausschließlich auf das Kontaktformular, ich wäre auch mit der derzeitigen Übersetzungen einverstanden.

**Comment by max123kl** [comment]
>> @max123kl mach hier bitte ggf. einen eigenen PR. Das sollten wir nicht mixen.

>Allerdings bezieht sich das ja ausschließlich auf das Kontaktformular, ich wäre auch mit der derzeitigen Übersetzungen einverstanden.

OK
