### ISSUE TITLE
[4.0] Module: "Statistiken", "Werkzeugleiste" zeigen HTML-Code

### ISSUE THREAD

**Issue by sandramay0905** [joomlagerman/joomla#1838]
### Was soll verbessert / korrigiert werden

![image](https://user-images.githubusercontent.com/78906980/120635602-f3c1ab80-c46c-11eb-91dc-ec7c2618655a.png) ![image](https://user-images.githubusercontent.com/78906980/120638329-494b8780-c470-11eb-8a21-7ad1e84c9e95.png)

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend

### Joomla Version & Version der deutschen Sprachdatei

‎4.0.0-rc2-dev / 4.0.0-rc1.1

**Comment by max123kl** [comment]
Kann den Fehler **nicht** bestätigen
Hier 
Joomla! 4.0.0-rc1 Release Candidate [ Mañana ] 1-June-2021 20:36 GMT 
German 4.0.0-rc1.1
installiert über Kombipaket: Joomla_4.0.0-RC1-Full_Package_German_rc1.zip

**Comment by max123kl** [comment]
Das Darstellungsproblem betrifft, so weit ich sehen kann, nur die Modul-Auswahl. An anderen Stellen wird das schmale, geschützte Leerzeichen (`&#8239;`) problemlos gerendert.
Einen Grund, warum es dort nicht interpretiert wird kann ich nicht erkennen.

Als Zwischenlösung schlage ich vor in den beiden betroffenen Dateien:

`administrator/language/de-DE/mod_stats_admin.sys.ini` und
`administrator/language/de-DE/mod_toolbar.sys.ini`

ein normales Leerzeichen einzufügen.
