### ISSUE TITLE
[4.0] Converting additional mails to mail templates

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1904]
### Was soll verbessert / korrigiert werden

missing merged pr [4.0] Converting additional mails to mail templates #31621 https://github.com/joomla/joomla-cms/pull/31621

**Comment by tecpromotion** [comment]
@webgras dies scheint der PR zu sein den wir wohl nicht mitbekommen haben.

**Comment by tecpromotion** [comment]
@zero-24 wissen wir warum der fehlt? Das sind ja doch recht viele Anpassungen in den .ini files die da fehlen.

**Comment by zero-24** [comment]
> @zero-24 wissen wir warum der fehlt? Das sind ja doch recht viele Anpassungen in den .ini files die da fehlen.

hmm nein hab ich jetzt spontan keine Idee woran es liegen kann..
