### ISSUE TITLE
[4.0] Konfiguration: "Captcha"-Link

### ISSUE THREAD

**Issue by sandramay0905** [joomlagerman/joomla#1907]
### Was soll verbessert / korrigiert werden

In `Konfiguration` > `Site` hat `Captcha` einen Link auf [wikipedia](https://de.wikipedia.org/wiki/Captcha),

![image](https://user-images.githubusercontent.com/78906980/121805514-db5f4700-cc4b-11eb-9bd2-14dc1336dbb1.png)

in Englisch nicht

![image](https://user-images.githubusercontent.com/78906980/121805366-4fe5b600-cc4b-11eb-805c-8ccb5abb269c.png)

### Zusätzlichen Informationen

Wenn das bekannt ist, den Kommentar bitte schließen.

**Comment by zero-24** [comment]
In meinen Augen eine Verbesserung gegenüber dem original :)

**Comment by tecpromotion** [comment]
das haben wir bewußt so eingebaut. Ist an einigen Stellen.

Danke @sandramay0905
