### ISSUE TITLE
[4.0] Deutsches Sprachpaket nicht gefunden

### ISSUE THREAD

**Issue by sandramay0905** [joomlagerman/joomla#1909]
### Was soll verbessert / korrigiert werden

Die Installation schlägt fehl:

![image](https://user-images.githubusercontent.com/78906980/122176584-11d3d680-ce85-11eb-8e1c-f2cf56d0d419.png)

### Joomla Version & Version der deutschen Sprachdatei

 4.0.0-rc2.1

**Comment by zero-24** [comment]
Hi, ja wir sind da dran ggf ein bug im neuen system für die Sprachpakete du kannst das Paket vom release tag hier installieren: https://github.com/joomlagerman/joomla/releases/tag/4.0.0v1-rc2

**Comment by sandramay0905** [comment]
Danke für die Antwort, ich wollte nur die Information weiter geben, falls das noch nicht bekannt ist.

**Comment by zero-24** [comment]
Ja alles gut, immer gerne reporten wenn dir was auffällt. Lass uns den issue auch auf lassen bis es gefixt wurde.

**Comment by zero-24** [comment]
Hi @sandramay0905 sollte inzwischen behoben sein.

**Comment by max123kl** [comment]
Heute früh – Upgrade fehlgeschlagen
![Update-RC2-deA](https://user-images.githubusercontent.com/853497/122331983-fffe3c00-cf35-11eb-8c10-8b58cb6b245a.png)

Über: Erweiterung → hochladen und installieren 
problemlos ausgeführt

**Comment by sandramay0905** [comment]
Die Installation in einem neuen J4 (das war das Problem gestern) hat heute geklappt.

**Comment by zero-24** [comment]
Hmm moment also klappt es jetzt oder nicht @sandramay0905 @max123kl ? Ich bin verwirrt.

**Comment by max123kl** [comment]
Bei mir klappt es, wenn ich das Sprachpaket über die Install-Funktion starte.

Es klappt **nicht,** wenn ich es über die Upgrade-Funktion versuche (s. Screenshot oben)

System:
Beide Installationen in einer VM als virtual Hosts auf dem gleichen Server (Ausgangsversion: J4-RC1)

**Comment by sandramay0905** [comment]
> Hmm moment also klappt es jetzt oder nicht

Bei mir hat es geklappt. Bei @max123kl nicht.

**Comment by zero-24** [comment]
> Es klappt nicht, wenn ich es über die Upgrade-Funktion versuche (s. Screenshot oben)

Kannst du bitte einmal den Update cache leeren und es dann nochmal probieren? ggf wurde da etwas noch gespeichert.

**Comment by max123kl** [comment]
Gleiches negatives Ergebnis – ich habe den (allgemeinen) Cache geleert (war aber auch in der Config schon deaktiviert) und das Plugin "updatenotification" deaktiviert. Wo gibt es noch einen speziellen "Update Cache"?

**Comment by zero-24** [comment]
Unter Erweiterungen -> Update -> Cache leeren

**Comment by max123kl** [comment]
Sorry, mit dieser "Pfadangabe" kann ich _Cache leeren_ nicht finden.
Ich hatte zwischenzeitlich in der Konfiguration → Installationen → Update-Cache auf 0 Stunden gesetzt.
Jetzt habe es danach noch mit einer Stunde versucht (falls die "0" dauerhaft ein bedeuten sollte).

Der Fehler tritt immer noch auf

**Comment by zero-24** [comment]
Hmm da wo man die Erweiterungs Updates installieren kann kann man auch "cache leeren" drücken. Ich schaue nochmal genauer mach bin gerade unterwegs.

**Comment by max123kl** [comment]
Hab jetzt mal den Crome-Browser genommen, um auch das auszuschließen

![Update-RC2-de_02](https://user-images.githubusercontent.com/853497/122455633-e77d3880-cfac-11eb-9629-08611b5b4f84.png)

**Comment by zero-24** [comment]
Ok konnte das Problem nachstellen, die Hashes sind falsch weil wahrscheinlich jemand manuell an dem Download rumgepfuscht hat.. Hab temporär das ganze auf der CDN gepatcht aber mit dem nächsten Update der CDN wird diese Änderung wieder verloren gehen. Bin dran das entsprechend auch im Download Portal korrigieren zu lassen.

**Comment by zero-24** [comment]
Achja du hast recht @max123kl das "clear cache" Thema ist wieder einmal raus geflogen.. Über "Update Suchen" sollte er auch den Cache löschen. In 3.x gibts noch einen expliziten Cache löschen Button.

**Comment by zero-24** [comment]
So sollte jetzt auch permanent gefixt sein. Kannst du einmal bitte gegenprüfen @max123kl dann können wir hier zu machen

**Comment by max123kl** [comment]
Ja, danke. Das Update läuft jetzt durch.
Aber
![Update-RC2-de_03](https://user-images.githubusercontent.com/853497/122501995-08b64700-cff6-11eb-8059-df4b421f4425.png)
![Update-RC2-de_04](https://user-images.githubusercontent.com/853497/122502007-0ce26480-cff6-11eb-88f9-f03c64bf8d5e.png)

Die neue Warnmeldung kommt, soweit ich erkennen kann, vom französischen Sprachpaket.
Könntest du einen entsprechenden Bugreport loslassen oder mir bei der Formulierung helfen (gerne direkt über RingCentral)?

**Comment by zero-24** [comment]
> Die neue Warnmeldung kommt, soweit ich erkennen kann, vom französischen Sprachpaket.

Mache ich. Ich mache dann hier aber zu da der Fehler im Sprachpaket inzwischen gefixt wurde.
