### ISSUE TITLE
[4.0] Dialogue Add module 

### ISSUE THREAD

**Issue by AK-CCM** [joomlagerman/joomla#1926]
### Was soll verbessert / korrigiert werden
Login Form
This module displays a username and password login form. It should not be unpublished.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend > Dashboard > Dialog: Modul hinzufügen

### Was wäre eine bessere Übersetzung / Bezeichnung
Anmeldeformular
Dieses Modul zeigt ein Anmeldeformular mit Benutzername und Passwort an. Es sollte nicht unveröffentlicht sein.

### Joomla Version & Version der deutschen Sprachdatei
4.0.0-rc3 + 4.0.0-rc3.1

**Comment by AK-CCM** [comment]
Wäre statt der doppelten Verneinung in "Es sollte nicht unveröffentlicht sein." die Üs. "Es sollte stets veröffentlicht sein." vorstellbar?

**Comment by max123kl** [comment]
@AK-CCM Danke für den Hinweis.
Hier liegt ein Fehler im Language-String vor, der dazu geführt hat, dass nicht die Übersetzung, sondern der engl. Text angezeigt wird.

**Comment by AK-CCM** [comment]
@max123kl
Eine gute Lösung, "unpublish" für gewöhnlich einheitlich mit "verstecken" zu übersetzen. Würde dennoch empfehlen, "displays" mit "zeigt ... an" zu übersetzen: Das ist näher am Wortlaut dran und zudem kürzer als die Konstruktion mit der Substantivierung "stellt ... zur Verfügung".

Generelle Frage an alle: Warum ist das Issue bereits closed? So wird m.E: ein konstruktiver Dialog einfach abgewürgt. Hab jetzt trotzdem hier geantwortet (sorry).

**Comment by max123kl** [comment]
@AK-CCM 
Der relevante Language-String "MOD_LOGIN_XML_DESCRIPTION" kommt insgesamt 4x in den Joomla-Sprachdateien vor. Im Allgemeinen versuchen wir die Übersetzungen für alle Fundorte gleichartig zu übersetzen.
Wie du in meinem "Verbesserungs-Commit" sehen kannst war der String schon übersetzt, er wurde nur, durch das doppelte Einfügen des Strings am Anfang der Zeile, im Backend nicht angezeigt. Wegen des begrenzten Platzes im Anzeigefeld wurde er zusätzlich gekürzt. Ich habe zu dieser Zeit keine Veranlassung gesehen auch noch die Formulierung zu ändern.

Zum Schließen des Issues:
Es ist allgemein üblich, nicht nur in diesem Repo, dass gelöste Fälle, die gemergt wurden, d.h. in den Branch aufgenommen wurden, anschließend geschlossen werden. Das hat nichts mit einem Abwürgen einer Diskussion zu tun. Ich finde die bisher verwendete Formulierung insofern richtiger, da es sich am angezeigten Bildschirm um neue Module dreht, deren Funktion kurz beschrieben werden.
Mir und ich glaube allen anderen auch, die hier an der Übersetzung arbeiten, ist bewusst, dass nicht jede Übersetzung elegant formuliert ist. Man muss oft einen Spagat zwischen Verständlichkeit und technisch korrektem Ausdruck ausführen.

Wenn dir Textstellen nicht gefallen oder noch besser, wenn du einen besseren Vorschlag hast – du darfst, nein du solltest, deine Ideen in einem neuen Issue formulieren. Du kannst sicher sein, dass jeder Vorschlag ernst genommen wird, solange damit kein Trollen oder Spammen verbunden ist.

@tecpromotion FYI

**Comment by tecpromotion** [comment]
Das merge ich durch. Danke für die sehr ausführliche und absolut super kommunizierte Antwort.
