### ISSUE TITLE
[4.0] Der String "Globale Einstellung" ist ziemlich lang. 

### ISSUE THREAD

**Issue by chmst** [joomlagerman/joomla#1930]
### Was soll verbessert / korrigiert werden
Der String "Globale Einstellung" ist ziemlich lang. 

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Beispiel:   Blog Layout

![grafik](https://user-images.githubusercontent.com/1035262/124118776-ff0af580-da71-11eb-968a-8f0fb0de7c81.png)

### Was wäre eine bessere Übersetzung / Bezeichnung

Eventuell überall kürzen auf "Global" ?

**Comment by tecpromotion** [comment]
Idee find ich richtig gut @chmst 
Magst du bitte einen PR dazu machen.
