### ISSUE TITLE
[4.0] Code für Textauszeichnung sichtbar

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1959]
### Was soll verbessert / korrigiert werden

![Issue](https://user-images.githubusercontent.com/853497/125171211-33d62580-e1b3-11eb-90b1-369dab7bdb91.png)

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend

### Was wäre eine bessere Übersetzung / Bezeichnung
Den Code der Textauszeichnung verstecken

### Joomla Version & Version der deutschen Sprachdatei
4.0.0v1-rc3 for Joomla! 4.0.0-rc3

### Zusätzlichen Informationen
Lt. Debug-Ansicht soll der String `JGLOBAL_ASSOC_NOT_POSSIBLE` hier angezeigt werden.
Zu finden in `administrator/language/de-DE/joomla.ini` und `api/language/de-DE/joomla.ini`

**Comment by tecpromotion** [comment]
@zero-24 kein html hier erlaubt?
