### ISSUE TITLE
Overrides vs Überschreibungen

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#196]
Sollen wir in Zukunft Overrides oder Überschreibungen benutzen?

Aktuell wird überall Overrides benutzt?

https://github.com/joomlagerman/joomla/pull/193#discussion_r101864029

**Comment by sisko1990** [comment]
@yvesh & @zero-24 Ich bin hier für Vorschläge offen. Aber „Überschreibungen“ glaube ich passt einfach nicht, da versteht man eher das englische ... Habt Ihr Ideen?

**Comment by zero-24** [comment]
hmm `Übersetzung überschreiben` oder `Sprachen überschreiben`? Denn genau das wird ja gemacht also der stand der offiziell ausgeliefert wird wird überschrieben. Aber ich kann auch damit leben wenn es weiterhin `Overrides` heißt da dies ja auch der aktuelle Standard ist und sich bis jetzt hat sich meines Wissens auch keiner darüber beschwert.

**Comment by peterpeter** [comment]
Moin
Ist ja ungefähr dasselbe wie Tags/Schlagwörter.

Das englische Wort kennt jeder, das deutsche ist eher beschreibend. Deshalb würde ich, wenn der Begriff als einzelnes Wort vorkommt (Formular-Label o.ä.) das englische/denglische nehmen. Und in den Tooltipps kann dann die deutsche Bezeichnung oder sogar eine Kombination angezeigt werden.

in der de-DE.ini beispielsweise
`JTAG="Tags"
JTAG_DESC="Tags/Schlagwörter einem Eintrag hinzufügen oder löschen."`
anstelle von
`JTAG="Schlagwörter"
JTAG_DESC="Schlagwörter einem Eintrag hinzufügen oder löschen."`

Nur meine Meinung :eyes:

**Comment by sisko1990** [comment]
Obwohl ich „Sprachen überschreiben“ als Begriff (nicht nur „Überschreibung“) gut finde. Denke ich wir bleiben erst mal bei „Overrides“ (gibt es ja bei den Templates auch).
