### ISSUE TITLE
[4.0] Beitragskategorie -> Kategorien

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1967]
### Was soll verbessert / korrigiert werden

<img width="656" alt="beiragskategorie" src="https://user-images.githubusercontent.com/1752513/125577153-fdcab9ab-1dcf-450c-8421-7275e958f4a0.png">

Hier sollte die Übersetzung nicht Beitragskategorie sondern Kategorien sein, um stimmig mit dem Menü links zu werden.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend

### Was wäre eine bessere Übersetzung / Bezeichnung

Kategorien

### Joomla Version & Version der deutschen Sprachdatei

4.0rc4

### Zusätzlichen Informationen

Danke A. Kunze für den Hinweis auf FB.

**Comment by chmst** [comment]
Ich weise drauf hin, dass schon ein PR eingereicht wurde, der die icons für Kontakte und Kontaktkategorien hinzufügt. Die Bezeichnung Kategorien ist dann mehrdeutig

**Comment by tecpromotion** [comment]
Guter Hinweis @chmst 

Dann muss es aber **Beitragskategorien** heißen.
