### ISSUE TITLE
[4.0] Simplification of the database labels during installation

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1968]
### Was soll verbessert / korrigiert werden

<img width="636" alt="datenbank-labels" src="https://user-images.githubusercontent.com/1752513/125578625-2fece3c3-b4e5-4a99-8a68-2e136bcfab4e.png">

Im Schritt "Datenbank-Konfiguration" sind die Labels der Inputfelder (zu), enden mit einem Punkt und verwirren vielleicht mehr als sie helfen.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Installation

### Was wäre eine bessere Übersetzung / Bezeichnung

Im Backend sind wir hier schon deutlich reduzierter und aufgeräumter unterwegs.

Angleichen?

<img width="285" alt="database-backend" src="https://user-images.githubusercontent.com/1752513/125579374-8d9d747a-91c8-4d75-b1d0-bf8699ffb570.png">

### Joomla Version & Version der deutschen Sprachdatei

4.0RC4

**Comment by tecpromotion** [comment]
Weitere Meinungen?
@SniperSister @webgras @astridx @chmst @coolcat-creations @joomlagerman/team

**Comment by astridx** [comment]
Wenn es dazu eine Dokumentation gibt finde ich das super.
Die Doku zu Joomla 3 ist hier: https://docs.joomla.org/J3.x:Installing_Joomla/
Für Joomla 4 habe ich noch keine gefunden, aber die 3er Version kann analog gelesen werden.

**Comment by max123kl** [comment]
Der Punkt ist überflüssig, wenn überhaupt könnte ein Doppelpunkt richtiger sein

@astridx 
Die Doku zu Joomla 4 ist hier: https://docs.joomla.org/J4.x:Installing_Joomla/de

**Comment by tecpromotion** [comment]
Meine Idee war einfach nur Datenbankserver etc. zu schreiben. 
Das ist viel zu viel unnötiger Balast.

**Comment by chmst** [comment]
Ich finde es beim server und datenbankname noch sinnvoll, dass ein hinweis auf den Hoster da steht.

Bei Passwort,
Benutzer
Tabellenpräfix

finde ich es super wenn es ganz puristisch ist
