### ISSUE TITLE
[4.0] Kern vs. Core

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#1975]
### Was soll verbessert / korrigiert werden

Alle Aufkommen von Kern ersetzen

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend

### Was wäre eine bessere Übersetzung / Bezeichnung

Core

### Joomla Version & Version der deutschen Sprachdatei

4.0RC4

**Comment by max123kl** [comment]
Dann müssten auch in JDocs und JHelp jede Menge Seiten aktualisiert werden.
Mike hat auf seiner Userseite eine Liste mit empfohlenen Wörtern veröffentlicht https://docs.joomla.org/User:M-b-o/helpintranslation
Dort wird Core nicht empfohlen.
Andererseits ist "Core" für mich wesentlich besser Joomla zuzuordnen als "Kern".
Man müsste Mike mal befragen.
