### ISSUE TITLE
[4.0] Benutzerliste Filteroptionen Begriffe in Auswahl doppelt

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#1977]
### Was soll verbessert / korrigiert werden
Im Backend kann die Benutzer-Liste über die Filteroptionen gesteuert werden.
Im Auswahlfeld "Status wählen" und "Aktivierung wählen" erscheinen jeweils die gleichen Begriffe, während im Core unterschiedliche benutzt werden.
![Filteroptionen](https://user-images.githubusercontent.com/853497/125734727-6eb8aa58-e9aa-4dcc-b46e-7f386455b7d6.png)

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend

### Was wäre eine bessere Übersetzung / Bezeichnung
Könnte eine der Auswahllisten mit anderen Begriffen gefüllt werden? 
Status könnte man mit "Freigegeben" und "Gesperrt" übersetzen

### Joomla Version & Version der deutschen Sprachdatei
J4 RC4, German 4.0.0-rc4.1

### Zusätzlichen Informationen

ergänzend dazu der folgende Kommentar im Core: https://github.com/joomla/joomla-cms/issues/34800#issuecomment-880542460

**Comment by tecpromotion** [comment]
Bitte einen PR anlegen, dann zieh ich mir das mal und schaue es mir auch im Backend mal an. Danke @max123kl
