### ISSUE TITLE
Massenmail vs. Serien-E-Mails

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#198]
https://github.com/joomlagerman/joomla/pull/197/files#r101865942

Serien-E-Mails -- Massenmail oder Massen-E-Mail hört sich zu sehr nach Spam an?

**Comment by sisko1990** [comment]
So habe ich das noch gar nicht betrachtet ... Serien-Mail bzw. Serien-E-Mail scheint mir angebracht. entsprechender Commit folgt gleich bzw. wird in #197 umgesetzt.
