### ISSUE TITLE
[4.0] Fatal error: Cannot declare class DE_DELocalise, because the name is already in use in ... administrator\language\de-AT\localise.php on line 17

### ISSUE THREAD

**Issue by ChristineWk** [joomlagerman/joomla#1980]
The following was reported in the forum: 
https://forum.joomla.de/thread/13987-fehler-in-neuen-language-dateien/

Is this known?

Found this one: https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-german

Thanks for information.

**Comment by tecpromotion** [comment]
Thanks for reporting.

**Comment by tecpromotion** [comment]
Bug confirmed

**Comment by tecpromotion** [comment]
will be fixed with our new build script #1382

cc @zero-24
