### ISSUE TITLE
Weblinks vs. Web Link (die Erweiterung)

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#199]
Wir haben uns im englischen darauf geeinigt das die Extension Web Link heißt, sollten wir eventuell auch so durch ziehen. Sprachdateien sind im EN noch nicht alle angepasst :)

https://github.com/joomlagerman/joomla/pull/195#discussion_r101862583

**Comment by sisko1990** [comment]
Laut Duden schreibt man den „Weblink“ zusammen: http://www.duden.de/rechtschreibung/Weblink
Hat im Deutschen auch den Vorteil, dass man so etwas bauen kann: Weblink-Kategorie / Weblinkkategorie. Für das Auge nicht ganz so einfach zu erkennen - gerade in einem Satz - wäre: Web Link Kategorie

Ich würde es davon abhängig machen, ob es um den Komponentennamen geht also „Web Links“ oder um den Weblink (auf den man nachher klicken kann) im Sinne des Duden.

Also:
Wenn Komponentenname, dann: „Web Links“
Wenn Link zum Klicken gemeint ist: Weblink

**Comment by zero-24** [comment]
:+1:
