### ISSUE TITLE
[4.0] Änderung der Standardsprache 

### ISSUE THREAD

**Issue by chmst** [joomlagerman/joomla#1998]
### Was soll verbessert / korrigiert werden
Die Standardsprache wurde gespeichert. Dies hat keinen Einfluss auf die von einem Benutzer in seinem Profil abweichend definierte oder die bei der Anmeldung ausgewählte Sprache.

Diesen Satz musste ich drei mal langsam lesen um ihn zu verstehen.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend. System -> manage -> language

### Was wäre eine bessere Übersetzung / Bezeichnung
Ich weiss es nicht - offen für Diskussionen:

"Die Standardsprache wurde gespeichert."  
Besser wäre "xx ist nun die Standardsprache"  (müsste im core / en geändert werden) bleibt also erst mal.

"Dies hat keinen Einfluss auf die von einem Benutzer in seinem Profil abweichend definierte oder die bei der Anmeldung ausgewählte Sprache."

Vielleicht: 

"Die vom Benutzer gewählte Sprache hat Vorrang". 

### Joomla Version & Version der deutschen Sprachdatei
J4.0

**Comment by tecpromotion** [comment]
@joomlagerman/reviewer @webgras @astridx @coolcat-creations Ideen jemand?

**Comment by astridx** [comment]
Hm. Da sieht man wie unterschiedlich man liest. Ich finden den Satz OK.

**Comment by tecpromotion** [comment]
> Hm. Da sieht man wie unterschiedlich man liest. Ich finden den Satz OK.

ich persönlich auch.

**Comment by AK-CCM** [comment]
Finde das Ganze auch etwas holprig und unnötig lang. Mein Vorschlag:
"Standardsprache gespeichert. Dies hat keinen Einfluss auf die individuell im Profil oder bei Anmeldung festgelegte Sprache."
