### ISSUE TITLE
[4.0] Überflüssiger Platzhalter

### ISSUE THREAD

**Issue by blueforce** [joomlagerman/joomla#2000]
### Was soll verbessert / korrigiert werden
<img width="313" alt="Bildschirmfoto 2021-07-29 um 07 45 21" src="https://user-images.githubusercontent.com/1141234/127438963-dce1a252-17a7-4dd0-bf5f-4f46d1dce31f.png">
hier hats ein «%s» zu viel

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
administrator/index.php?option=com_joomlaupdate
Im Tab «Extensions» (BTW: müsste das nicht Erweiterungen heissen?)

### Was wäre eine bessere Übersetzung / Bezeichnung
Korrekt wäre so:
<img width="372" alt="Bildschirmfoto 2021-07-29 um 07 55 56" src="https://user-images.githubusercontent.com/1141234/127439234-2ca7a4f6-6493-4537-b9ca-600a34d458c0.png">
ohne «%s»

**Comment by tecpromotion** [comment]
Das %s sollte es eigentlich nicht mehr geben. Wird geprüft.

**Comment by blueforce** [comment]
ja, hat sich erledigt, in der neusten Version ists behoben!
