### ISSUE TITLE
Falsche Übersetzung in Menüpunkten

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#2004]
### Was soll verbessert / korrigiert werden
In Menüpunkten wird der Begriff "übergeordnete Kategorie verwendet" das trifft bei Menüpunkten jedoch nicht zu:
<img width="1439" alt="grafik" src="https://user-images.githubusercontent.com/828371/127768322-7b50ce1d-bfaf-4582-acfa-906f514afde6.png">

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

In der Menüpunkt-Erstellung

### Was wäre eine bessere Übersetzung / Bezeichnung
Übergeordneter Menüpunkt wäre perfekt

### Joomla Version & Version der deutschen Sprachdatei
J4 RC5

**Comment by tecpromotion** [comment]
Reden noch von Menüeintrag aber klingt gut. 
Müssen nur schauen, dass es an anderer Stelle dann nicht auch greift. Machst du einen PR und prüfst es @coolcat-creations ?

**Comment by coolcat-creations** [comment]
Muss ich nach meiner Schulungswoche machen,aber gerne

**Comment by tecpromotion** [comment]
https://github.com/joomlagerman/joomla/blob/1c2f13c8f8a199a348cdcc9b224260527a375a19/administrator/language/de-DE/joomla.ini#L583
https://github.com/joomlagerman/joomla/blob/1c2f13c8f8a199a348cdcc9b224260527a375a19/api/language/de-DE/joomla.ini#L579
