### ISSUE TITLE
J4 RC5 Übersetzung Admin activation bisschen verwirrend

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#2005]
### Was soll verbessert / korrigiert werden
Bitte anmelden, um zu bestätigen, dass dieser Benutzer berechtigt ist, neue Benutzerkonten zu aktivieren.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Wenn der Admin sich einloggen soll um einen Account zu bestätigen

### Was wäre eine bessere Übersetzung / Bezeichnung
Um einen Benutzerkonto zu aktivieren, muss man mit entsprechenden Berechtigungen eingeloggt sein. 

### Joomla Version & Version der deutschen Sprachdatei
Jooml4 RC5

### Zusätzlichen Informationen
Man denkt, dass man durch das einloggen diesem anderen Nutzer Berechtigungen erteilt, Benutzerkonten zu aktivieren.

**Comment by tecpromotion** [comment]
Ich hab den jetzt mehrfach gelesen und finde das im Kontext ok.
Bin gerne für Vorschläge offen aber was besseres fällt mir grad nicht ein.
