### ISSUE TITLE
Übersetzung Workflows Grundstufe und Zielstufe

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#2006]
### Was soll verbessert / korrigiert werden
Die Bezeichnung ist falsch und nach Rücksprache mit den führenden Workflow Experten ;-) bisschen irreführend.
Ich schreibe diesen Issue als Notiz für später und zum Brainstorming wie wir es benennen wollen.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Grundstufe und Zielstufe
Stufen bei den Workflows

**Comment by AK-CCM** [comment]
Ist mit Grundstufe die erste Phase eines Workflows und mit Zielstufe die letzte Phase gemeint?
Falls zutreffend, dann einfach Startphase und Endphase?

**Comment by bembelimen** [comment]
Nein bei beiden.

**Comment by tecpromotion** [comment]
> Nein bei beiden.

Magst du einen Vorschlag (PR) machen?

**Comment by tecpromotion** [comment]
sollten wir mit Issue #1472 als einen PR umsetzen.
@coolcat-creations ich schließ den hier und assign dich für den #1472
