### ISSUE TITLE
[4.0] HTML-Formatierung bei Joomla Update nicht dargestellt

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#2021]
### Was soll verbessert / korrigiert werden
HTML Formatierung wird nicht dargestellt
![Warnung_bei_Update](https://user-images.githubusercontent.com/853497/129014211-719905cc-0d6d-4863-8db4-48557494a523.png)

### Wie reproduzieren
**Joomla Update → Installationsprüfung → Checkbox aktivieren "Warnung ignorieren"**
![Warnung_ignorieren_A](https://user-images.githubusercontent.com/853497/129015820-b98482f0-c2e7-4964-bf2b-e06bab8b1359.png)

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend

### Joomla Version & Version der deutschen Sprachdatei
4.0.0v1-rc5 for Joomla! 4.0.0-rc5

**Comment by zero-24** [comment]
PR: https://github.com/joomlagerman/joomla/pull/2022
