### ISSUE TITLE
Versionen: Keep forever != immer speichern

### ISSUE THREAD

**Issue by chmst** [joomlagerman/joomla#2032]
### Was soll verbessert / korrigiert werden
"Immer speichern" wird verstanden als "jedesmal speichern." und ist verwirrend.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
![grafik](https://user-images.githubusercontent.com/1035262/129753095-43d285f7-8b2f-40f6-97e6-35e1c3718d68.png)

### Was wäre eine bessere Übersetzung / Bezeichnung
gute Frage

### Joomla Version & Version der deutschen Sprachdatei
4.0.0

**Comment by max123kl** [comment]
Wie wäre "Dauerhaft speichern"?
