### ISSUE TITLE
Benutzerdefinierte Felder vs. eigene Felder

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#204]
Hi,
@sisko1990 wie möchtest du das in Zukunft machen? Die Idee hinter eigene Felder war das es kürzer ist und daher in die meisten Oberflächen passt.

@hamby und mir war aufgefallen das du das in einer PR noch nachträglich geändert hattest. 😄

**Comment by m-b-o** [comment]
Hi,
ich würde noch "Spezifische Felder" in den Raum werfen, ist meiner Meinung nach besser geeignet, custom fields in deutsch zu beschreiben

**Comment by chmst** [comment]
Hi, der Begriff ist echt scwer zu übersetzten .. aber was würdest du dir, wenn du newbie wärst, unter "Spezifiiche Felder" vorstellen? Da finde ich, dass Eigene Felder doch eher eine Assoziation wecken.

**Comment by sisko1990** [comment]
Nach Durchsicht von Joomla! wird gerne auch nur „Fields“ verwendet, daher würde ich dazu übergehen, sie auch einfach nur „Felder“ zu nennen (gerade weil sonst auch Menüs zu breit werden, wie das @zero-24 schon geschrieben hat). Wenn also in einem Text etwas von „[...] custom Fields“ steht, würde ich das „custom“ als Beschreibung für die Felder sehen und ab jetzt „eigene“ dafür übersetzen.

Damit ändert sich auch die Übersetzung für das Modul „Custom“ - hieß bis jetzt: „Benutzerdefiniertes Modul“; wird jetzt heißen: „Eigenes Modul“ - einen entsprechenden Commit werde ich gleich hier verlinken.

**Comment by chmst** [comment]
„Eigenes Modul“  - das finde ich sehr gut!
