### ISSUE TITLE
[4.0] Missing translations in configuration: com_search

### ISSUE THREAD

**Issue by AK-CCM** [joomlagerman/joomla#2041]
### Was soll verbessert / korrigiert werden
Fehlende Übersetzungen in Konfiguration: com_search

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend

### Joomla Version & Version der deutschen Sprachdatei
4.0.0 Stable & 4.0.0.1

### Zusätzlichen Informationen
![grafik](https://user-images.githubusercontent.com/33413085/130531429-83f7a83b-f6b6-4bb0-93b1-e39a342711ef.png)
Zuvor hatte ich ein kleines Update der Komponente installiert, das mir im Dashboard angezeigt wurde.

**Comment by zero-24** [comment]
@AK-CCM bitte installiere das letzte 3.10.x Sprachpaket über die 4.0.xer Version. Das nächste 4.0.xer Sprachpaket wird dann die Search Sprachdateien erstmal nicht mehr löschen.
