### ISSUE TITLE
[4.0] Missing translation in basic workflow

### ISSUE THREAD

**Issue by AK-CCM** [joomlagerman/joomla#2042]
### Was soll verbessert / korrigiert werden
Im Feld "Name" des Basic Workflows wird COM_WORKFLOW_BASIC_WORKFLOW ausgegeben.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend

### Joomla Version & Version der deutschen Sprachdatei
4.0.0 Stable & 4.0.0.1

### Zusätzlichen Informationen
![grafik](https://user-images.githubusercontent.com/33413085/130532584-f4c5181b-fd6c-4a93-8981-8adc2e9033c7.png)

**Comment by tecpromotion** [comment]
@AK-CCM ist im Core (en-GB) auch so. Ist derzeit nicht übersetzbar, da der String aus der SQL Anweisung kommt.
