### ISSUE TITLE
Typo in string "Joomla-Udpate-Mitteilung"

### ISSUE THREAD

**Issue by stell** [joomlagerman/joomla#2069]
### Was soll verbessert / korrigiert werden
Die Rechtschreibung

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
plg_system_updatenotification.ini

### Joomla Version & Version der deutschen Sprachdatei
4.0.3 / 4.0.3.1

**Comment by tecpromotion** [comment]
Hi @stell,
mach gerne einen konkreten Vorschlag. Danke.

**Comment by stell** [comment]
Mein Vorschlag wäre "Joomla-Update-Mitteilung"
