### ISSUE TITLE
[4.0] Texts for emptystate screens

### ISSUE THREAD

**Issue by chmst** [joomlagerman/joomla#2081]
### Was soll verbessert / korrigiert werden
Emptystate screens are meant to give a friendly and very short information, not for long descriptions. 
Texts must be shorter.

https://github.com/joomla/joomla-cms/pull/35644

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend, if "nothing found" 

### Was wäre eine bessere Übersetzung / Bezeichnung
An exact translation of the Englisch text - ~~not only here but it needs a check over all emptystate-texts.~~

### Joomla Version & Version der deutschen Sprachdatei
4.0

**Comment by chmst** [comment]
This is the screen with englisch text: 
![grafik](https://user-images.githubusercontent.com/1035262/134427825-3d0c594b-16c9-4c6e-98f2-7ff6328c5b3a.png)

**Comment by tecpromotion** [comment]
@chmst Please make a suggestion as PR, then we can all look at this together and happily use it in 4.0.4.1.

**Comment by tecpromotion** [comment]
@max123kl Do you have the time and inclination to optimise them by 20.10.2021?

**Comment by chmst** [comment]
COM_INSTALLER_MSG_DISCOVER_DESCRIPTION This is the message for discover.

At the moment I don't see other texts which are so long, the empty screens are good.

**Comment by max123kl** [comment]
Ich schau's mir an und mache im PR dann die Vorschläge.
@chmst Ich glaube da gibt es noch ein paar Strings, die ein wenig komprimiert werden könnten.

**Comment by tecpromotion** [comment]
@max123kl any news here?

**Comment by max123kl** [comment]
@tecpromotion - bin bis morgen Nachmittag vermutlich durch - bisher nur der bemängelte String von Christiane wirklich problematisch.
Ich mach dazu mal einen Draft-PR, dann könnt ihr meinen Vorschlag beurteilen.

**Comment by tecpromotion** [comment]
Prinzip KISS (keep it short & simple).

Mach einfach das draus: "Erweiterungen finden, die nicht den normalen Installationsprozess durchlaufen haben."
Fertig.
