### ISSUE TITLE
Fehlerhafte Tags in Mail-Templates zu Datenschutz-Anfragen

### ISSUE THREAD

**Issue by mipri25** [joomlagerman/joomla#2109]
### Was soll verbessert / korrigiert werden
In den beiden Mail-Templates "Datenschutz: Export von Daten anfordern - de-DE" (com_privacy.notification.export) und "Datenschutz: Entfernen von Daten anfordern - de-DE" (com_privacy.notification.remove) sind die verwendeten Tags in eckigen Klammern eingeschlossen statt in geschweiften, also z.B. [TOKENURL] statt {TOKENURL}.

Die daraus erzeugten Emails sind nutzlos, da sie den Namen der Tags statt deren Inhalt enthalten, also z.B.

```
Um diese Anfrage zu bestätigen, bitte einen der folgenden Schritte ausführen:

1. Aufruf der folgenden URL: [TOKENURL]

2. Den Token kopieren und unter folgender URL einfügen.
URL: [FORMURL]
Token: [TOKEN]
```

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Im Backend und in der erzeugten Email.

### Joomla Version & Version der deutschen Sprachdatei
Joomla! 4.0.3 Stable [ Furaha ] 12-September-2021 10:39 GMT
Sprachdateien de-DE Version 4.0.3.1

**Comment by tecpromotion** [comment]
https://github.com/joomlagerman/joomla/blob/1c2f13c8f8a199a348cdcc9b224260527a375a19/language/de-DE/com_privacy.ini?_pjax=%23js-repo-pjax-container#L23-L26
