### ISSUE TITLE
[4.0] Übersetzung von "COM_INSTALLER_TOOLBAR_PURGE" ist missverständlich

### ISSUE THREAD

**Issue by max123kl** [joomlagerman/joomla#2130]
### Was soll verbessert / korrigiert werden
Gleiche Situation wie in Issue #2121 auch in J4

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend

### Was wäre eine bessere Übersetzung / Bezeichnung
siehe #2121

**Comment by zero-24** [comment]
Wenn es der selbe string ist sollte sich das durch das hoch mergen lösen

**Comment by max123kl** [comment]
Dann könnte ich den PR #2131 auch löschen ??

Gleicher String - aber anderer Dateiname

**Comment by tecpromotion** [comment]
@zero-24 prüfst du das mal. danke.

**Comment by zero-24** [comment]
Done: https://github.com/joomlagerman/joomla/commit/626ba97452997989f192975d1b7c022ccaf6851a

**Comment by zero-24** [comment]
Nach 4.1 wurde es hier hochgeladen: https://github.com/joomlagerman/joomla/commit/71d26ffac3e1d93595946353f575c8b85a4465ae
