### ISSUE TITLE
Tags vs. Schlagwort

### ISSUE THREAD

**Issue by sisko1990** [joomlagerman/joomla#226]
Via E-Mail von einem Benutzer gemeldet:

> [...] Wir haben grad eine Kundenseite in Bearbeitung, die Tags/Schlagwörter verwendet, da fiel mir auf,
> dass diese inkonsistent übersetzt sind, und zwar bei den Optionen/Parameter mit ‚Schlagwörter anzeigen‘ (Menupunkt) und ‚Tags anzeigen‘ (com_content). 
> 
> Besser wäre meiner Meinung nach überall dasselbe. Und zwar ‚Tags‘, wenn du mich fragst. Denn ich denke die Mehrheit der Benutzer
> (eher jünger und an Anglizismen gewohnt) können mit dem Begriff ‚Tags‘ mehr anfangen als mit ‚Schlagwort‘ oder gar ‚Verschlagwortung‘, wie
> ich das mal irgendwo gelesen habe. [...]

**Comment by zero-24** [comment]
@sisko1990 hier: https://github.com/joomlagerman/joomla/pull/229 die PR für den Fix.

Wenn wir uns für "Tags" entscheiden sollten machen wir das ggf. in der Version für 3.7.x haben den Fehler aber erstmal behoben.

**Comment by sisko1990** [comment]
Wir bleiben erst einmal beim deutschen Wort „Schlagwort“ bzw. „Schlagwörter“. Mit ein Grund - nicht der einzige - nicht „Tags“ zu verwenden ist die Gefahr bei Anfängern den englischen Singular „Tag“ mit dem deutschen „Tag“ (Wie in „Wochentag“) zu verwechseln.
