### ISSUE TITLE
Tooltip Sortierung nicht übersetzt

### ISSUE THREAD

**Issue by sisko1990** [joomlagerman/joomla#227]
Via E-Mail von einem Benutzer gemeldet:
> [...] Du, ich habe da grad vorhin noch einen nicht übersetzten Tool-Tipp gesehen, falls du dich dem annehmen möchtest. Er erscheint, wenn man mit der Maus auf die Pfeile der Sortier-Reihenfolge fährt. Der ist anscheinend neu, den habe ich heute auch das erste Mal. [...]
![image](https://cloud.githubusercontent.com/assets/1638037/23587691/2f9a137c-01b2-11e7-8a44-d360af058adc.png)

**Comment by zero-24** [comment]
@sisko1990 wie genau hast du das nachgestellt? Ich kann das nicht reproduzieren bei mir in der beta3 ?

**Comment by peterpeter** [comment]
Hi Leudde
Ich hab das dem Jan gemeldet. Das ist auf einer Kundenseite von uns, J-3.6.5 mit Sprachpaket 3.6.5.1. Hab jetzt aber noch weitere Seiten geprüft, und das kam da so nicht vor. Alles paletti mit der Übersetzung dieses Tooltipps. 

Muss also aus irgendeinem Grunde ein Einzelfall sein, und bringt deshalb auch nicht viel, da explizit die Ursache zu suchen, Issue kann also, von mir aus jedenfalls, geschlossen werden.
