### ISSUE TITLE
[4.1] TinyMCE Editor Anpassungen

### ISSUE THREAD

**Issue by 7at1blow** [joomlagerman/joomla#2276]
### Was soll verbessert / korrigiert werden

Im Plugin TinyMCE ist die Pfadangabe zum Skin im Deutschen anders als die im Englischen.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Im Backend, im Plugin TinyMCE.

### Was wäre eine bessere Übersetzung / Bezeichnung

Keine Ahnung, weil ich (noch) nicht weiß, wie der wirklich korrekte Pfad lautet.

### Joomla Version & Version der deutschen Sprachdatei

J4.1
German 4.1.0.1, gerade festgestellt: im German 4.1.0.2 auch noch

### Zusätzlichen Informationen

Im englischsprachigen Backend von J4.1 steht beim TinyMCE-Plugin der Hinweis

- Copy your new skins to: /media/vendor/tinymce/skins/ui

und im deutschsprachigen lautet der Hinweis

- Neue Skins in das Verzeichnis „/media/vendor/tinymce/skins“ kopieren

also ohne das zusätzliche Verzeichnis "/ui".

**Comment by tecpromotion** [comment]
Vielen Dank!

**Comment by 7at1blow** [comment]
P.S.: Bei diesem Thread werden sogar zwei verschiedene Pfade angegeben, die dafür erforderlich sein würden:

https://forum.joomla.de/thread/15381-kurzanleitung-eigene-skins-designfarben-für-tinymce-erstellen-und-in-joomla-4-in/

**Comment by tecpromotion** [comment]
Halten uns da mal an den Core.
