### ISSUE TITLE
[4.1] "Sprachen-Overrides"

### ISSUE THREAD

**Issue by 7at1blow** [joomlagerman/joomla#2280]
### Was soll verbessert / korrigiert werden

Die Übersetzung des englischen Begriffs "Language Overrides" ins Deutsche.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

EN: System > Manage > Language Overrides
DE: System > Verwalten > Overrides

### Was wäre eine bessere Übersetzung / Bezeichnung

Die Verwendung des Ausdrucks "Sprachen-Overrides" gibt den Sachverhalt m. E. besser wieder als die derzeitige Übersetzung des englischen Begriffs "Language Overrides", die derzeit nur "Overrides" lautet.

### Joomla Version & Version der deutschen Sprachdatei

J4.1
German 4.1.0.2

**Comment by tecpromotion** [comment]
Klasse @7at1blow 
Das ergibt Sinn, PR ist fertig.

Danke!
<img width="441" alt="Bildschirmfoto 2022-02-18 um 21 29 00" src="https://user-images.githubusercontent.com/1752513/154756804-ce795b78-2688-42e4-9c11-a7ba43d6e49c.png">
