### ISSUE TITLE
[4.1] wording "Verlauf der Ausführung"

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#2328]
### Was soll verbessert / korrigiert werden

Im Reiter "Verlauf der Ausführung" der Aufgabe selbst, wird das failed mit gescheitert übersetzt. Wäre evtl. gut wenn dies einheitlich wäre?
![159119107-b77d3fe8-2d52-435e-b3e5-2277c1b93dc6](https://user-images.githubusercontent.com/1752513/159119894-b61a38a8-fd77-40f5-98e9-22dd48d1bd8b.png)

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

backend

### Was wäre eine bessere Übersetzung / Bezeichnung

An dieser Stelle hier finde ich aber die Übersetzung von times als Zeiten unpassend, da es ja eher die Male (Anzahl) sind. [>Ref](https://www.linguee.com/english-german/translation/times.html)

### Joomla Version & Version der deutschen Sprachdatei

4.1.0

### Zusätzlichen Informationen

_Originally posted by @heelc29 in https://github.com/joomlagerman/joomla/issues/2325#issuecomment-1072993211_

**Comment by tecpromotion** [comment]
@heelc29 wäre dann dein Vorschlag **Male (Anzahl)** zu verwenden?

**Comment by tecpromotion** [comment]
<img width="353" alt="Bildschirmfoto 2022-03-19 um 18 51 57" src="https://user-images.githubusercontent.com/1752513/159132877-a2883312-b9ed-463b-b9ea-b6b807118599.png">

Wäre fast nur für **Anzahl**

**Comment by zero-24** [comment]
Ausführungen und Fehlschläge?

**Comment by tecpromotion** [comment]
> Ausführungen und Fehlschläge?

Also komplett andere Strings? Finde ich auch OK.

**Comment by zero-24** [comment]
> > Ausführungen und Fehlschläge?
> 
> Also komplett andere Strings? Finde ich auch OK.

merged macht es deutlicher was gemeint ist oder?

**Comment by heelc29** [comment]
> @heelc29 wäre dann dein Vorschlag **Male (Anzahl)** zu verwenden?

Das "Anzahl" war nur als Ergänzung zur Bedeutung gemeint, da Male als eigenständiges Wort etwas komisch klingt ;) @tecpromotion
