### ISSUE TITLE
[4.1] new translation PLG_INSTALLER_OVERRIDE_N_FILE_UPDATED

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#2356]
### Was soll verbessert / korrigiert werden

Translation PLG_INSTALLER_OVERRIDE_N_FILE_UPDATED

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

backend

### Was wäre eine bessere Übersetzung / Bezeichnung

PLG_INSTALLER_OVERRIDE_N_FILE_UPDATED="%d überschriebene Dateien (Template-Overrides) wurden geändert."
PLG_INSTALLER_OVERRIDE_N_FILE_UPDATED_1="Überschriebene Datei (Template-Override) wurde geändert."

### Joomla Version & Version der deutschen Sprachdatei

4.1.1v1

### Zusätzlichen Informationen

Reported from "Elwood"
https://forum.joomla.de/thread/15655-%C3%BCberschriebene-dateien-wurden-ge%C3%A4ndert-bei-update-auf-4-1-1/

**Comment by astridx** [comment]
Meinst du man kann da auch noch einen Link zu
https://docs.joomla.org/J4.x:Improved_Override_Management/de
Integrieren?

**Comment by tecpromotion** [comment]
Puuh. Das schon sehr weit weg vom Core mit einem Link. 

ABER wenn du es im Core einreichst, unterstütze ich es und  versuche es schnell zu mergen. Dann haben wir es auch in deutschen ;)

**Comment by kitepascal** [comment]
PLG_INSTALLER_OVERRIDE_N_FILE_UPDATED="%d durch Template-Overrides überschriebene Dateien wurden im Original geändert. Im Template Manager können die Änderungen unter \\"Aktualisierte Dateien\\" überprüft werden."


...oder so ähnlich, wäre auf jeden Fall deutlich mehr Aussagekraft gegeben als Zwischending. Überall die Doku zu verlinken kann ja auch nicht die Lösung sein. Wobei insbesondere das Video in der Doku natürlich viel Klarheit schafft.

**Comment by max123kl** [comment]
@tecpromotion 
Die neue Übersetzung, die mit #2588 eingefügt wurde, ist leider auch nicht verständlicher.

Neuer PR folgt mit folgendem Vorschlag:
```
PLG_INSTALLER_OVERRIDE_N_FILE_UPDATED="%1$s Original-Dateien des Templates mit einem Override wurden aktualisiert. <a href=\'%2$s\'>Diese Änderungen sollten überprüft werden</a>."
PLG_INSTALLER_OVERRIDE_N_FILE_UPDATED_1="Eine Original-Datei des Templates mit einem Override wurde aktualisiert. <a href=\'%2$s\'>Diese Änderung sollte überprüft werden</a>."
```
