### ISSUE TITLE
Eigene Felder vs. benutzerdefinierte Felder

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#238]
Sieht man sich die ACL Einstellungen zu Benutzerdefinierten Feldern an, gibt es eine Einstellung Inhalt von eigenen Feldern bearbeiten. Ich finde das ehrlich gesagt ein bisschen verwirrend, da ich den Ausdruck "eigene" mit dem Ausdruck eigene Beiträge etc. gleichsetze. Im Grunde müsste man fast sehen ob das nicht tatsächlich eine zusätzliche ACL Option im CMS Wert wäre. Eigene Felder zu bearbeiten oder Fremde Felder. Ich hoffe ich hab gut ausgedrückt was ich meine. Hat jemand Gedanken dazu?
Ich wäre für benutzerdefinierte Felder oder Custom Fields...

![image](https://cloud.githubusercontent.com/assets/828371/24190700/a8cccc6e-0ee9-11e7-9739-bc81a146ab34.png)

**Comment by sisko1990** [comment]
Ob es „benutzerdefinierte Felder“ oder „eigene Felder“ heißt wurde hier schon diskutiert: #204
