### ISSUE TITLE
[4.1.3] Mehrsprachenstatus: Warnung enthält Fehler

### ISSUE THREAD

**Issue by ghost** [joomlagerman/joomla#2451]
### Was soll verbessert / korrigiert werden

<img width="949" alt="e" src="https://user-images.githubusercontent.com/89642616/168970849-68ecfc8b-126a-4f09-ae7e-8209eb37b0ff.png">

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Backend

### Was wäre eine bessere Übersetzung / Bezeichnung
Warnung! Ein Benutzer/Autor sollte nur einen verknüpften Kontakt haben, der der Sprache „Alle“ zugewiesen ist ODER ein Kontakt pro veröffentlichter Inhaltssprache.

### Joomla Version & Version der deutschen Sprachdatei
Joomla: 4.1.3
Sprachdatei: 4.1.3.2

### Zusätzliche Information
Den Grund für die Warnung habe ich nicht gefunden … andere Geschichte.

**Comment by tecpromotion** [comment]
Danke
