### ISSUE TITLE
Kleine Sammlung von offenen/fehlerhaften Übersetzungen.

### ISSUE THREAD

**Issue by dozentis** [joomlagerman/joomla#2456]
Hallo zusammen, bin noch im Joomla Unterricht und bevor ich es mal wieder vergesse, schnell eine kleine Zusammenfassung mit Bilder (hab ehrlicherweise auf die Schnelle auch nicht jeden String/Phrase gefunden)

### Joomla Version & Version der deutschen Sprachdatei
Version 2022-05-24

#### a) Menüeintrag hinzufügen, Menüeintragstyp 
Alle Kategorien in einer Beitragskategorie auflisten. In der Beschreibung steht fehlerhaft Plural "Beitragskategorie**n**"
[/de-DE/com_content.sys.ini](https://github.com/joomlagerman/joomla/blob/4.1-dev/administrator/language/de-DE/com_content.sys.ini)
![joomla-menueeintragstyp-allekatauflisten](https://user-images.githubusercontent.com/98828023/171424085-ca6a1029-4ccf-4afe-a2d1-44e0a0fcf54a.png)

#### b) Tiny-MCE Tabelle einfügen, Spalte bearbeiten
-> In der Menüleiste bzw. Kontextmenü steht noch: _Cut Column, Copy Column, Paste col before/after_
![joomla-tabelle-dt](https://user-images.githubusercontent.com/98828023/171424117-2163a000-2f77-42bc-8293-e700b58e05bd.png)

#### c) Modul **Benutzer-Anmeldung** hinzufügen 
-> siehe Beschreibung des Moduls dort steht am Ende: .... Benutzer `&rarr;_` (Entität von Pfeil rechts)
Hab einen ähnlichen Text in Zeile 12 hier gefunden [/de-DE/mod_login.ini](https://github.com/joomlagerman/joomla/blob/4.1-dev/administrator/language/de-DE/mod_login.ini) ; der Beginn des Textes ist allerdings leicht anders 
![joomla-modulbeschreib-user_ini](https://user-images.githubusercontent.com/98828023/171424150-c84a2e0d-0f5c-4374-8274-0743b40878b9.png)

#### d) Online-Hilfe zu Modul Zufallsbild
Und noch ein sehr sehr alter Fehler in der engl. Online-Hilfe (damals Tooltipp) des Moduls **Zufallbild**.
[DE:](https://help.joomla.org/proxy?keyref=Help41:Site_Modules:_Random_Image&lang=de) Bildtyp: Typ des Bildes PNG/GIF/JPG usw. (der Standard ist JPG).
[EN:](https://help.joomla.org/proxy?keyref=Help41:Site_Modules:_Random_Image&lang=en) Image Type: Type of image PNG/GIF/JPG etc. (the default is JPG).
In dieses Feld müßen zusätzliche Dateitypen **mittels Pipe-Symbol getrennt** werden, nicht mit Kommata.
Die korrekte Schreibweise wäre daher:   **jpg|png|gif**

### Was wäre eine bessere Übersetzung / Bezeichnung
zu a) [/de-DE/com_content.sys.ini](https://github.com/joomlagerman/joomla/blob/4.1-dev/administrator/language/de-DE/com_content.sys.ini)
Zeile 21: `COM_CONTENT_CATEGORIES_VIEW_DEFAULT_DESC="Zeigt eine Liste aller Kategorien in einer Beitragskategorien an."`
 Hier würde ich gerne einen aus Dozentensicht besser verständlichen Text formulieren; halten wir uns denn strikt und kosequent an den englischen Originaltexten? ;-) @tecpromotion ?

Das selbe gilt übrigens für die Informations-Texte in den globalen Einstellung z.B. Beiträge/Kategorien etc. oder in Menüeinträge:
Information: _Diese Einstellungen gelten für eine einzelne Beitragskategorie, wenn sie nicht von einem eigenen Menülink überschrieben werden._
Diese Information ist für viele Einsteiger sehr unverständlich, das kann ich aus 7 Jahre Erfahrung heraus bestätigen.

**Comment by heelc29** [comment]
Hier ein paar Infos:

**Zu b)**
Die Übersetzungen für den TinyMCE-Editor sind im [Core](https://github.com/joomla/joomla-cms/tree/4.1-dev/build/media_source/vendor/tinymce/langs) enthalten.
Diese sind auch noch mit diesen identisch, die von Tiny für Version 5 [heruntergeladen](https://www.tiny.cloud/get-tiny/language-packages/) werden können.
PS: Habe neulich auch noch ein paar nicht übersetzte Texte gesehen:
![image](https://user-images.githubusercontent.com/66922325/171851052-64520522-be9d-4bd3-9ba0-f3087ca5b5ac.png)

**Zu c)**
Dieser optische Fehler existiert schon so im Core:
![image](https://user-images.githubusercontent.com/66922325/171850231-6cdef695-aa47-4103-9b67-7f1a3514d9cd.png)
Passiert hier beim "escapen":
https://github.com/joomla/joomla-cms/blob/5665ddbf4abbc3691fcb4b0302094cdf7cac2f09/administrator/components/com_modules/tmpl/select/default.php#L64
In der Übersicht der Erweiterungen wird es "richtig" dargestellt:
![image](https://user-images.githubusercontent.com/66922325/171851847-451fde12-cb14-4bb5-b304-4f8972c732d4.png)

**Comment by tecpromotion** [comment]
@dozentis 
typo fix for a) with pr #2462

**Comment by tecpromotion** [comment]
zu d)
das müsste im joomla docs gemeldet werden, das wird nicht hier im repo gepflegt.

**Comment by tecpromotion** [comment]
zu b) das betrifft ALLE Sprachen so wie ich das sehe. Dafür müsste jemand einen PR für das joomla-cms repo schreiben.

**Comment by ghost** [comment]
> das müsste im joomla docs gemeldet werden, das wird nicht hier im repo gepflegt.

Erledigt en,de,nl: https://docs.joomla.org/Help4.x:Site_Modules:_Random_Image

@dozentis Nach Anmeldung in https://docs.joomla.org kannst du ändern, dann braucht es nicht einen Zufallsfund wie hier :-)

**Comment by dozentis** [comment]
Vielen Dank für die Erledigung...Am Montag beginne ich meinen neuen Joomla Kurs, und schau mal was ich unter der Woche noch finde , bzw ob alles gut aussieht. Schönes Wochenende euch allen
