### ISSUE TITLE
Custom Fields Automatische Anzeige

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#250]
Die Übersetzung der Inhalte im Dropdown, wahrscheinlich sogar von mir, braucht noch ne Korrektur,

![image](https://cloud.githubusercontent.com/assets/828371/25906847/0e48879e-35a6-11e7-9278-1f4989adb687.png)

Das Problem ist ja dass es sich um diesen "Event" handelt, aber nicht nur auf einen Beitrag bezogen ist. Muss also fast Englisch bleiben?

Hat jemand eine Idee?

**Comment by zero-24** [comment]
Nach dem Titel
Vor dem Inhalt
Nach dem Inhalt

?

**Comment by coolcat-creations** [comment]
Es geht aber um den Event-Trigger an sich... ist der immer nach dieser Logik gesetzt oder könnte ich ihn missbrauchen und an eine andere Stelle setzen?

**Comment by zero-24** [comment]
> könnte ich ihn missbrauchen und an eine andere Stelle setzen?

Ja. wann bzw. wo und ob die getriggert werden hängt an der componente. com_content macht das nach dem titel bzw vor un nach dem Beitrag.

Und da die anderen Componenten auch nur "Inhalt" produzieren können wir IMO auch Inhalt sagen

**Comment by zero-24** [comment]
@coolcat-creations kannst du dann hier zumachen?

**Comment by coolcat-creations** [comment]
@zero-24 mit Freude :)
