### ISSUE TITLE
[4.x]: Hauptbeitrag oder Haupteintrag

### ISSUE THREAD

**Issue by ghost** [joomlagerman/joomla#2511]
### Was soll verbessert / korrigiert werden?

Backend/Inhalt: 'Hauptbeiträge' wird in linken Menü verwendet, im 'Aktionen'-Button 'Haupteintrag'.

<img width="538" alt="hauptbeitrag" src="https://user-images.githubusercontent.com/89642616/175496755-8aa0f131-56a6-4769-86cb-658da2b930ce.png">

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend.

### Was wäre eine bessere Übersetzung / Bezeichnung

Hauptbeiträge, passt zu 'Beiträge'. 

Einträge werden für 'Menüeinträge' verwendet.

### Joomla Version

4.x (Empfohlen)

### Zusätzliche Informationen

Beim Erstellen des Issue kann kein Bildschirmfoto eingefügt werden.

**Comment by max123kl** [comment]
Nach meinem Verständnis bezeichnet "Beitrag" einen "article".
"Eintrag" wird dagegen für ein Listenelement (item) verwendet.

**Comment by tecpromotion** [comment]
> Nach meinem Verständnis bezeichnet "Beitrag" einen "article". "Eintrag" wird dagegen für ein Listenelement (item) verwendet.

So haben wir das auch immer geschult.

@Franzwohlkoenig können wir den schließen, mit dem Verständnis der Bedeutung?

**Comment by ghost** [comment]
> können wir den schließen

Das Problem bleibt leider. Es stellt sich auf Hilfeseiten, hier ein anderes Beispiel (Menüeintrag Kategorieblog):
 
<img width="600" alt="1200px-Help-4x-Menus-Item-Articles-Category-Blog-blog-layout-subscreen-de" src="https://user-images.githubusercontent.com/89642616/178892432-a06cafa8-2dd0-4cd2-8ec0-12b5619db4fb.png">

#### Demnach müsste die Beschreibung so lauten:

- Haupt**ein**trag.
  - Anzeigen: Haupt**bei**träge mit anderen Beiträgen zeigen.
  - Verbergen: Haupt**bei**träge verbergen.
  - Nur: Nur Haupt**bei**träge zeigen.

#### Ich habe es so gelöst:

<img width="481" alt="helpscreen" src="https://user-images.githubusercontent.com/89642616/178892542-b8a1a4e0-ca08-411a-9cf7-443df278c403.png">

Auch keine befriedigende Lösung, weil mit **Hauptbeitrag** eine Bezeichnung verwendet wird, die im Bildschirmfoto und im CMS aber **Haupteintrag** zeigt.

**Comment by max123kl** [comment]
@Franzwohlkoenig 
Ich denke auch, dass es hier Hauptbeitrag heißen sollte. Nice catch

@tecpromotion @zero-24 schaut ihr euch das bitte nochmal an:
![Hauptbeitrag](https://user-images.githubusercontent.com/853497/181805082-80969141-8d80-4e8d-a3ef-180ef399a76e.png)

Ich starte dazu vorsorglich einen PR

**Comment by tecpromotion** [comment]
Mach gerne mal den PR, dann ziehe ich mir das mal und schaue mir die Ausgabe in einer 4.2 an.
Danke @max123kl und @Franzwohlkoenig 

@heelc29 schau du auch bitte mit drauf dann im PR.

**Comment by ghost** [comment]
Ich danke euch.

**Comment by max123kl** [comment]
@Franzwohlkoenig Bitte melde dich bei @coolwebcreations (Mike Brandner). 
Wir brauchen deinen fachlichen Rat zu einem Problem im JDoc-Wiki.

**Comment by ghost** [comment]
@max123kl Erledigt.

**Comment by max123kl** [comment]
@Franzwohlkoenig Danke

**Comment by max123kl** [comment]
@Franzwohlkoenig 
Hallo Franz, ich bitte dich, dass du dich bei mir oder @ceford (Cliff Ford) zu melden. Wir möchten uns gerne mit dir besprechen, wie wir die Arbeit bei JDoc etwas abstimmen können.
Gruß Dieter

**Comment by ghost** [comment]
Ich warte ab, um welches [Problem](https://github.com/joomlagerman/joomla/issues/2511#issuecomment-1242701891) es geht.

**Comment by tecpromotion** [comment]
Tauscht euch bitte per E-Mail aus!

**Comment by max123kl** [comment]
@tecpromotion leider hat @Franzwohlkoenig keine E-Mail-Adresse veröffentlicht.

@Franzwohlkoenig Ich bitte dich hiermit, dass du mich oder [Cliff](https://github.com/ceford) über die in unseren Accounts hinterlegte Adresse anspricht.

**Comment by max123kl** [comment]
@tecpromotion leider hat @Franzwohlkoenig keine E-Mail-Adresse veröffentlicht.

@Franzwohlkoenig Ich bitte dich hiermit, dass du mich oder [Cliff](https://github.com/ceford) über die in unseren Accounts hinterlegte Adresse anspricht.
