### ISSUE TITLE
[4.2] plg_fields enDash vs Divis

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#2531]
### Was soll verbessert / korrigiert werden?

enDash, statt eines Divis

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend

### Joomla Version

4.x (Empfohlen)

**Comment by max123kl** [comment]
Ich bin schon dran – es gibt noch jede Menge weiterer Dateien

**Comment by tecpromotion** [comment]
> Ich bin schon dran – es gibt noch jede Menge weiterer Dateien

siehe PR und dann einfach in den committen.
