### ISSUE TITLE
[4.1] Improve German translation for COM_FINDER_QUERY_RESULTS

### ISSUE THREAD

**Issue by crimle** [joomlagerman/joomla#2542]
### Was soll verbessert / korrigiert werden?

**Ausgangslage**
In der Komponente «Suchindex» > Optionen ist die «Abfrageerklärung» aktiviert.
Wenn man zum Beispiel den Suchbegriff «Joomla» eingibt, wird die folgende Erklärung oberhalb der Suchresultate ausgegeben:

Ausgehend davon, dass „Joomla“ benötigt wird, wurden 2 Ergebnisse gefunden.

Dieser holprige Text sollte meines Erachtens schöner formuliert sein.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Front-End > Such-Index > Suchergebnisse

Ausgehend davon, dass „xxx“ benötigt wird, wurden 2 Ergebnisse gefunden.

COM_FINDER_QUERY_RESULTS
Ausgehend davon, dass %2$s, wurden %d Ergebnisse gefunden.

COM_FINDER_QUERY_RESULTS_0
Ausgehend davon, dass %2$s, wurde kein Ergebnis gefunden. Erneut suchen.

COM_FINDER_QUERY_RESULTS_1
Ausgehend davon, dass %2$s, wurde folgendes Ergebnis gefunden.

### Was wäre eine bessere Übersetzung / Bezeichnung

COM_FINDER_QUERY_RESULTS
Für den Suchbegriff %2$s, wurden %d Ergebnisse gefunden.

COM_FINDER_QUERY_RESULTS_0
Für den Suchbegriff %2$s, wurde kein Ergebnis gefunden. Erneut suchen.

COM_FINDER_QUERY_RESULTS_1
Für den Suchbegriff %2$s, wurde folgendes Ergebnis gefunden.

### Joomla Version

4.x (Empfohlen)

### Zusätzliche Informationen

Eigentlich finde ich ja die ganze Erklärung überflüssig. Ich blende sie für meine Webseiten deshalb aus.
Auch der Link hinter «2 Ergebnisse gefunden» ist unnötig, denn die Ergebnisse werden ja unmittelbar darunter aufgelistet.
«Ausgehend davon» tönt irgendwie sperrig.
«benötigt» finde ich in diesem Zusammenhang ein unpassendes Wort.

**Comment by tecpromotion** [comment]
Danke.

**Comment by zero-24** [comment]
PR has been created: https://github.com/joomlagerman/joomla/pull/3205 Thanks and sorry that it took that long here.
