### ISSUE TITLE
[4.2] Improve MFA wording

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#2545]
### Was soll verbessert / korrigiert werden?

Das Wort "Multi-Faktor-Authentifizierung" ist hier einfach zu lang.

<img width="612" alt="mfa" src="https://user-images.githubusercontent.com/1752513/180280376-d9e3de7a-04b2-4f5a-96bd-8df5a6e8da43.png">

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend

### Was wäre eine bessere Übersetzung / Bezeichnung

MFA als Abkürzung an dieser Stelle und dann ggf. in den Benutzereinstellungen und in den Plugins drauf hinweisen.

### Joomla Version

4.x (Empfohlen)

### Zusätzliche Informationen

@zero-24 wie besprochen erstmal der Reminder.

**Comment by zero-24** [comment]
ja wie gesagt wenn wir hier MFA nehmen macht es ggfs Sinn im Benutzer edit Formular dann: Multi-Faktor-Authentifizierung (MFA) zu nutzen d.h. die Abkürzung da einzuführen.

**Comment by heelc29** [comment]
Zur Info:

Der Sprachschlüssel `COM_USERS_HEADING_MFA` wird auch hier benutzt:
https://github.com/joomlagerman/joomla/blob/bed3cb8e28b157332b48182b29b58577af7a1852/administrator/language/de-DE/com_users.ini#L177
![image](https://user-images.githubusercontent.com/66922325/180286789-3ca93b61-a770-4686-95c6-35b8096acd9e.png)

Das steht auch hier beschrieben:
https://github.com/joomlagerman/joomla/blob/bed3cb8e28b157332b48182b29b58577af7a1852/administrator/language/de-DE/com_users.ini#L65

**Comment by tecpromotion** [comment]
Core PR?

**Comment by heelc29** [comment]
> Core PR?

Hab gerade den hier gefunden https://github.com/joomla/joomla-cms/pull/38208;
> 3. Replaced `COM_USERS_HEADING_MFA` with `COM_USERS_USER_MULTIFACTOR_AUTH`, because the first key is also the heading in the users table. For many languages, it makes sense to reduce it to **MFA**, so as not to inflate an already large table. However, the same key was used on the authentication page when logging in - the short **MFA** is inappropriate there, the full name is needed.

**Comment by tecpromotion** [comment]
Der wird es leider nicht mehr in die 4.2.0 schaffen und erst in die 4.2.1.
Wir haben derzeit das Phänomen, dass unsere Spaltenbeschriftungen so lang sind, dass wir nach rechts herauslaufen.

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/1752513/181919223-b1f8cc71-9e5f-4839-9130-136ca672e4b5.png)
