### ISSUE TITLE
Komponente/Schlagwort -> Online Hilfe

### ISSUE THREAD

**Issue by dozentis** [joomlagerman/joomla#2550]
### Was soll verbessert / korrigiert werden?

siehe Link, es werden die en-Bilder im Beitrag der Online Hilfe nicht angezeigt (falsche Umbrüche?)
[https://help.joomla.org/proxy?keyref=Help41:Tags&lang=de](https://help.joomla.org/proxy?keyref=Help41:Tags&lang=de)
**Bsp:**
[[Image:Help-4x-Components-Tags-Manager-screen-

en

.png|800px]]``

### PS

🤔 Wie kann ich das Label ändern? es wurde mir autom. auf enhancement gesetzt

**Comment by tecpromotion** [comment]
Hi @dozentis 
Das ist eher ein Joomla Documentation Thema und hat jetzt nichts direkt zu tun.

Ich weiße es mal @max123kl zu, da er auch docs macht.

@max123kl bitte den Issue schließen sobald gelesen.

**Comment by max123kl** [comment]
Hi @dozentis 
Wie Stefan richtig vermutet, betrifft dein entdeckter Fehler die deutsche Übersetzung folgender Hilfeseite: https://docs.joomla.org/Help4.x:Tags. Alle Hilfeseiten, die du aus Joomla heraus aufrufen kannst, sind Bestandteil des [Joomla Documentation Wikis](https://docs.joomla.org/Main_Page/de) und werden dort betreut.

Bisher wurde die Seite aber noch nicht vollständig übersetzt, sodass du eigentlich die nicht übersetzten Teile im englischen Original sehen müsstest.
Warum das nicht so ist und die Seite fehlerhaft dargestellt wird, kann ich ad hoc nicht sagen. Ich leite deine Fehlermeldung mal an das Translation Team weiter und hoffe, dass es bald repariert wird.

Wie @tecpromotion schon geschrieben hat, betrifft der Fehler die Dokumentation-Übersetzung und wir können in diesem Repo nicht weiterhelfen. Ich schließe deshalb dieses Issue.
