### ISSUE TITLE
[4.2] Texte für das Ausblenden von Spalten sind lang

### ISSUE THREAD

**Issue by chmst** [joomlagerman/joomla#2560]
### Was soll verbessert / korrigiert werden?

https://github.com/joomla/joomla-cms/issues/38503

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

![grafik](https://user-images.githubusercontent.com/1035262/185230288-2a254719-e09e-4a04-ae77-a8f2764bdb9e.png)

### Was wäre eine bessere Übersetzung / Bezeichnung

Die Übersetzungen "Veröffentlichte Einträge" usw. ist korrekt, Sie erzwingt aber eine ziemliche Breite der Ausgabe. Vorschlag: Man könnte das Wort "Einträge" doch auch weglassen? "Veröffentlicht, Versteckt, .." würde es auch tun. 

### Joomla Version

4.x (Empfohlen)

### Zusätzliche Informationen

Ich fände es besser, wenn statt des Textes ein icon  wie auch in der Spaltenüberschrift gezeigt würde - das ist aber Sache der Entwickler, nicht der Übersetzer.

Abwarten, was aus dem PR noch wird.

P.S. zufällig hatte ich debug modus an, das hat nichts zu bedeuten

**Comment by tecpromotion** [comment]
Warten wir mal auf den Core PR.
Sollte dieser nichts ergeben, kannst du gerne einen für unsere deutschen 4.2er machen @chmst

**Comment by richard67** [comment]
Wie willst du denn für jeden Spaltentitel einer Listenansicht ein eindeutiges Icon finden, bei dem man nicht lange herumsuchen muss, zu welcher Spalte es gehört? Mal angenommen, eine Tabelle hat 15 Spalten, dann musst du 15 kleine Icons unterscheiden können, und diese Icons müssen entweder noch mal bei den Tabellenspaltentiteln auftauchen oder so eindeutig sein, dass man sofort sieht, zu welcher Spalte sie gehören. Ich halte das für unmöglich und habe bisher auch noch keine einzige Software gesehen, die das so macht. Und ich habe schon viele gesehen. Alle verwenden die Titel der Spalten, um festzulegen, welche Spalten angezeigt werden und welche nicht. Aus meiner Sicht ist das mit den Icons ein denkbar unsinniger Vorschlag.

**Comment by chmst** [comment]
Natürlich nur, wenn schon icons da sind. Dann sollten die auch verwendet werden. Wie auf categories - die Spaltenüberschrift ist nicht "Versteckte Einträge" sondern das unpublished icon.

**Comment by richard67** [comment]
Und die anderen Spalten ohne Icon habe dann weiter den Spaltentitel … das macht das Dropdown für die Spaltenauswahl zu eine Mix aus Icons und Text und damit noch schwieriger für den Anwender zu erfassen, und wenn der Text bei den Spalten ohne Icon nicht gekürzt wird, ist für die benötigte Breite des Dropdown auch nichts gewonnen.

**Comment by tecpromotion** [comment]
Sollte mit #38507 erledigt sein.

**Comment by richard67** [comment]
Mittlerweile habe ich mir das noch mal genauer angeschaut und **muss zugeben, dass ich einen Fehler gemacht habe**.

**Mir war nicht mehr bewusst, dass wir bereits jetzt eine Mischung aus Icons und Texten für die Spaltentitel in den Listenansichten haben, so dass ich dachte, die Icons seien eine neue Idee.**

Ich verstehe jetzt, dass der Vorschlag von @chmst nur bezweckt, die Title in der Listenansicht und in der Spaltenauswahl zum Zeigen/Verstecken der Spalten angleichen will.

**Dennoch denke ich, dass ein Mix aus Icons und Texten furchtbar aussieht** und für den Benutzer schwer zu erfassen ist. Bei den Spaltentiteln in der Listenansicht haben wir die Icons mal gebraucht, als wir Platzprobleme mit der Breite hatten. Aber jetzt, wo man Spalten ausblenden kann, ist das Platzproblem weitgehend entschärft, und so denke ich, dass man langfristig wieder zur konsistenten Verwendung von Texten zurückkehren sollte, oder wenn Icons, dann überall, evtl. mit der Möglichkeit für den Benutzer, in den Optionen festzulegen, ob man Icons oder Texte will.

Möglicherweise wurde ich in meiner Wortwahl von der (aus meiner Sicht grauenhaften) Vorstellung eines Icon-und-Text-Mix inspiriert, so dass ich in meinem Kommentar **"denkbar unsinniger Vorschlag"** geschrieben habe. **Das war nicht wirklich nett und auch nicht korrekt, und dafür möchte ich mich aufrichtig entschuldigen.** Ich hoffe, das wird akzeptiert.

**Comment by chmst** [comment]
@richard67 danke für die Klarstellung. 

Mein eigentlicher Vorschlag für die Deutsche Übersetzung war, auf das Wort "Einträge" zu verzichten, das wäre einfach und prägnant, wurde ignoriert

> Was wäre eine bessere Übersetzung / Bezeichnung
Die Übersetzungen "Veröffentlichte Einträge" usw. ist korrekt, Sie erzwingt aber eine ziemliche Breite der Ausgabe. Vorschlag: Man könnte das Wort "Einträge" doch auch weglassen? "Veröffentlicht, Versteckt, .." würde es auch tun. 

Der zusätzlich Vorschlag braucht Programmierung und war daher nur eine Zusatzinformation
Könnte so aussehen - hier provisorisch
![grafik](https://user-images.githubusercontent.com/1035262/185469486-23fc8ed4-40d6-40c9-9e6a-9c8b1cbccbc8.png)
