### ISSUE TITLE
German Language Pack 4.2.0.1 für zurückgestelltes Update auf J4.2 im Backend deaktivieren

### ISSUE THREAD

**Issue by WM-Loose** [joomlagerman/joomla#2563]
### Was soll verbessert / korrigiert werden?

Würde irgend Jemand, der dazu berechtigt ist, das Updateangebot vom Server nehmen, damit nicht weitere User einfach das Backup installieren. Viele User sehen im Backend nur den Hinweis ohne zu wissen, dass 4.2 erst einmal installiert werden sollte bervor das LanguagePack an der Reihe ist. Solange das nun im Backend noch auftauscht laufen wir Gefahr, dass es auch angeklickt wird.

Ich bin der Meinung, dass wenn ich das eigentliche Update erst mal zurückziehe, hier auch die Sprachdatei zu berücksichtigen ist.

Wir haben zwar eine Rundmail an unsere Kunden versendet aber irgenwie wird es nicht wirklich beachtet, da teilweise auch Verantwortliche auf Kundenseite im Urlaub sind und Vertretungen einfach im Backend die angebotene Installation ausführen.

Letztlich landen die dann natürlich mit Fragen wieder bei uns. Echt unnötig und nervig das Ganze.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend

### Joomla Version

4.x (Empfohlen)

### Zusätzliche Informationen

https://forum.joomla.de/thread/16471-german-language-pack-4-2-0-1-f%C3%BCr-zur%C3%BCckgestelltes-update-auf-j4-2-im-backend/

**Comment by tecpromotion** [comment]
Hallo @WM-Loose 

Du kannst das 4.2.1.1 Sprachpaket eh nur ab 4.2 installieren. 
Und es spricht auch nichts direkt gegen eine frische 4.2, es wurde nur das Update über den Updateserver zurückgezogen. 
Weiterhin gibt es bereits den 4.2.1-rc2 zum Testen, auch da macht es wieder Sinn. 
Hier besteht kein Problem und auch kein Handlungsbedarf. 

Und am Dienstag erscheint ja schon die 4.2.1

(Versionsnummern korrigiert. Im Urlaub auf 1700m an was anderes gedacht 😀 )

**Comment by zero-24** [comment]
4.2.1 @tecpromotion ;-)

**Comment by tecpromotion** [comment]
Klar. 4.2.1-rc2. Ihr wisst was ich meine.
