### ISSUE TITLE
[4.x] Englische Begriffe in den Resultaten der Suchergebnisseite com_finder

### ISSUE THREAD

**Issue by dozentis** [joomlagerman/joomla#2622]
### Was soll verbessert / korrigiert werden?

In der Sucherergebnisseite der in Jom4 überarbeiteten Komponente Suchindex/Finder tauchen Begriffe wie article/tags etc auf (hinter dem Suchtyp) auf, die meines Erachtens noch keinen String haben. (siehe screenshot 1+2)

Dagegen sind diese Begriffe in der Dropdownliste der Auswahl der erweiterten Suche präsent (siehe screenshot 3)

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

No 1
![fehler-suchergebnisseite-joomla](https://user-images.githubusercontent.com/98828023/192288221-c0117180-7cbf-457f-91d4-6df7dcec2125.png)
No 2
![fehler-suchergebnisseite-joomla2](https://user-images.githubusercontent.com/98828023/192288226-649b9789-6afe-4877-b961-36af688d0de0.png)
No 3
![fehler-suchergebnisseite-joomla3](https://user-images.githubusercontent.com/98828023/192288229-cfca17e1-9105-454c-8e15-dad72648c5df.png)

### Was wäre eine bessere Übersetzung / Bezeichnung

Dürfte klar sein ;-)

### Joomla Version

4.x (Empfohlen)

**Comment by tecpromotion** [comment]
Hallo @dozentis 
Dies ist derzeit in keiner Sprache übersetzt.

@Hackwar wird das hier gemacht?
https://github.com/joomla/joomla-cms/blob/f520c98c64efb538e70e918acffb60d07e4d6b1e/administrator/components/com_finder/src/Helper/LanguageHelper.php#L62-L63

Wäre natürlich super, wenn wir dann auch die Übersetzung hier ausliefern, dies scheint aber derzeit im Core nicht zu funktionieren.

**Comment by Hackwar** [comment]
Jepp, von dort kommt das.

**Comment by Hackwar** [comment]
Das müsste 
PLG_FINDER_QUERY_FILTER_BRANCH_S_CATEGORY="Kategorie"
PLG_FINDER_QUERY_FILTER_BRANCH_S_CONTACT="Kontakt"
PLG_FINDER_QUERY_FILTER_BRANCH_S_ARTICLE="Beitrag"
PLG_FINDER_QUERY_FILTER_BRANCH_S_NEWS_FEED="Newsfeed"
PLG_FINDER_QUERY_FILTER_BRANCH_S_TAG="Schlagwort"
sein. Hab ich jetzt ehrlich gesagt nicht getestet.

**Comment by dozentis** [comment]
Danke fürs Feedback
> PLG_FINDER_QUERY_FILTER_BRANCH_S_ARTICLE="Beitrag"

Hab es eben mal schnell als Override eingegeben, aber keine Änderung zu sehen

**Comment by Hackwar** [comment]
Mea culpa, du hast Recht, das ist momentan nicht übersetzt.

**Comment by Hackwar** [comment]
Bitte als Bug im CMS melden und mich dort erwähnen, dann kümmere ich mich in den nächsten Wochen darum. Momentan (heute) komme ich da nicht zu.

**Comment by tecpromotion** [comment]
Danke @Hackwar 
Da heute ja bereits 4.2.3 erscheint und auch gebaut ist, macht das erst mit 4.2.4 eh Sinn.
Ich erstelle den Issue.

**Comment by tecpromotion** [comment]
@Hackwar ich hab dir einen Issue angelegt: https://github.com/joomla/joomla-cms/issues/38846
