### ISSUE TITLE
[4.3] placeholder JGLOBAL_TYPE_OR_SELECT_SOME_TAGS 

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#2788]
### Was soll verbessert / korrigiert werden?

Placeholder im Feld Schlagwort is zu lang
![Bildschirmfoto 2023-04-13 um 21 32 00](https://user-images.githubusercontent.com/1752513/231864325-f66e5380-a9ca-4eb1-bdee-f3faa47304fa.jpg)

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

all

### Was wäre eine bessere Übersetzung / Bezeichnung

JGLOBAL_TYPE_OR_SELECT_SOME_TAGS="Schlagwort eingeben oder auswählen"

### Joomla Version

4.x (Empfohlen)

**Comment by max123kl** [comment]
Vorschlag:
`JGLOBAL_TYPE_OR_SELECT_SOME_TAGS="Schlagwort(e) eingeben oder auswählen"`
