### ISSUE TITLE
TinyMCE Übersetzung wird nicht aktualisiert

### ISSUE THREAD

**Issue by hacki65** [joomlagerman/joomla#280]
### Wie kann der Fehler nachgestellt werden
Bei einer Aktualisierung des Sprachpakets wird die Übersetzung des TinyMCE nicht aktualisiert

### Zusätzlichen Informationen
Im Komplettpaket von Joomla! ist die aktualisierte Version der de.js für den TinyMCE integriert.
Kann das reine Sprachpaket nicht auch diese aktuelle Version mit updaten?

**Comment by tecpromotion** [comment]
Die de.js findest du hier: https://github.com/joomlagerman/joomla/blob/master/media/editors/tinymce/langs/de.js

Das Komplett-Paket nutzt die gleichen Dateien.
Was genau funktioniert nicht? Bei allen Projekten? Vereinzelt?
Wurde die de.js beim Update auf 3.8.1 überschrieben?

**Comment by hacki65** [comment]
Das Problem ist, das bei installiertem Joomla! die de.js nicht ersetzt wird. Im reinen Sprachpaket ist diese Datei NICHT enthalten und kann somit auch nicht aktualisiert werden!

**Comment by tecpromotion** [comment]
Die Datei ist enthalten, Paket gerade runtergeladen und getestet.
Werde dies in einer Installation aber gerne testen.

**Comment by hacki65** [comment]
Die Datei ist eben NICHT enthalten !!!
[https://github.com/joomlagerman/joomla/releases/download/3.8.1v1/de-DE_joomla_lang_full_3.8.1v1.zip](url)

**Comment by hacki65** [comment]
Noch mal zum Verständnis: z.b. Update von Joomla! 3.7.5 auf 3.81, updaten des deutschen Sprachpakets auf 3.8.1v1 - Ergebnis: TinyMCE hat noch die alte de.js !!!

Bei einer Neuinstallation von Joomla! 3.8.1 in der deutschen Version von J!German ist die Datei natürlich enthalten, aber eben nicht bei einem Update das reinen Sprachpakets.

**Comment by tecpromotion** [comment]
Fehler gefunden,
danke @hacki65 

Ich hatte mir nicht das Release sondern direkt den Download gezogen.

**Comment by zero-24** [comment]
hmm kann es ggf. daran liegen das es hier: https://github.com/joomla/joomla-cms/blob/staging/media/editors/tinymce/langs/de.js auch eine Datei gibt? Oder was war der Fehler den du gefunden hast @tecpromotion?

**Comment by sisko1990** [comment]
Also die Grundidee bei der de.js bzw. aller anderen Sprachdateien für TinyMCE ist, dass die aktuelle Version im Core ist und nicht durch das Sprachpaket aktualisiert werden muss ...

**Comment by sisko1990** [comment]
@hacki65 Gab es den Probleme mit der Sprachdatei für TinyMCE (der im Core übrigens noch 4.5.7 ist; aktuell ist 4.7.1)

**Comment by hacki65** [comment]
Bei der letzten Version 3.8.1 des deutschen Pakets wurde ein kleiner Fehler behoben, der im original Joomla! vorhanden ist. Es gäbe 2 Möglichkeiten: entweder das deutsche Sprachpaket beinhaltet die korrigierte Version für den TinyMCE oder jemand macht einen PullRequest direkt im Joomla GitHub, um den Fehler dort zu korrigieren. Dann wäre im deutschen Sprachpaket gar keine TinyMCE Übersetzung nötig.

Das ganze ist auch ehrlich gesagt nicht so dramatisch (ist ein Leerzeichen falsch drin) - siehe PR #278 - aber wenn im großen CMS-Paket dies korrigiert wurde, warum nicht auch im kleinen Sprachpaket?

Beste Lösung wäre wohl, es im Joomla! GitHub per PR für die 3.8.2 reinzubauen.

Gruß hacki65

**Comment by zero-24** [comment]
Ich hab das ganze mal gemerged 😄 Sollte demnach mit 3.8.2 behoben sein.

**Comment by hacki65** [comment]
Danke zero-24
