### ISSUE TITLE
[4.x] Translation "Empty trash"

### ISSUE THREAD

**Issue by crimle** [joomlagerman/joomla#2851]
### Was soll verbessert / korrigiert werden?

An vielen Orten (Beiträge, Kategorien, Menüeinträge, Module, ...) gibt es den Button [Papierkorb leeren]. Diese Beschriftung finde ich ungenau. Der Begriff [Papierkorb leeren] impliziert, dass der **ganze** Inhalt des Papierkorbs gelöscht wird. Der gleichlautende Begriff bei Windows tut zum Beispiel genau das. Bei Joomla ist es jedoch so, dass nur die ausgewählten Elemente aus dem Papierkorb entfernt werden. 
<img width="502" alt="Papierkorb-leeren" src="https://github.com/joomlagerman/joomla/assets/51155809/521cff5d-d139-43b1-969c-24dd5825c3ae">

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Im Backend. Überall wo man [Filter-Optionen] > [Status wählen] = Papierkorb auswählen kann.

### Was wäre eine bessere Übersetzung / Bezeichnung

a) «Aus Papierkorb löschen»
b) «Aus Papierkorb entfernen»
c) «Endgültig löschen»

### Joomla Version

4.x (Empfohlen)

### Zusätzliche Informationen

Der englische Begriff im Joomla Core ist ebenso ungenau. Dort heisst es [Empty trash]. Aber genau genommen stimmt das nicht: der Trash ist danach nicht empty.

**Comment by tecpromotion** [comment]
Hallo @crimle 
vielen Dank für deinen Vorschlag.
Ich würde dich gerne dazu ermuntern dies im Joomla-Core mit einem Issue oder gleich einem PR einzureichen.
Dies betrifft ja alle Sprachen und sollte dann am besten top-down passieren.

**Comment by crimle** [comment]
Ok, ich habe den Vorschlag eingereicht https://issues.joomla.org/tracker/joomla-cms/41106
PR? Ich weiss, was das ist, aber mir fehlen die Kenntnisse, um einen PR zu erstellen.

**Comment by tecpromotion** [comment]
PR https://github.com/joomla/joomla-cms/pull/41119

**Comment by tecpromotion** [comment]
Wenn https://github.com/joomla/joomla-cms/pull/41119 gemerged wird, kriegen wir das durch ein automatisches Issue mit.
