### ISSUE TITLE
[4.x/5.x] a) gleich > selbe, b) Fenster > Browser-Tab

### ISSUE THREAD

**Issue by 7at1blow** [joomlagerman/joomla#3090]
### Was soll verbessert / korrigiert werden?

Die oft auftretende Auswahl-Option
- "_In **gleichem** Fenster öffnen_"

müsste besser bzw. korrekterweise
- "_**Im selben** Fenster öffnen_"

lauten, weil es sich um dasselbe und nicht um das Gleiche handelt.

Meines Erachtens wäre es noch korrekter, wenn die Übersetzung
- "Im selben **Browser-Tab** öffnen"

lauten würde, da es sich ja um einen Browser-Tab handelt und nicht um ein Browser-Fenster.

Analog dazu sollte m. E. dann auch die Option
- "In **neuem Fenster** öffnen"

dann
- "In **neuem Browser-Tab** öffnen"

übersetzt sein.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

JBROWSERTARGET_PARENT
JBROWSERTARGET_NEW

Aber ggf. u. a. auch anwendbar bei:
JBROWSERTARGET_NEW_TITLE
JBROWSERTARGET_DOWNLOAD

### Was wäre eine bessere Übersetzung / Bezeichnung

s. o.

### Joomla Version

5.x

**Comment by tecpromotion** [comment]
@joomlagerman/reviewer Feedback dazu?

**Comment by chmst** [comment]
Ich würde schreiben "Im selben Fenster öffnen".  

Stimme zu bei gleich ->selbe
aber glaub, man kann eine etwas lässigere Sprache behalten. "In selbem Browser-Tab" klingt etwas künstlich obwohl es akademisch korrekt ist.

**Comment by 7at1blow** [comment]
Dein Vorschlag bzgl. des "in" und "im" finde ich gut. Habe meine Formulierungen deswegen gerade diesbezüglich geändert. Danke

**Comment by tecpromotion** [comment]
> Dein Vorschlag bzgl. des "in" und "im" finde ich gut. Habe meine Formulierungen deswegen gerade diesbezüglich geändert. Danke

@7at1blow magst du dann auch einen PR dazu machen?

**Comment by 7at1blow** [comment]
@tecpromotion Du hattest mir ursprünglich mitgeteilt, ich möge dazu ein Issue schreiben. Reicht das nicht?

Und wie geht das denn mit einem zusätzlichen PR mit richtigen Zuordnungen? Könntest Du das nicht machen, damit ich dann sehe, wie Du das gemacht hast und mit welchen Zuordnungen ("_Choose different branches or forks above to discuss and review changes._")?

**Comment by 7at1blow** [comment]
Danke @tecpromotion.

Erlaube mir drei Verständnisfragen dazu:
a) Warum wird Dein PR in Deinem letzten Post zweimal genannt/angeführt?
b) Greift der PR jetzt nur für 5.1 und nicht auch für 4.x?
c) Muss ich jetzt noch etwas tun im PR? Was soll ich denn jetzt dazu prüfen?
Sorry, kenne mich eben noch zu wenig aus hier mit der Materie.

**Comment by tecpromotion** [comment]
Der kommt dort wegen der Zuweisung des Issues und umgekehrt. 

Ich wollte das für 4 eigentlich nicht mehr ändern. Da ist es seit Jahren so und 5 ist wo es weitergeht.
