### ISSUE TITLE
Das 'System - Umleitungen' ist deaktiviert.

### ISSUE THREAD

**Issue by peterpeter** [joomlagerman/joomla#311]
### Wie kann der Fehler nachgestellt werden
/Backend/Komponenten/Umleitungen:
Wenn das redirect-Plugin deaktiviert ist, erscheint in obiger Ansicht eine System-Meldung vom Typ Error:

Fehler
Das „System - Umleitungen“ ist deaktiviert. Damit diese Komponente funktioniert, muss es aktiviert sein.

Müsste wohl heissen:

Fehler
Das **Plugin** „System - Umleitungen“ ist deaktiviert. Damit diese Komponente funktioniert, muss es aktiviert sein.

**Comment by tecpromotion** [comment]
Danke @peterpeter 
Du darfst gerne beim nächsten Mal direkt einen Pull Request machen, das ist sehr simple und hilft uns schneller die Stelle zu finden bzw. auch gleich nach Sichtung zu mergen.

**Comment by peterpeter** [comment]
Hi
Würd ich gerne machen, resp. hätte ich auch gemacht, bin hier aber grad auf der Arbeit, teilweise auch unterwegs, und meine Rpos sind nicht up to date. 👀

**Comment by tecpromotion** [comment]
Geht direkt über den Browser. Hab einen PR gemacht da ich das etwas anders gelöst hab und noch eine Vereinheitlichung. @zero-24 und @coolwebcreations schauen noch drüber und dann ist das in der 3.8.4 mit drin.
