### ISSUE TITLE
Umbennenung Artikelkategorien zu Beitragskategorien [4.x/5.x] 

### ISSUE THREAD

**Issue by Engholm** [joomlagerman/joomla#3125]
### Was soll verbessert / korrigiert werden?

In der Administratorspache de_DE steht im Dashboard bei den Quickicon die Bezeichnung **Artikelkategorien**. In der deutssprachingen Version wurde allerdings aus den ursprünglichen _Articles_ -> Beiträge. Hier würde es also aus Konsistenzgründen besser passen, die Beschriftung Beitragskategorien anstatt Artikelkategorien zu bennen:

<img width="627" alt="artikelkategorien" src="https://github.com/joomlagerman/joomla/assets/1927499/98520b40-bec6-43d7-8ee0-45203f284010">

1. 

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Im Backend

### Was wäre eine bessere Übersetzung / Bezeichnung

Anstatt der Bezeichnung Artikelkategorie(n) besser -> Beitragskategorie(n)

### Joomla Version

5.x

### Zusätzliche Informationen

 joomla/administrator/language/de-DE/com_categories.ini

**Comment by tecpromotion** [comment]
Hallo @Engholm 
Danke für den Issue.

Das passiert scheinbar nur in Kombination mit der Anzahl an Beiträgen. Nice catch!

**Comment by zero-24** [comment]
PR ist merged. Danke :)
