### ISSUE TITLE
[5.1] Database installation Fields

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#3131]
https://github.com/joomla/joomla-cms/pull/43054

**Comment by tecpromotion** [comment]
@joomlagerman/maintainers bisher haben wir da eine sehr kurze Übersetzung, die bisher auch immer gut funktioniert hat m.M.n.

Anmerkungen?

**Comment by zero-24** [comment]
Stimme ich zu dann würde ich hier zu machen. 👍
