### ISSUE TITLE
[4.x/5.x] Apostroph create Json error

### ISSUE THREAD

**Issue by thuebschmann** [joomlagerman/joomla#3164]
### Was soll verbessert / korrigiert werden?

in admin/de-DE/lib_joomla.ini
JLIB_JS_AJAX_ERROR_PARSE="Ein Parsing-Fehler trat bei der Verarbeitung der folgenden JSON-Daten auf:<br /><code style='color:inherit;white-space:pre-wrap;padding:0;margin:0;border:0;background:inherit;'>%s</code>"
crates issue in css

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Beackend

### Joomla Version

4.x

### Zusätzliche Informationen

Durch das ' einsteht ein fehlerhafter JSON-String 
Ich habe nur Joomla und das deutsche Sprachpaket installiert, der Fehler kann mit einem entsprechnen Sprach overide behoben werden.

![grafik](https://github.com/joomlagerman/joomla/assets/20397591/61eb12c3-0443-46fa-9371-f70b74787db8)

**Comment by tecpromotion** [comment]
Hallo @thuebschmann 
Ich kann das leider bisher nicht reproduzieren.
Ich kann dir jetzt nur anbieten, wenn du mir ein Backup der Seite zur Verfügung stellst, dass sich das jemand mal anschaut.
Gehe aber derzeit nicht von einem globalen Problem aus.
Link zum Backup bei Bedarf gerne an stefan.wendhausen@community.joomla.org senden.

**Comment by thuebschmann** [comment]
Ich habe den fehler lokalisert, es scheit an einem Eigenen plguin zu liegen

**Comment by tecpromotion** [comment]
> Ich habe den fehler lokalisert, es scheit an einem Eigenen plguin zu liegen

Danke für dein Feedback @thuebschmann
