### ISSUE TITLE
[5.1] Improve German translation for Users > Filter Options

### ISSUE THREAD

**Issue by crimle** [joomlagerman/joomla#3170]
### Was soll verbessert / korrigiert werden?

![grafik](https://github.com/joomlagerman/joomla/assets/51155809/f81cffad-e947-4d11-923e-9de9347bb343)
The first filter dropdown is related to the column «Freigegeben». 
The second filter dropdown is related to the column «Aktiviert».
The German translation for these two dropdowns is bewildering, because both dropdowns contain the same options «Aktiviert» and «Deaktiviert».

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Goto Benutzer > Verwalten > then click «Filter Optionen»

### Was wäre eine bessere Übersetzung / Bezeichnung

Instead of
- Status wählen -
Aktiviert 
Deaktiviert 

I suggest the following translation
**- Freigabe wählen -
Freigegeben 
Nicht freigegeben**

_The English Text is more precise:

- Select state -
Enabled
Disabled

- Select active state -
Activated
Unactivated_

### Joomla Version

5.x

**Comment by crimle** [comment]
Why has my proposal not met any attention here for a long time?

**Comment by zero-24** [comment]
Hi,

entschuldige hab den issue nicht mehr auf'm Schirm gehabt, wenn es bereits im Core mit unterschiedlichen strings gemacht wurde müssten wir das auch so regeln können. Ich schaue mir das in den nächsten Tage mal genauer an und baue einen PR.

**Comment by zero-24** [comment]
Hmm leider ist es doch nicht so einfach wie gedacht da wir da im Core "JENABLED" und "JDISABLED" nutzen.

![image](https://github.com/joomlagerman/joomla/assets/2596554/6a61087e-5d18-4918-8ec8-06bc58643ae5)

@tecpromotion @crimle  was haltet ihr davon COM_USERS_HEADING_ENABLED von "Freigegeben" auf "Status" zu ändern? Damit passen dann auch wieder Aktiviert und Deaktiviert.

**Comment by tecpromotion** [comment]
Magst du mal einen PR machen für 5.2.0, dann  kann man sich das im Backend auf einer Testinstanz mal ansehen.

**Comment by zero-24** [comment]
Mache ich heute Abend

**Comment by zero-24** [comment]
PR here: https://github.com/joomlagerman/joomla/pull/3199 @tecpromotion Closing here as there is a PR.

**Comment by crimle** [comment]
> Hmm leider ist es doch nicht so einfach wie gedacht da wir da im Core "JENABLED" und "JDISABLED" nutzen.
> @tecpromotion @crimle was haltet ihr davon COM_USERS_HEADING_ENABLED von "Freigegeben" auf "Status" zu ändern? Damit passen dann auch wieder Aktiviert und Deaktiviert.

Eine pragmatische Lösung, mit der ich leben kann. Vielen Dank!
