### ISSUE TITLE
[4.x/5.x] Unklare Anleitung zum Joomla-Update

### ISSUE THREAD

**Issue by ChristineWk** [joomlagerman/joomla#3178]
### Was soll verbessert / korrigiert werden?

Es ist nicht erkennbar, dass man die Checkbox davor anklicken "muss." 

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Screenshot ist im Issue 43408
Danke. 

### Was wäre eine bessere Übersetzung / Bezeichnung

a) Ich habe ein Backup erstellt und meine Erweiterungen sind kompatibel
b) Vor dem Update bitte um Bestätigung, dass ein Backup erstellt worden ist.
c) Ich bestätige, dass ........... 

### Joomla Version

4.x

### Zusätzliche Informationen

siehe bitte [Issue ](https://github.com/joomla/joomla-cms/issues/43408)

**Comment by tecpromotion** [comment]
Bitte einen Vorschlag in neutraler Sprache machen.

**Comment by ChristineWk** [comment]
a) Habe ein Backup erstellt und meine Erweiterungen sind kompatibel
(bei der englischen Version steht: 've .....)

b) Ja, mir ist bewusst, dass vor Beginn der Sicherung dringend ein Backup empfohlen wird

**Comment by chmst** [comment]
Ich denke dass mit der neutralen Schreibweise die Entscheidung zwischen "du" und "Sie" vermieden werden soll. 
Aber "Ich bestätige dass ... " hat damit nichts zu tun das findet man ja auch überall.   

Ich finde b) ganz gut und es ist eine exakte Übersetzung aus dem Englischen

**Comment by Sieger66** [comment]
Fehlt nur noch der Punkt am Ende des Satzes des Übersetzungsvorschlages wobei es aber wohl korrekt z.B. lauten sollte:

Ja, mir ist bewusst, dass vor dem starten eines Update's dringend ein Backup empfohlen wird.

Unter anderem auch weil der anschließende Button mit "Update starten" bezeichnet ist und im Vorschlag offensichtlich wohl auch ein "Missgeschick" vorliegt:
"vor Beginn der Sicherung dringend ein Backup empfohlen wird"
Sicherung = Backup :smiley:

Wobei es aber auch noch den Button "Hochladen & Installieren" gibt,
oberhalb dessen ebenso dieser Sprachstring mit Checkbox ausgegeben wird.

Wobei es nun auch einen PR gibt:
https://github.com/joomlagerman/joomla/pull/3184

Language Constant is:
COM_JOOMLAUPDATE_UPDATE_CONFIRM_BACKUP
Inhalt:
I'm aware that a backup before any update is highly recommended.

**Comment by zero-24** [comment]
Hi, entschuldigt hab den falschen issue, also dem im CMS, zu gemacht. Ich wollte natürlich hier kommentieren.

Wie im PR notiert haben Stefan und ich uns entschieden die bestehende Formulierung so zu behalten wie sie ist. Im Ende ist es immer eine verpflichtende Option welche jemand bestätigt und ich bezweifle das es hier wirklich einen Unterschied macht und würden gerne nicht mit der Ansprache brechen.

Vielen Dank für euren Input :)

**Comment by Sieger66** [comment]
Es bleibt ja die Möglichkeit diesbezüglich selbst einen eigenen Text für den Sprachstring COM_JOOMLAUPDATE_UPDATE_CONFIRM_BACKUP festzulegen per Sprach-Override und/oder zusätzlichen CSS-Code in der Datei: `/media/templates/administrator/atum/css/user.css` zu verwenden wie z.B. dort erklärt:
https://github.com/joomla/joomla-cms/issues/43408#issuecomment-3154801665
