### ISSUE TITLE
5.x Custom Fileds - Checkbox - Text ist nicht gleich Ausgabe

### ISSUE THREAD

**Issue by ChristineWk** [joomlagerman/joomla#3207]
### Was soll verbessert / korrigiert werden?

Wenn ein Beitrag erstellt & der entsprechende Reiter gewählt wird, um die Custom Fields zu befüllen gibt es als Auswahl "info". Wird aber: "Information" angezeigt. 

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend. Siehe bitte screenshot. 

### Joomla Version

5.x

### Zusätzliche Informationen

Infos sind bitte hier zu finden: 
https://forum.joomla.de/thread/21155-custom-fileds-checkbox-text-ist-nicht-gleich-ausgabe/?postID=155894#post155894
Vielen Dank

**Comment by tecpromotion** [comment]
Hallo @ChristineWk 
Es gibt einige fest definierte Sprachstrings in Joomla.
Dazu gehört u.a. INFO: https://github.com/joomlagerman/joomla/blob/1e413e98d97d60ddb35e284753ad7fc67bba8f97/administrator/language/de-DE/joomla.ini#L44

**Comment by ChristineWk** [comment]
@tecpromotion 
OK, Danke für die Info
