### ISSUE TITLE
[5.x] Improve translation of the button [Update]

### ISSUE THREAD

**Issue by crimle** [joomlagerman/joomla#3293]
### Was soll verbessert / korrigiert werden?

In English, there are the terms «refresh» and «update», which have pretty different meanings.
«Refresh» means «Reload the current view on a computer screen».
«Update» means «Bring something up to date».

In German we often use the word «Aktualisieren» for either of the two English words.
It is obvious that in some cases the word «Aktualisieren» may be misleading.
  
Currently, Joomla uses the term «Aktualisieren» with the meaning «Install the update for the selected extension».
On the other hand, «Aktualisieren» is commonly used with the meaning «Refresh the screen» or «Reload the page».

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

English Back-End 
Go to System > Update > Extensions 
Press the button [Check for Updates]
Provided there is at least one extension update available, you will see the button [Update] in the top left corner

German Back-End 
System > Updates > Erweiterungen
Den Button [Auf Updates prüfen] drücken 
Vorausgesetzt, dass mindestens 1 Erweiterungs-Update verfügbar ist, wird oben links der Button [Aktualisieren] angezeigt

![2024-09-23-Erweiterungen_Aktualisieren](https://github.com/user-attachments/assets/19bc0ba0-2e6b-4744-98cf-f5365efec25b)
![2024-09-23-Extensions_Update](https://github.com/user-attachments/assets/dda94789-3ece-45f1-96eb-18ed88d3a28b)

### Was wäre eine bessere Übersetzung / Bezeichnung

I think «**Installieren**» is a much preciser term which makes it absolutely clear what is going to happen, when clicking this button. «Aktualisieren» might lead to the conclusion, that the current browser window will be reloaded. A function that is in fact necessary from time to time, when working in Joomla's Back-End. 

### Joomla Version

5.x

### Zusätzliche Informationen

This change might not be overwhelming. But it's a tiny contribution to preciser wording and making it easier for less experienced users.

**Comment by zero-24** [comment]
Hmm i do get where you are coming from. But to me just 'Installieren' is even more confusing and would let me ask whether i'm now installing something new. Maybe 'Updates installieren' or something like that could work but i would say thats just to long. Looking at the play store for example they are also just using aktualisieren when updating apps.

**Comment by crimle** [comment]
Well, in my opinion it is pretty obvious, that we can install something new as well as install an update. I quite agree, that «Updates installieren» is too long. May I suggest the germanized English term «Updaten»?

**Comment by zero-24** [comment]
Hi, ich hab mich nochmal abgestimmt und wir sind zu dem Ergebnis gekommen das wir es erstmal bei Aktualisieren lassen wollen. Wenn wir doch noch einen besseres Wort finden können wir uns das gerne nochmal ansehen.

**Comment by crimle** [comment]
Mir fällt gerade auf, dass der Button beim Joomla-Update mit [Update starten] beschriftet ist:
![2025-01-14-Joomla-Update-starten](https://github.com/user-attachments/assets/4d22143e-3ffb-4291-939f-772bfd2385b1)
Das wäre für mich die perfekte Lösung für den Button bei den Erweiterungs-Updates.

**Comment by tecpromotion** [comment]
Reden wir über oben links?
![2025-01-14_12-52-38](https://github.com/user-attachments/assets/55a2af29-7319-4b94-959c-62cd2984d82b)

**Comment by crimle** [comment]
Ja genau! «Aktualisieren» ist hier für mich immer ein wenig missverständlich. Besonders im Browser kommt das «Aktualisieren» im Sinn von «Neu laden der Seite» sehr häufig vor. «Update starten» ist ganz klar und stimmt erst noch mit dem Starten des Core-Updates überein.

**Comment by tecpromotion** [comment]
Im englischen ist es halt "Update" was wir im deutschen für diesen Case bisher mit "Aktualisieren" übersetzt haben.
Nicht zu verwechseln mit nach Updates suchen, auf Updates prüfen etc.

Ich bringe das noch mal ins Spiel. Danke @crimle.
