### ISSUE TITLE
[4.x/5.x] Task Scheduler Quots

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#3294]
### Was soll verbessert / korrigiert werden?

Is this an issue with German or a general issue?

<img width="309" alt="grafik" src="https://github.com/user-attachments/assets/092a4880-1e29-43e3-aa84-a84916d41146">

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Task Scheduler Test Task Process

### Was wäre eine bessere Übersetzung / Bezeichnung

"

### Joomla Version

5.x

**Comment by heelc29** [comment]
@coolcat-creations Could you check #3160

**Comment by coolcat-creations** [comment]
Sorry old mistake, I always forget I have to reinstall the languages after Major Updates

**Comment by tecpromotion** [comment]
They actually appear under Updates and no reinstallation is necessary.

**Comment by coolcat-creations** [comment]
Not always - Sometimes a reinstallation helps - sometime I have even to install the language package manually
