### ISSUE TITLE
[5.2] Falsche Charaktere in Modul Beschreibung 

### ISSUE THREAD

**Issue by drmenzelit** [joomlagerman/joomla#3315]
### Was soll verbessert / korrigiert werden?

https://github.com/joomlagerman/joomla/blame/effc7cbaf899a77dbf17ca47000a4c4634d9709a/administrator/language/de-DE/mod_user.sys.ini#L9
![grafik](https://github.com/user-attachments/assets/8ca080a1-92d1-4604-9516-7d5a5998087e)

Die Anführungszeichen werden falsch dargestellt.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend

### Joomla Version

5.x

**Comment by tecpromotion** [comment]
Hi @drmenzelit 
Ja, das geht leider nicht anders, da sie in der anderen Ansicht richtig sind. Das wird da von Joomla falsch gerendert meine ich.

**Comment by drmenzelit** [comment]
In Englisch werden einfache Anführungszeichen benutzt, wäre in Deutsch für den Fall nicht auch sinnvoll? So sieht es echt blöd aus.

**Comment by tecpromotion** [comment]
Es sollen halt Pfeile sein, dass man weiß, wo man hin muss 🫤

**Comment by drmenzelit** [comment]
Ahh, ich habe an der falschen Stellen im Language File geschaut ... ja, dann ist ein Problem von Core.
