### ISSUE TITLE
[5.2] Benutzermenü | Eingeloggt als [Name] -> Angemeldet: [Name]

### ISSUE THREAD

**Issue by AK-CCM** [joomlagerman/joomla#3325]
### Was soll verbessert / korrigiert werden?

Im Benutzermenü wird als erster Eintrag "Eingeloggt als [Name]" ausgegeben, obwohl Benutzername und Passwort auf der Login-Seite durch Anklicken bzw. Antippen des Buttons "Anmelden" und nicht "Einloggen" abgeschickt werden. Umgekehrt melden sich Benutzer über den Menüeintrag "Abmelden" vom Adminbereich ab und nicht über "Ausloggen".

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend

### Was wäre eine bessere Übersetzung / Bezeichnung

**MOD_USER_TITLE:** Angemeldet: %s

### Joomla Version

5.x

### Zusätzliche Informationen

https://www.facebook.com/groups/joomla.deutschland/permalink/2827026144137840/

**Comment by tecpromotion** [comment]
Hier sehe ich wenn dann #3326
