### ISSUE TITLE
[5.2] Benutzermenü | Eingeloggt als [Name] -> Hallo [Name]!

### ISSUE THREAD

**Issue by AK-CCM** [joomlagerman/joomla#3326]
### Was soll verbessert / korrigiert werden?

Alternativ zu Issue #3325 soll der erste Eintrag im Benutzermenü "Eingeloggt als [Name]" in eine Begrüßung wie z.B. "Hallo [Name]!" geändert werden, um unmissverständlich klarzustellen, dass dies kein Eintrag zum Anklicken ist.

Zudem sollte der Eintrag mit dem Status oder der Begrüßung anders formatiert werden als das Mouseover im Benutzermenü.

Der erste Menüeintrag im Benutzermenü ließe sich sogar einsparen, wenn der letzte Menüeintrag in "Abmelden: [Name]" umbenannt wird.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

Backend > Benutzermenü

### Was wäre eine bessere Übersetzung / Bezeichnung

**MOD_USER_TITLE:** Hallo %s!

### Joomla Version

5.x

### Zusätzliche Informationen

https://www.facebook.com/groups/joomla.deutschland/permalink/2827026144137840/

**Comment by tecpromotion** [comment]
Finde ich eine gute Idee.
Wäre hier allerdings dann für eine Änderung im Core vorab auf "Hallo [name]": https://github.com/joomla/joomla-cms/blob/e3cc332fcc3f7988b1ab0594018670b1ace5fae4/administrator/language/en-GB/mod_user.ini#L11

**Comment by AK-CCM** [comment]
Meinst Du eine einheitliche Anpassung in allen Sprachen?

**Comment by tecpromotion** [comment]
Genau.

**Comment by tecpromotion** [comment]
Der PR dazu https://github.com/joomla/joomla-cms/pull/44386
