### ISSUE TITLE
[5.x] Eine Tour machen

### ISSUE THREAD

**Issue by chmst** [joomlagerman/joomla#3349]
### Was soll verbessert / korrigiert werden?

"Eine Tour machen" ist kein schönes Deutsch. Nach einem Brainstorming und viel Unsinn  kam Jürgen Langer mit dem Vorschag, statt dessen "Erste Schritte" zu schreiben. 
Das gefällt mir sehr und ich stelle es zur Diskussion

### Wo wird der Sprachstring angezeigt (Frontend/Backend)

![grafik](https://github.com/user-attachments/assets/70188c93-7bf7-4e02-9ec8-8f03729be9b8)

### Was wäre eine bessere Übersetzung / Bezeichnung

![grafik](https://github.com/user-attachments/assets/9a55d958-ff7b-4983-99c5-e36035d4acb1)

### Joomla Version

5.x

**Comment by tecpromotion** [comment]
@chmst ich habe einen PR für 5.3 gemacht.
