### ISSUE TITLE
[4.0] Improvement for the stats module

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#367]
https://github.com/joomla/joomla-cms/pull/17056

**Comment by n-at-work** [comment]
Hallo Stefan Wendhausen und alle Contributors,

Könntet ihr bitte für den String MOD_STATS_ARTICLES_VIEW_HITS im Core Statistik-Modul von Joomla den Vorschlag berücksichtigen:

Statt "Anzahl Beitragshäufigkeit" was ungeeignet ist, "Anzahl Artikelansichten" reinnehmen.

Das wäre im Language Pack in die de-DE.mod_stats.ini
Aus der Version 3.8.12 hab ich den Txt inkl Vorschlag:

; Joomla! German Translation
; Copyright (C) 2005 - 2014 Open Source Matters. All rights reserved.
; Copyright (C) Translation 2008 - 2014 J!German (www.jgerman.de)
; License http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL, see LICENSE.php
; Note : All ini files need to be saved as UTF-8 - No BOM

MOD_STATS="Statistiken"
MOD_STATS_ARTICLES="Beiträge"
MOD_STATS_ARTICLES_VIEW_HITS="Anzahl Artikelansichten"
MOD_STATS_CACHING="Zwischenspeicherung"
MOD_STATS_FIELD_COUNTER_DESC="Zugriffzähler anzeigen?"
MOD_STATS_FIELD_COUNTER_LABEL="Zugriffszähler"
MOD_STATS_FIELD_INCREASECOUNTER_DESC="Anzahl der Zugriffe eingeben, um den Zähler zu erhöhen."
MOD_STATS_FIELD_INCREASECOUNTER_LABEL="Zähler hochsetzen"
MOD_STATS_FIELD_SERVERINFO_DESC="Serverinformationen anzeigen"
MOD_STATS_FIELD_SERVERINFO_LABEL="Serverinformationen"
MOD_STATS_FIELD_SITEINFO_DESC="Seiteninformationen anzeigen"
MOD_STATS_FIELD_SITEINFO_LABEL="Seiteninformationen"
MOD_STATS_GZIP="GZIP"
MOD_STATS_MYSQL="MySQL"
MOD_STATS_OS="OS"
MOD_STATS_PHP="PHP"
MOD_STATS_TIME="Zeit"
MOD_STATS_USERS="Besucher"
MOD_STATS_WEBLINKS="Weblinks"
MOD_STATS_XML_DESCRIPTION="Das Statistik-Modul zeigt Informationen zur Server-Installation und Statistiken der Website an, wie z.&#8239;B.: Besucher, Anzahl der Beiträge in der Datenbank und Anzahl der Weblinks die angeboten werden."

Vielen Dank im Voraus.
 
Herzliche Grüße,
N-at-Work
