### ISSUE TITLE
Incorrect Packages for Joomla! 3.8.7

### ISSUE THREAD

**Issue by hacki65** [joomlagerman/joomla#416]
Leider sind die Download-Pakete für das neue Release 3.8.7 defekt oder falsch:

- Joomla_3.8.7-Stable-Full_Package_German.tar.bz2 = **182 KB**
- Joomla_3.8.7-Stable-Full_Package_German.tar.gz = **269 KB**
- Joomla_3.8.7-Stable-Full_Package_German.zip = **458 KB**

Könnt Ihr das bitte fixen? Danke.

**Comment by tecpromotion** [comment]
Super. Danke @hacki65 
Das Release wurde aktualisiert.
