### ISSUE TITLE
Release 3.8.7 is not a Full Installation Package

### ISSUE THREAD

**Issue by hacki65** [joomlagerman/joomla#417]
Leider ist euch wieder ein Fehler beim Full-Paket unterlaufen. So wie jetzt wäre es ein UPDATE Paket und kein FULL Paket (Images fehlen und der Installation-Ordner ist fast leer) ;).
Damit lässt sich keine Neuinstallation ausführen.

Müsst Ihr nochmal fixen bitte... Danke!

#416

**Comment by tecpromotion** [comment]
Die Pakete wurden wie immer angelegt.
Ich vermute grad, dass in den Sourcen was nicht drin war.
Alle 3 Full-Install-Pakete wurden nun grad getestet.

https://github.com/joomlagerman/joomla/releases/tag/3.8.7v1

Danke @hacki65
