### ISSUE TITLE
[3.8.9] Check Backend Modules

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#437]
### Wie kann der Fehler nachgestellt werden
Login to Backend 

### Das erwartete Ergebnis
Module titles are translated

### Das aktuelle Ergebnis
![grafik](https://user-images.githubusercontent.com/1752513/41108210-4204594c-6a74-11e8-97f0-d5a2beb6b547.png)

### System Information
3.8.8

### Zusätzlichen Informationen
![grafik](https://user-images.githubusercontent.com/1752513/41108210-4204594c-6a74-11e8-97f0-d5a2beb6b547.png)

**Comment by tecpromotion** [comment]
Reporter @widmann-it

**Comment by tecpromotion** [comment]
@zero-24 Das sollte wie bei den Benutzergruppen doch kein Stress sein. Meinst nicht?

**Comment by chmst** [comment]
Es gibt bei jedem Modul einen Parameter unter Erweiterte Einstellungen: Automatischer Titel. Er steht defalt mäßig leider auf "nein". Stell ihn auf "ja" und es wird übersetzt.

**Comment by Bakual** [comment]
> Er steht defalt mäßig leider auf "nein". Stell ihn auf "ja" und es wird übersetzt.

Ich denke das war früher anders? Zumindest haben das alle meine Seiten aktiviert 😄 
Vielleicht sollte dieses Issue nicht hier sondern im Core eröffnet werden.

**Comment by chmst** [comment]
ja, denke ich auch. Ich glaub eher dass der Parameter neu ist - aber habe mich nie damit befasst.

**Comment by ahotzler** [comment]
Ist hier auch so. Seiten, die ich in letzter Zeit aufsetzte, haben nicht-übersetze Modul-Titel und der von Christiane genannte Parameter steht auf "Nein". Seiten, die ich von 2.x auf 3 updated habe, verhalten sich genau umgekehrt.

**Comment by Bakual** [comment]
Es wurde mit 3.4.2 (https://github.com/joomla/joomla-cms/pull/5793) im Installations-SQL geändert nachdem das Feature in J3 nicht mehr existierte.
Mit 3.5.0 wurde das Feature durch JM wieder eingeführt https://github.com/joomla/joomla-cms/pull/7925, aber die Anpassung im SQL wurde nicht mehr gemacht.

Das erklärt warum Seiten welche vor 3.4.2 erstellt wurden den Titel übersetzt haben und Seiten welche danach erstellt wurden nicht mehr 😄 

Also grundsätzlich funktionierts es wie gedacht. Wenn man will könnte man darüber diskutieren ob man das SQL wieder so einstellen soll dass der automatische Titel standardmässig bei Neuinstallation aktiviert ist.

**Comment by chmst** [comment]
Ich frag mich wozu man einen  Parameter braucht, wenn man per Sprachoverride den Text anpassen kann. Und das an einer Stelle, wo es 99,99% der Admins wahrscheinlich egal ist, was da steht
Ich bin gegen alle überflüssigen Parameter ;) vielleicht könnte man in V4 drüber diskutieren ihn weg zu lassen?

**Comment by Bakual** [comment]
Der Parameter macht dass da steht "Last 5 articles" statt bloss "Last articles". Die Übersetzung ist nur noch nen Goodie obendrauf.

**Comment by tecpromotion** [comment]
@zero-24 close?

**Comment by zero-24** [comment]
Hab ne PR gemacht: https://github.com/joomla/joomla-cms/pull/21330 da es nix mit der Übersetzung zu tuen hat mache ich hier zu.

**Comment by zero-24** [comment]
CMS PR wurde abgewiesen. Ich schaue mal ob was das zumindest im deutschen neu install Paket aktivieren können.

**Comment by tecpromotion** [comment]
Willst du das noch für 3.9.0 machen @zero-24 oder später?

**Comment by zero-24** [comment]
Ja aber das ist der Plan aber nicht mehr vor meinem Urlaub. Im Grunde muss hier: https://github.com/joomlagerman/joomla/blob/3.9-dev/installation/sql/mysql/localise.sql ein SQL Befehl rein welcher dann sowas macht hier: https://github.com/joomlagerman/joomla/blob/3.9-dev/installation/sql/mysql/localise.sql#L8 aber das möchte ich mir genauer ansehen.

**Comment by zero-24** [comment]
Auch wenn es länger gedauert hat hier ist eine PR: https://github.com/joomlagerman/joomla/pull/695
