### ISSUE TITLE
[RFC] The use of the term "Webseite" or "website" should be reconsidered

### ISSUE THREAD

**Issue by astridx** [joomlagerman/joomla#550]
We often misuse the term "Webseite"

A "Webseite" is actually an HTML document that is part of a "Website": https://de.wikipedia.org/wiki/Webseite
With Joomla! we creates usually a Website to which several (dynamic) Websites belong (https://de.wikipedia.org/wiki/Website)

What do you think?

**Comment by tecpromotion** [comment]
@zero-24 @coolwebcreations Was meint ihr? Ich bin auch dafür mal alles durchzugehen und sauber zu machen. 
Ist dann ein relativ großer Schritt und 3.9 wäre perfekt dafür.

**Comment by zero-24** [comment]
Hört sich gut an.

Einer schaut sich alle aktuellen [Website (75)](https://github.com/joomlagerman/joomla/search?q=Website) 
Strings an und einer die [Webseite (30)](https://github.com/joomlagerman/joomla/search?q=Webseite) Ich kann mal schauen was ich nächste Woche schaffe.

**Comment by zero-24** [comment]
https://github.com/joomlagerman/joomla/compare/master...zero-24:550?expand=1

In fast allen fällen sprechen wir über die Website und nicht die einzelne HTML-Seite / Webseite
