### ISSUE TITLE
[3.9] Übersetzung "capabilities" 

### ISSUE THREAD

**Issue by f-hamel** [joomlagerman/joomla#553]
Die Übersetzung von "capabilities" unter Users->Privacy zu "Möglichkeiten" finde ich irritierend.

"capabilities" bedeutet ja eher etwas in RIchtung "Fähigkeiten" .
Also welche Daten könnten gesammelt werden.

Ich würde daher vlt . "Ressourcen".
Aus meiner Sicht ist es so verständlicher, dass es darum geht was für Daten gesammelt werden.

**Comment by tecpromotion** [comment]
@f-hamel Wir haben hier in der JUG Nürnberg grad überlegt ob man es nicht rein als **Hinweise** bezeichnet. Weil da kann künftig viel rein kommen. Die eigenen Erweiterungen die com_privacy unterstützen tauchen dort auf und beschreiben die Funktionalität.
Und wenn man drin ist, dann ist könnte oben dann Datenschutz: Hinweise stehen

**Comment by f-hamel** [comment]
@tecpromotion Hinweise fände ich auch gut

**Comment by webgras** [comment]
Ich würde eher Richtung "Umfang" oder "Reichweite" gehen.
"Hinweise" finde ich zu allgemein

**Comment by tecpromotion** [comment]
Was soll Umfang oder Reichweite im Menü bedeuten @webgras ?
Gerade Reichweite verstehe ich nicht in dem Kontext.

**Comment by f-hamel** [comment]
Also Umfang könnte ich auch nachvollziehen und würde in Hinblick auf Datenschutz als übergeordnete Ebene Sinn ergeben. Reichweite finde ich eher verwirrend.

Aktuell halte ich Hinweise für besser, da dies1
1. eine höhe Aufmerksamkeit generiert
2. Denn Sinn dass hier Informationen vorliegen die relevant für den Datenschutz sind wiederspiegeln

**Comment by webgras** [comment]
bei dem Punkt geht es doch generell darum, welche Erweiterungen welche Daten erfassen und an dieser Stelle anzeigen.
Ich überlege gerade, ob "Funktionsumfang" besser passt, aber auch nicht so richtig. oder "Datenschutzumfang" passt auch nicht so wirklich.
Also vielleicht eh nur "Umfang"

**Comment by tecpromotion** [comment]
Frage ob Umfang eine Erwartung weckt, dass dort Hinweise/Informationen ausgegeben werden, welche Erweiterung/Plugin sich dem Sammeln von Daten anschließt.

**Comment by webgras** [comment]
dann vielleicht "gesammelte Daten"?
Oder "Hinweis zu Daten"

**Comment by tecpromotion** [comment]
"Datenschutzhinweise"?

**Comment by tecpromotion** [comment]
@webgras "gesammelte Daten" würde ich als ... dort finde ich Daten verstehen. Bei der Seite geht es um reine Information bzw. Hinweise um beim Wort zu bleiben.
Daten werden hier keine angezeigt.

**Comment by webgras** [comment]
ja, "Datenschutzhinweise" finden wir gut

**Comment by tecpromotion** [comment]
Ich werde dann einen PR dazu machen, dass zieht sich ja doch an der einen oder anderen Stelle mehr durch. Vielen Dank für euer Feedback @webgras und @f-hamel

**Comment by f-hamel** [comment]
Gerne :wink:Datenschutzhimweise finde ich gut.
