### ISSUE TITLE
[3.9] Übersetzung von "Expiration" zu Ablauf

### ISSUE THREAD

**Issue by webgras** [joomlagerman/joomla#556]
Wir haben hier gerade alle diskutiert :)
Wie man "Ablauf" als Tab-Überschrift ersetzen kann.
Wenn ich "Ablauf" bei diesem Plugin lesen, dachte ich es kommt jetzt, die Reihenfolge wie ich es einrichte.

Wir waren jetzt bei "Verfallsdatum" , "Ablaufdatum", "Zustimmungsdauer"
Was findet Ihr?
![39plugin-titel](https://user-images.githubusercontent.com/10774704/45254674-7bd9fb80-b37c-11e8-8376-69c84cfc030f.jpg)

**Comment by tecpromotion** [comment]
Das Ablauf bei 360 sollte auf jeden Fall in Zustimmungsdauer umbenannt werden. Like.

Der Tab kann ja ggf. auch Ablaufoptionen oder so heißen. Es ist ja auch ein An/Aus dabei.

**Comment by tecpromotion** [comment]
@webgras was hälst du von Ablaufeinstellungen oder Ablauf-Optionen (Ablaufoptionen) als TAB-Name?
