### ISSUE TITLE
[3.9]Post-installation Messages - Open links in new tab #22061

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#577]
https://github.com/joomla/joomla-cms/issues/22061 - hmm sollten wir uns auch mal überlegen. Was denkt Ihr darüber?

**Comment by tecpromotion** [comment]
Alles was extern ist würde ich auch gerne in einem neuen TAB sehen.

**Comment by tecpromotion** [comment]
PR is still open
