### ISSUE TITLE
[3.8.12] "Abmeldeweiterleitungstyp": Falsche Information im Tooltip

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomlagerman/joomla#599]
### Wie kann der Fehler nachgestellt werden
Menü "Anmeldeformular", Tab "Optionen", Parameter "Abmeldeweiterleitungstyp": Im Tooltip steht "Anmeldeweiterleitungstyp".
![1](https://user-images.githubusercontent.com/8235763/46241531-89066b00-c3bb-11e8-8d3a-341175fef1c4.png)
### Das erwartete Ergebnis
Sollte "Abmeldeweiterleitungstyp" sein
### System information
- 3.8.12
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.0.28
- MySQLi 5.7.18-cll-lve
### Zusätzlichen Informationen
Bei den Parametern "Anmeldeweiterleitungstyp" und "Abmeldeweiterleitungstyp" die Reihenfolge der Beschreibung analog zum Formular umdrehen: Zuer "Menüeintrag", dann "Interne URL" beschreiben.

**Comment by tecpromotion** [comment]
Thanks @franz-wohlkoenig 
This is a bug in core imho.
I've made a PR https://github.com/joomla/joomla-cms/pull/22434

**Comment by franz-wohlkoenig** [comment]
danke @tecpromotion
