### ISSUE TITLE
[3.9]Typo in der Admin Module Beschreibung

### ISSUE THREAD

**Issue by blueforce** [joomlagerman/joomla#609]
### Wie kann der Fehler nachgestellt werden
1. Gehe ins BE und melde dich an
2. Navigiere zu Erweiterungen > Module
3. Stelle Filter von Site auf Administrator
4. Klicke Neu und erstelle ein neues Modul
5. die Liste erscheint

### Das erwartete Ergebnis
Der Wert beim letzten Moduleintrag der Liste in der Klammer wird korrekt angezeigt

### Das aktuelle Ergebnis
es hat noch ein Html-String, der nicht als symbol umgesetzt wird
![bildschirmfoto 2018-10-10 um 16 31 27](https://user-images.githubusercontent.com/1141234/46749750-b7871e80-ccb6-11e8-9c57-57c67c5159c4.png)

### System Information
getestet mit Version: 5d04b9b

**Comment by tecpromotion** [comment]
Typografisches Leerzeichen kam mit Commit 81041ea9ba77da8bc0dec3c5177c1e148583bee7

**Comment by zero-24** [comment]
Fixed. Danke @blueforce und @tecpromotion
