### ISSUE TITLE
Improve PLG_SYSTEM_ACTIONLOGS_XML_DESCRIPTION #23071

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#654]
### Zusätzlichen Informationen

https://github.com/joomla/joomla-cms/pull/23071/files

**Comment by zero-24** [comment]
hmm IMO sind wir da mit unserer Übersetzung schon besser gewesen als der Core:
https://github.com/joomlagerman/joomla/blob/master/administrator/language/de-DE/de-DE.plg_system_actionlogs.ini#L15

https://github.com/joomlagerman/joomla/blob/master/administrator/language/de-DE/de-DE.plg_system_actionlogs.sys.ini#L8

Ergo würde ich es in unserer Übersetzung so lassen wie wir das gerade haben? Was denkt Ihr @tecpromotion @coolwebcreations ?
