### ISSUE TITLE
Implementing com_contact frontend editing #22735

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#655]
### Zusätzlichen Informationen

https://github.com/joomla/joomla-cms/pull/22735

**Comment by zero-24** [comment]
Hier ist noch nicht entschieden wo diese Funktion implementiert wird daher würde ich diesen issue noch aufschieben und warten in welches Update diese eingespielt wird. Daher nehme ich auch erstmal den milestone wieder raus. Wenn die PR gemerged ist sehen wir weiter :)
