### ISSUE TITLE
'SUCCESS' not translated

### ISSUE THREAD

**Issue by James-Antrim** [joomlagerman/joomla#679]
### Wie kann der Fehler nachgestellt werden

In eins der 'de-DE.ini' Sprachdateien neben 'WARNING', 'MESSAGE' & co. nachschlagen. Die Konstante 'SUCCESS' fehlt komplett.

...oder aber ein Joomla! Nachricht vom Typ 'success' erzeugen lassen und den nicht übersetzten Typ ansehen.

### Das erwartete Ergebnis

"Erfolg"

### Das aktuelle Ergebnis

"success"

### System Information

Egal

### Zusätzlichen Informationen

Der Versuch die E-Mail Adressen von der J!German Seite einzusehen erzeugt ein Pop-Up mit einem 404 Fehler drin.

**Comment by coolwebcreations** [comment]
Bei welcher Aktion wurde die Nachricht angezeigt?

**Comment by James-Antrim** [comment]
JFactory::getApplication()->enqueueMessage('Irgendwas', 'success');
Erzeugt einen grünen Nachrichenbox mit der Kopfzeile 'success' wo eigentlich 'Erfolg' stehen müsste.
Deswegen auch der Hinweis wegen 'WARNING' und 'MESSAGE'.

**Comment by James-Antrim** [comment]
![image](https://user-images.githubusercontent.com/9820228/52342845-c7b9cb00-2a16-11e9-866c-08f7406f2a58.png)

**Comment by tecpromotion** [comment]
Hallo @James-Antrim,

wir übersetzen hier alle Strings aus dem Core.
Ich hab grad mal eine Search über das joomla-cms (INI) gemacht und exakt 30 Strings gefunden.
https://github.com/joomla/joomla-cms/search?l=INI&q=success

Wenn du das mit den deutschen Sprachdateien vergleichst, dann sind dies auch 30 Strings.
https://github.com/joomlagerman/joomla/search?l=INI&q=success

Meine Frage wäre nun, brauchst du das in einem eigenen Kontext?
Dann gibt es mehrere Möglichkeiten.

- eigenen Sprachoverride anlegen
- in deiner Entwicklung den String in deine .ini aufnehmen

Weil in Joomla gibt es diesen Fall so nicht, meines Wissens.
Heißt auch, wenn dein Beispiel echte Screenshost sind, dann hat der Entwickler das wohl vergessen.

**Comment by tecpromotion** [comment]
Und Danke für den Hinweis mit dem Impressum. Gleich mal ausgebessert.

**Comment by James-Antrim** [comment]
Jo. Sie haben Recht. Joomla selbst hat zwar die Klassen und alles drum und dran aber die Konstante nicht. Hatte natürlich auch im Core schauen können, aber da es die Klassen dazu gegeben hat war ich die Annahme sie würden dass konsequent durchziehen. Tut mir leid.

@Impressum: Gerne geschehen.

**Comment by tecpromotion** [comment]
Kein Problem. Vielen Dank für die Initiative.
