### ISSUE TITLE
Bessere Meldungsvorlage möglich? 

### ISSUE THREAD

**Issue by chmst** [joomlagerman/joomla#727]
Könnte man diese Vorlage für Sprachen ändern? Die Programmierer fagestellung passt ier nicht so gut
Vielleicht so: 
Was ist falsch - welche Sprachdatei- Wo wird es gezeigt - Wie könnte es richtig heissen? 
Sprachkey falls bekannt

Das mit erwarteten Ergebnissen, Reproduzierbarkeit, Systeminformationen ist hier nicht relevant.

**Comment by tecpromotion** [comment]
@zero-24 und @coolwebcreations was meint ihr?
Eine Optimierung wäre grundsätzlich ja machbar.
Man kann das durchaus mehr auf Sprachen anpassen. Systeminformationen sind dennoch nicht unrelevant, da wir dann ja 3.x und 4.x hier betreuen eine ganze Zeit lang.
Eine mögliche Idee wäre es, den 4.0 Branch nach oder vor beta in ein eigenes repo zu ziehen bzw. den jetzigen master bei Release von 4 in ein eigenes Repo. Da hängt aber sehr viel mehr dran, Releases etc. Das sollten wir in Ruhe mal besprechen.

**Comment by zero-24** [comment]
Siehe: https://github.com/joomlagerman/joomla/pull/729
