### ISSUE TITLE
[4.0] Hauptbeitrag oder Haupteintrag?

### ISSUE THREAD

**Issue by chmst** [joomlagerman/joomla#728]
### Wie kann der Fehler nachgestellt werden
Im Hauptmenü

### Das erwartete Ergebnis
?

### Das aktuelle Ergebnis
Es heisst "Beiträge" und "Haupteinträge" - gewollt oder Zufall?

**Comment by tecpromotion** [comment]
Hi @chmst 
Frage ist ob wir das wirklich für 3.x noch machen sollten. Die komplette Literatur wäre halt dann nicht mehr korrekt.
Wenn das OK ist, dann finde ich die Anpassung für 4.0 super. Sind aber einige Stellen!
Quicksearch ergab > 20 Strings

**Comment by chmst** [comment]
Nur für V4.
Ich dachte das ist jetzt nur für v4, also sorry wenn ich da an der falschen Stelle bin. Vielleicht sollte man [4.0] davor schreiben?

**Comment by tecpromotion** [comment]
Hi @chmst 
Dies ist das allgemeine Repo, wir haben hier verschiedene Branches.
Ich habe den Issue mal mit 4.0 ergänzt.

Da wir in der alpha1 nur das Frontend haben, würde ich das dann auf den Milestone beta1 schieben.

**Comment by tecpromotion** [comment]
@chmst Ich hab gleich mal zwei neue Labels angelegt. Dann ist das noch mal ein Pluspunkt. **Danke** für die Idee.

**Comment by tecpromotion** [comment]
Siehe PR #730
