### ISSUE TITLE
Global Options: Different Tooltips on 3 Datetypes (Update en-GB.ini) #25556

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#742]
https://github.com/joomla/joomla-cms/pull/25556

**Comment by tecpromotion** [comment]
Würde bei uns derzeit bedeuten,
dass die Erklärung wegfällt: 

>  Dies ist eine allgemeine Einstellung, kann aber in den Kategorien, Menüs und Beiträgen individuell angepasst werden.

Drin lassen oder raus damit? @joomlagerman/reviewer

**Comment by zero-24** [comment]
IMO drin lassen, ich persönlich halte das für eine wichtige Information.

**Comment by tecpromotion** [comment]
> IMO drin lassen, ich persönlich halte das für eine wichtige Information.

Ist halt null einheitlich in den ganzen Strings aber bin auch für drin lassen.
