### ISSUE TITLE
Simplify description language #25844

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#746]
https://github.com/joomla/joomla-cms/pull/25844

### Was soll verbessert / korrigiert werden

Vereinfachung der Sprache

### Zusätzlichen Informationen

Wait for merge

**Comment by tecpromotion** [comment]
@joomlagerman/reviewer 

Was meint ihr? Vereinfachung find ich grundsätzlich super.

**Comment by zero-24** [comment]
nicht immer ist Vereinfachung machbar aber hier stimme ich zu 👍
