### ISSUE TITLE
Verbesserungsvorschlag, Tab Umbenennung "Gemeinsam"

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#762]
Der Reiter "Gemeinsam" ist etwas holprig übersetzt.
Ich würde "Generelle Einstellungen" oder "Allgemeine Einstellungen" vorschlagen.

<img width="1178" alt="grafik" src="https://user-images.githubusercontent.com/828371/64263246-9dd67180-cf2f-11e9-8d02-328ba625f8bb.png">

**Comment by tecpromotion** [comment]
Base: https://github.com/joomla/joomla-cms/blob/16eb98e058dbd8b9e6374a22ad6ace0d8bfc7db0/administrator/language/en-GB/en-GB.com_content.ini#L183

**Comment by tecpromotion** [comment]
Mit dem nachfolgenden Info-Block: 
>  Die gemeinsamen Einstellungen gelten für die Beitragslistenansichten, die Blogansichten und die Haupteinträge, wenn sie nicht in einem eigenen Menülink überschrieben werden.
finde ich es eigentlich passend.

Im englischen ist es **Shared**, würde man dann mit geteilt übersetzen was nicht passend wäre.
Es in Generell oder Allgemein zu ändern, dafür ist die Position des Tabs unglücklich.

Weitere Meinungen? @joomlagerman/reviewer @astridx @webgras um ein paar Contributors zu nennen.

**Comment by astridx** [comment]
Die Übersetzung `Gemeinsam` finde ich auch nicht glücklich.

Ich würde `Interaktion` mit `Interaktion` oder `Einbindung` übersetzen: https://dict.leo.org/englisch-deutsch/integration.

Wobei ich mit dem Begriff Interaktion ohnehin nicht ganz froh bin. Für mich stehen die Optionen nicht für `eine Integration der Komponente in das CMS Joomla`, sondern eher für `eine Interaktion einer Komponente mit anderen Komponenten`. Aber das ist ein anderes Thema.

**Comment by astridx** [comment]
~~Die Übersetzung Gemeinsam finde ich auch nicht glücklich.~~

~~Ich würde `Interaktion` mit `Interaktion` oder `Einbindung` übersetzen: https://dict.leo.org/englisch-deutsch/integration.~~

~~Wobei ich mit dem Begriff ohnehin nicht ganz froh bin. Für mich stehen die Optionen nicht für `eine Integration der Komponente in das CMS Joomla`, sondern eher für `eine Interaktion einer Komponente mit anderen Komponenten`. Aber das ist ein anderes Thema.~~

Ups, zuschnell gelesen.

**Comment by zero-24** [comment]
Ja bin bei @astridx `Gemeinsam genutzte Optionen` nur das ist zu lang.

Vielleicht `Übergreifende`?

**Comment by coolcat-creations** [comment]
„Gemeinsam genutzt“ ist das zu lang?


Von meinem iPhone gesendet

**Comment by webgras** [comment]
Oder "Allgemein" - weil es sind ja im Prinzip Basis-Einstellungen, aber das hat wenig mit "Shared" zu tun. Ist echt schwierig.
"Gemeinsam genutzt" - finde ich von der Länge noch ok.

**Comment by tecpromotion** [comment]
Problem welches ich mit Allgemein hab.
Als user erwarte ich Allgemein vorne. Es steht aber relativ weit hinten. Das würde mich mehr verwirren und wundern was die da machen.

**Comment by tecpromotion** [comment]
> „Gemeinsam genutzt“ ist das zu lang?

Mach dafür mal einen PR, dann können wir das alle testen und ggf. haben wir dann auch schnell eine Lösung.

**Comment by tecpromotion** [comment]
https://github.com/joomlagerman/joomla/pull/764
