### ISSUE TITLE
Verbesserungsvorschlag "Zugriffe" vs. "Seitenaufrufe"

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#763]
In den Parameters werden die Einstellungen 
<img width="404" alt="grafik" src="https://user-images.githubusercontent.com/828371/64263348-cb231f80-cf2f-11e9-8d22-136db00c7195.png"> Seitenaufrufe genannt.

Im Layout jedoch mit Zugriffen belabelt:
<img width="458" alt="grafik" src="https://user-images.githubusercontent.com/828371/64263554-189f8c80-cf30-11e9-8564-9cd4a194a338.png">

Für einen nicht versierten User ist das nicht auf Anhieb logisch dass die Einstellung mit dieser Anzeige verbunden ist. Entweder muss der Parameter Zugriffe heißen oder das Label in der Liste Seitenaufrufe.

**Comment by tecpromotion** [comment]
Magst du selber den PR schreiben @coolcat-creations ?

**Comment by coolcat-creations** [comment]
Könnte ich, welches Wording soll es denn werden? :-)

Von meinem iPhone gesendet

**Comment by tecpromotion** [comment]
Von der reinen Nutzung bisher wäre Zugriffe deutlich weiter vorne.
Seitenaufrufe nutzen wir tatsächlich da. Im englischen sind es die Hits, denke Zugriffe passt da gut.

**Comment by tecpromotion** [comment]
https://github.com/joomlagerman/joomla/pull/765
