### ISSUE TITLE
[4.0] Menüpunkte vs. Menüeinträge

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#767]
### Was soll verbessert / korrigiert werden
Wie wäre es wenn wir das gestoche Word "Menüeinträge" durch das umgangssprachliche Wort Menüpunkte ersetzen?  Und resp. alles was damit zu tun hat. z.B. Menüeintragstyp -> Menüpunkttyp. Denke das ist für Einsteiger einfacher zu verstehen.

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
Im Backend

**Comment by zero-24** [comment]
hmm wären diese ganzen stellen hier: https://github.com/joomlagerman/joomla/search?utf8=%E2%9C%93&q=Men%C3%BCeintrag&type=

was denkt ihr @joomlagerman/reviewer ?

**Comment by tecpromotion** [comment]
@coolcat-creations Ich finde das grundsätzlich eine ganz gute Idee, will das aber sehr ungern für 3.x umsetzen. Da ist doch sehr viel Literatur und Doku Allgemein im Netz, u.a. JDOCS etc. die sich auf dieses Wording beziehen.
Ich habe dies daher vorerst auf J4 als Label gesetzt.

**Comment by coolcat-creations** [comment]
Ja das wäre klasse - soll ich dann einen PR auf den 4.0 branch machen?

**Comment by coolcat-creations** [comment]
Notiz an mich selbst: Bei "Menüs: Einträge" dann müsste es wahrscheinlich "Menüs: Menüpunkte" heißen.

**Comment by tecpromotion** [comment]
Nicht vor beta Status bitte, es gibt den Branch aber den werden wir ab beta noch mal umbauen müssen.
Und dann sollten wir ggf. noch mal eine Abfrage machen, es muss dann immer noch sämtliche Literatur angepasst werden.

**Comment by tecpromotion** [comment]
> Notiz an mich selbst: Bei "Menüs: Einträge" dann müsste es wahrscheinlich "Menüs: Menüpunkte" heißen.

Eintrag ist halt schön allgemein, evtl. passt Menüpunkt nicht in jedem Anwendungsfall? Klar sind es im Menü irgendwo Menüpunkte... evtl. müssen wir das bei PBF am 19.10. mal gemeinsam durchtesten.

**Comment by tecpromotion** [comment]
@coolcat-creations @zero-24 Bin grad wieder drüber gestolpert... Was wollen wir machen?

**Comment by zero-24** [comment]
> Eintrag ist halt schön allgemein, evtl. passt Menüpunkt nicht in jedem Anwendungsfall?

hmm wenn jemand einen anderen Anwendungsfall hat kann er einen Sprachoverride machen. Also das wäre für mich kein blocker.

Ich würde sagen lass es mal als Umfrage einstellen dann entscheiden wir drei das das nicht alleine und bekommen ggf. noch weiteres Feedback oder Ideen? @tecpromotion ?

**Comment by tecpromotion** [comment]
@zero-24 53/6 für Menüpunkt und die Varianten.

@coolcat-creations magst du einen PR machen oder soll ich?

**Comment by crimle** [comment]
Zwar finde ich auch, dass das Wort «Menüeintragstyp» nicht gerade ein schönes Wort ist. Aber ist «Menüpunkttyp» wirklich besser? Ich finde: nein! «Menüeintrag» beschreibt besser was gemeint ist. «Menüpunkt» ist sehr umgangssprachlich aber auch ungenau. Bei «Menüpunkt» höre bzw. lese ich «Punkt» und unter einem Punkt verstehe ich das da «.»

**Comment by tecpromotion** [comment]
Bei Interesse gerne einen PR machen @coolcat-creations ... sonst würde ich das vorerst so belassen.
