### ISSUE TITLE
[4.0] User sperren / freigeben

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#768]
<img width="415" alt="grafik" src="https://user-images.githubusercontent.com/828371/64532968-d5b82d00-d312-11e9-9a8c-77484290384a.png">

Ich finde das bisschen ein Kuddelmuddel mit Sperren und Freigeben, man erkennt da als User nicht dass diese zwei Funktionen wirklich zusammengehören.

Sperren und Entsperren wäre gut, aber Entsperrt als Überschrift klingt nicht prickelnd.
Habt ihr eine Idee wie man das verbessern kann?

**Comment by zero-24** [comment]
hmm im forum wird: `Sperren` vs `Sperrung aufheben` benutzt ist das klarer?

**Comment by coolcat-creations** [comment]
Nein das meinte ich nicht... ich meinte dass man das Pendant zu freigeben weder vom Icon noch vor Wort her erkennen kann... ?

**Comment by zero-24** [comment]
Bezüglich Icons was hältst du von den Icons `lock` und `unlock`
https://docs.joomla.org/J3.x:Joomla_Standard_Icomoon_Fonts/de

Bezüglich Text war daher mein Vorschlag die beiden auf `Sperren` und `Sperrung aufheben` zu ändern damit die besser passen oder hab ich dich falsch verstanden?

**Comment by coolcat-creations** [comment]
Aber dann würde statt Freigegeben in der Tabelle stehen "Entsperrte" ... das klingt ja doof... deswegen weiß ich nicht wie man es formulieren könnte Bzgl icons müssten wir ins joomla-cms oder? Das Schloss steht ja in J schon für eingecheckte Elemente... alles nicht so easy.

**Comment by zero-24** [comment]
> Bzgl icons müssten wir ins joomla-cms oder? 

Ja.

> Das Schloss steht ja in J schon für eingecheckte Elemente... alles nicht so easy.

Und fun fact auch einchecken heist "Freigeben" im Deutschen :D 

> Aber dann würde statt Freigegeben in der Tabelle stehen "Entsperrte" ... das klingt ja doof... deswegen weiß ich nicht wie man es formulieren könnte

Die Forensoftware benutzt `Zustand` auch nicht wirklich optimal.

**Comment by chmst** [comment]
Nach einigem Gegrübel und Konsultation von Übersetzern: 
Freigegeben ist tatsächlich das neutralste Wort und Gegenteil von gesperrt.

Zugelassen wäre auch korrekt ist aber ein hässliches wort. Befugt / Unbefugt sagt man seit 100 Jahren nicht mehr.

**Comment by max123kl** [comment]
Wie wäre es mit "Freigeschaltet"?
Im Core wird der Spaltenkopf mit "Enabled" bezeichnet (der Gegensatz "Disabled" wird hier nicht gebraucht).

Falls das Begriffspaar doch gebraucht würde, dann könnte man auf "Aktiv/Inaktiv" ausweichen.

**Comment by chmst** [comment]
Dummerweise braucht das Wort so viel Platz in der oberen Zeile.  Am besten wär so was wie "Ok!" das würde die Optik der Tabelle enorm verbessern

**Comment by tecpromotion** [comment]
Ist das noch so aktuell @coolcat-creations ?
Danke.
