### ISSUE TITLE
"Sortieren nach Template"

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#769]
<img width="1182" alt="grafik" src="https://user-images.githubusercontent.com/828371/64694777-cc59cc80-d49a-11e9-95b9-e3c339d24a75.png">

Wie wäre es mit "Template Name" oder Template Titel" als Überschrift und zur Sortierung?

**Comment by tecpromotion** [comment]
https://github.com/joomlagerman/joomla/blob/643bff8b31a37a79383772990f24c6b65c1ddce6/administrator/language/de-DE/de-DE.com_templates.ini#L156 und folgende.

**Comment by tecpromotion** [comment]
Allerdings bekommen wir eine Inkonsistenz dadurch.
Die Spalten haben Namen, diese Namen werden verwendet und dann jeweils aufsteigend/absteigend.
Die Spalte in Template Name zu ändern ist aber nicht vorgesehen.
Daher lassen wir das vorerst mal auf Template aufsteigend/absteigend.
