### ISSUE TITLE
Erweiterungsverzeichnis vs. Webkatalog

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#770]
Einmal heißt es "Webkatalog" und einmal "Erweiterungsverzeichnis"

<img width="477" alt="grafik" src="https://user-images.githubusercontent.com/828371/64696506-dbdb1480-d49e-11e9-84ad-b904a55b8055.png">

<img width="1021" alt="grafik" src="https://user-images.githubusercontent.com/828371/64696549-f1503e80-d49e-11e9-9b8c-0d71bb61ab39.png">

**Comment by tecpromotion** [comment]
Würde hier auf **Webkatalog** gehen.

**Comment by tecpromotion** [comment]
Die beiden Stellen austauschen: https://github.com/joomlagerman/joomla/search?q=Erweiterungsverzeichnis&unscoped_q=Erweiterungsverzeichnis

**Comment by coolcat-creations** [comment]
Danke
