### ISSUE TITLE
Browsertitel / Seitentitel 

### ISSUE THREAD

**Issue by coolcat-creations** [joomlagerman/joomla#772]
Im Beitrag heißt es  **Browser Seitentitel** 
<img width="497" alt="grafik" src="https://user-images.githubusercontent.com/828371/64713805-d3460680-d4bd-11e9-923d-16f09a2ef03e.png">

Im Menüeintrag heißt es: **Seitentitel im Browser**
<img width="502" alt="grafik" src="https://user-images.githubusercontent.com/828371/64714041-3899f780-d4be-11e9-9fb8-9215d1484a3c.png">

In der Konfiguration wird es nur Titel benannt:
<img width="450" alt="grafik" src="https://user-images.githubusercontent.com/828371/64714360-cbd32d00-d4be-11e9-8f8c-80615dbb9445.png">

Am besten verstehen es aber Leute m.E. nach wenn man Browser Titel sagt.
Meinungen?

**Comment by tecpromotion** [comment]
Das nur **Titel** in der Konfiguration passt nicht rein.
Die anderen beiden sind ja gleichwertig -> kann man gleichziehen mMn. zu **Browser Seitentitel**

Konfiguration evtl. **Seitentitel auch im Browser** ?

**Comment by coolcat-creations** [comment]
Mein Vorschlag wäre
- Browser Titel
- Browser Titel
- Seitenname im Browser Titel

**Comment by tecpromotion** [comment]
@coolcat-creations nenn die PRs gerne immer wie die Issues. Danke für deine Ideen.

**Comment by tecpromotion** [comment]
Ich habe gerade mal etwas gesucht und wenn, sollte es Browsertitel als ein Wort werden.
Allerdings wird in der Literatur (Google Recherche) meist vom Seitentitel gesprochen.
Das Wort Seitentitel hat mehr als das zehnfache an Suchergebnissen in Google.
