### ISSUE TITLE
[4.0] Anregungen für AT Version

### ISSUE THREAD

**Issue by websquirrel** [joomlagerman/joomla#782]
### Was soll verbessert / korrigiert werden
In Österreich heißt es nicht die E-Mail, sondern das E-Mail. Wenn schon eine AT-Version, dann eine, die auch AT ist ;)

### Wo wird der Sprachstring angezeigt (Frontend/Backend)
von der Konfiguration, über die Kontakte bis hin zu den E-Mails, die das System verschickt, etwa im Falle einer Joomla!-Aktualisierung. Da müsste der erste Satz so beginnen: "Dieses E-Mail ..."

### Was wäre eine bessere Übersetzung / Bezeichnung
die E-Mail -> das E-Mail
diese E-Mail -> dieses E-Mail
eine E-Mail -> ein E-Mail
usw

### Joomla Version & Version der deutschen Sprachdatei
alle

**Comment by tecpromotion** [comment]
Ich hab das mal auf J4 getagged.

**Comment by tecpromotion** [comment]
Meinungen dazu @webgras @HLeithner @webfeuerflo

**Comment by HLeithner** [comment]
Ghupft wie Ghatscht, Im österreichischen werden Englische Lehnwörter immer (Ausnahmen bestätigen die Regel) mit dem neutralem Artikel eingedeutscht. Im Bundesdeutschen wird der Artikel der über verwendet in dem Fall (Mail -> die Post). In Österreich kannst du die und das E-Mail sagen. Ich persönlich bin mag die Ableitung des Artikels der Übersetzung mehr (da wir sonst jedes eingedeutschte Wort mit "das" schreiben müssten) des wegen bin ich für die Beibehaltung von "die" als Artikel.

**Comment by tecpromotion** [comment]
Ok, das wäre ja ne Menge Anpassungen die wir hier berücksichtigen müssten.
Close?

**Comment by webfeuerflo** [comment]
Also wenn es schon eine eigene Österreichische Sprachversion gibt, müsste es wohl "das Mail" heißen, die Mail sagt hier keiner, finde ich

**Comment by tecpromotion** [comment]
Aber E-Mail ist jetzt ja nur EIN Beispiel, es gibt doch bestimmt sehr viele dieser Fälle und das wäre eine Herausforderung.

**Comment by HLeithner** [comment]
Ich kenne kaum jemanden der das E-Mail sagt ;-)

Aber ja ich habe es oben beschrieben wie der Artikel gebildet wird.

**Comment by websquirrel** [comment]
Das liegt daran, dass die meisten Sprachversionen von Software, Büchern, Schulungsunterlagen und Vorträgen nur den Deutschen Sprachgebrauch kennen und die Österreicher sich hier zwangsläufig anpassen. Sind die Österreicher unter sich, sagen sie das eMail, jedenfalls die älteren. Die Jugend ist schon von den Deutschen Sozialen Medien, TV-Sendern und Filmen auf „Bundesdeutsche“ Sprache getrimmt ;)

Von meinem iPad gesendet

**Comment by HLeithner** [comment]
@websquirrel so alt bin ich nicht ;-)

egal von mir aus kann auch eine komplette österreichische version gemacht werden allerdings nur wenn es genügend commitment dazu gibt und aller texte durchgegangen werden.

Nur ein paar Artikel zu ändern ist den aufwand nicht wert in meinen augen

**Comment by tecpromotion** [comment]
Ab RC6 haben wir nun Jänner in der DE-AT. 

Ich schließe diesen issue jetzt. 
Wie Harald schon sagte, bei Commitment gerne offen für mehr AT aber ich schaffe es zeitlich nicht, zudem kann ich es auch nicht.
