### ISSUE TITLE
[4.0] Installation

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#792]
1. Fork this repo
2. Check local file diff with joomla/joomla-cms with diffmerge or https://www.diffchecker.com/
3. Rename file
4. Commit file with a reference to this issue

**Files:**
- [x] joomla.ini
- [x] langmetadata.xml

**Comment by tecpromotion** [comment]
@zero-24 is working on this issue

**Comment by zero-24** [comment]
see #800
