### ISSUE TITLE
[3.10] Be able to use unique language strings for the rules field #13523

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#794]
Here: https://github.com/joomla/joomla-cms/pull/13523/files the new alternative string is implemented:

JLIB_RULES_SETTING_NOTES vs. JLIB_RULES_SETTING_NOTES_COM_BANNERS

I don't see a benefit for the change now as the current string is still used and we don't use different strings per extension. When this changes we can to use the alternate string.

**Comment by tecpromotion** [comment]
tbd later

**Comment by tecpromotion** [comment]
@joomlagerman/reviewer
Decision: We go with the alternative strings and adjust them according to the official repo.

**Comment by tecpromotion** [comment]
was used at the points where it makes sense, alternatively tighten again and again.
