### ISSUE TITLE
[4.0] Language generally

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#795]
1. Fork this repo
2. Check local file diff with joomla/joomla-cms with diffmerge or https://www.diffchecker.com/
3. Rename file
4. Commit file with a reference to this issue

**Files:**
- [x] de-DE.files_joomla.sys.ini
- [x] de-DE.finder_cli.ini
- [x] de-DE.lib_joomla.ini
- [x] de-DE.lib_joomla.sys.ini
- [x] de-DE.lib_phpass.sys.ini
- [x] de-DE.lib_simplepie.sys.ini
- [x] de-DE.localise.php
- [x] install.xml
- [x] joomla.ini
- [x] langmetadata.xml

**Comment by tecpromotion** [comment]
@chmst is working on this issue

**Comment by zero-24** [comment]
see: #813

**Comment by zero-24** [comment]
joomla.ini: https://github.com/joomlagerman/joomla/pull/1248/files
