### ISSUE TITLE
[4.0] language components

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#796]
1. Fork this repo
2. Check local file diff with joomla/joomla-cms with diffmerge or https://www.diffchecker.com/
3. Rename file
4. Commit file with a reference to this issue

**Files:**
- [ ] de-DE.com_ajax.ini
- [ ] de-DE.com_config.ini
- [ ] de-DE.com_contact.ini
- [ ] de-DE.com_content.ini
- [ ] de-DE.com_finder.commonwords.txt
- [ ] de-DE.com_mailto.ini
- [ ] de-DE.com_media.ini
- [ ] de-DE.com_messages.ini
- [ ] de-DE.com_newsfeeds.ini
- [ ] de-DE.com_privacy.ini
- [ ] de-DE.com_tags.ini
- [ ] de-DE.com_users.ini
- [ ] de-DE.com_wrapper.ini

**Comment by zero-24** [comment]
see: https://github.com/joomlagerman/joomla/pull/809
