### ISSUE TITLE
[4.0] language modules

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#798]
1. Fork this repo
2. Check local file diff with joomla/joomla-cms with diffmerge or https://www.diffchecker.com/
3. Rename file
4. Commit file with a reference to this issue

**Files:**
- [x] de-DE.mod_articles_archive.ini
- [x] de-DE.mod_articles_archive.sys.ini
- [x] de-DE.mod_articles_categories.ini
- [x] de-DE.mod_articles_categories.sys.ini
- [x] de-DE.mod_articles_category.ini
- [x] de-DE.mod_articles_category.sys.ini
- [x] de-DE.mod_articles_latest.ini
- [x] de-DE.mod_articles_latest.sys.ini
- [x] de-DE.mod_articles_news.ini
- [x] de-DE.mod_articles_news.sys.ini
- [x] de-DE.mod_articles_popular.ini
- [x] de-DE.mod_articles_popular.sys.ini
- [x] de-DE.mod_banners.ini
- [x] de-DE.mod_banners.sys.ini
- [x] de-DE.mod_breadcrumbs.ini
- [x] de-DE.mod_breadcrumbs.sys.ini
- [x] de-DE.mod_custom.ini
- [x] de-DE.mod_custom.sys.ini
- [x] de-DE.mod_feed.ini
- [x] de-DE.mod_feed.sys.ini
- [x] de-DE.mod_finder.ini
- [x] de-DE.mod_finder.sys.ini
- [x] de-DE.mod_footer.ini
- [x] de-DE.mod_footer.sys.ini
- [x] de-DE.mod_languages.ini
- [x] de-DE.mod_languages.sys.ini
- [x] de-DE.mod_login.ini
- [x] de-DE.mod_login.sys.ini
- [x] de-DE.mod_menu.ini
- [x] de-DE.mod_menu.sys.ini
- [x] de-DE.mod_random_image.ini
- [x] de-DE.mod_random_image.sys.ini
- [x] de-DE.mod_related_items.ini
- [x] de-DE.mod_related_items.sys.ini
- [x] de-DE.mod_stats.ini
- [x] de-DE.mod_stats.sys.ini
- [x] de-DE.mod_syndicate.ini
- [x] de-DE.mod_syndicate.sys.ini
- [x] de-DE.mod_tags_popular.ini
- [x] de-DE.mod_tags_popular.sys.ini
- [x] de-DE.mod_tags_similar.ini
- [x] de-DE.mod_tags_similar.sys.ini
- [x] de-DE.mod_users_latest.ini
- [x] de-DE.mod_users_latest.sys.ini
- [x] de-DE.mod_whosonline.ini
- [x] de-DE.mod_whosonline.sys.ini
- [x] de-DE.mod_wrapper.ini
- [x] de-DE.mod_wrapper.sys.ini

**Comment by zero-24** [comment]
see: https://github.com/joomlagerman/joomla/pull/803
