### ISSUE TITLE
[4.0] administrator/language modules

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#806]
1. Fork this repo
2. Check local file diff with joomla/joomla-cms with diffmerge or https://www.diffchecker.com/
3. Rename file
4. Commit file with a reference to this issue

**NEW Files:**

- [x] mod_loginsupport.ini
- [x] mod_loginsupport.sys.ini
- [x] mod_messages.ini
- [x] mod_messages.sys.ini
- [x] mod_post_installation_messages.ini
- [x] mod_post_installation_messages.sys.ini
- [x] mod_privacy_status.ini
- [x] mod_privacy_status.sys.ini
- [x] mod_user.ini
- [x] mod_user.sys.ini

**CHANGE Files:**

- [x] de-DE.mod_custom.ini
- [x] de-DE.mod_custom.sys.ini
- [x] de-DE.mod_feed.ini
- [x] de-DE.mod_feed.sys.ini
- [x] de-DE.mod_latest.ini
- [x] de-DE.mod_latest.sys.ini
- [x] de-DE.mod_latestactions.ini
- [x] de-DE.mod_latestactions.sys.ini
- [x] de-DE.mod_logged.ini
- [x] de-DE.mod_logged.sys.ini
- [x] de-DE.mod_login.ini
- [x] de-DE.mod_login.sys.ini
- [x] de-DE.mod_menu.ini
- [x] de-DE.mod_menu.sys.ini
- [x] de-DE.mod_multilangstatus.ini
- [x] de-DE.mod_multilangstatus.sys.ini
- [x] de-DE.mod_popular.ini
- [x] de-DE.mod_popular.sys.ini
- [x] de-DE.mod_privacy_dashboard.ini
- [x] de-DE.mod_privacy_dashboard.sys.ini
- [x] de-DE.mod_quickicon.ini
- [x] de-DE.mod_quickicon.sys.ini
- [x] de-DE.mod_sampledata.ini
- [x] de-DE.mod_sampledata.sys.ini
- [x] de-DE.mod_stats_admin.ini
- [x] de-DE.mod_stats_admin.sys.ini
- [x] de-DE.mod_submenu.ini
- [x] de-DE.mod_submenu.sys.ini
- [x] de-DE.mod_title.ini
- [x] de-DE.mod_title.sys.ini
- [x] de-DE.mod_toolbar.ini
- [x] de-DE.mod_toolbar.sys.ini
- [x] de-DE.mod_version.ini
- [x] de-DE.mod_version.sys.ini

**DELETE Files:**
- [x] de-DE.mod_status.ini
- [x] de-DE.mod_status.sys.ini

**Comment by zero-24** [comment]
see: #814
