### ISSUE TITLE
[4.0] administrator/language plugins

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#807]
1. Fork this repo
2. Check local file diff with joomla/joomla-cms with diffmerge or https://www.diffchecker.com/
3. Rename file
4. Commit file with a reference to this issue

**NEW Files:**

- [x] plg_behaviour_taggable.ini
- [x] plg_behaviour_taggable.sys.ini
- [x] plg_behaviour_versionable.ini
- [x] plg_behaviour_versionable.sys.ini
- [x] plg_extension_finder.ini
- [x] plg_extension_finder.sys.ini
- [x] plg_extension_namespacemap.ini
- [x] plg_extension_namespacemap.sys.ini
- [x] plg_fields_subfields.ini
- [x] plg_fields_subfields.sys.ini
- [x] plg_filesystem_local.ini
- [x] plg_filesystem_local.ini
- [x] plg_installer_override.ini
- [x] plg_installer_override.sys.ini
- [x] plg_media-action_crop.ini
- [x] plg_media-action_crop.sys.ini
- [x] plg_media-action_resize.ini
- [x] plg_media-action_resize.sys.ini
- [x] plg_media-action_rotate.ini
- [x] plg_media-action_rotate.sys.ini
- [x] plg_quickicon_downloadkey.ini
- [x] plg_quickicon_downloadkey.sys.ini
- [x] plg_quickicon_overridecheck.ini
- [x] plg_quickicon_overridecheck.sys.ini
- [x] plg_sampledata_multilang.ini
- [x] plg_sampledata_multilang.sys.ini
- [x] plg_system_httpheaders.ini
- [x] plg_system_httpheaders.sys.ini
- [x] plg_system_skipto.ini
- [x] plg_system_skipto.sys.ini
- [x] plg_webservices_banners.ini
- [x] plg_webservices_banners.sys.ini
- [x] plg_webservices_config.ini
- [x] plg_webservices_config.sys.ini
- [x] plg_webservices_contact.ini
- [x] plg_webservices_contact.sys.ini
- [x] plg_webservices_content.ini
- [x] plg_webservices_content.sys.ini
- [x] plg_webservices_languages.ini
- [x] plg_webservices_languages.sys.ini
- [x] plg_webservices_menus.ini
- [x] plg_webservices_menus.sys.ini
- [x] plg_webservices_messages.ini
- [x] plg_webservices_messages.sys.ini
- [x] plg_webservices_modules.ini
- [x] plg_webservices_modules.sys.ini
- [x] plg_webservices_newsfeeds.ini
- [x] plg_webservices_newsfeeds.sys.ini
- [x] plg_webservices_plugins.ini
- [x] plg_webservices_plugins.sys.ini
- [x] plg_webservices_privacy.ini
- [x] plg_webservices_privacy.sys.ini
- [x] plg_webservices_redirect.ini
- [x] plg_webservices_redirect.sys.ini
- [x] plg_webservices_tags.ini
- [x] plg_webservices_tags.sys.ini
- [x] plg_webservices_templates.ini
- [x] plg_webservices_templates.sys.ini
- [x] plg_webservices_users.ini
- [x] plg_webservices_users.sys.ini

**CHANGE Files:**

- [x] de-DE.plg_actionlog_joomla.ini
- [x] de-DE.plg_actionlog_joomla.sys.ini
- [x] de-DE.plg_authentication_cookie.ini
- [x] de-DE.plg_authentication_cookie.sys.ini
- [x] de-DE.plg_authentication_joomla.ini
- [x] de-DE.plg_authentication_joomla.sys.ini
- [x] de-DE.plg_authentication_ldap.ini
- [x] de-DE.plg_authentication_ldap.sys.ini
- [x] de-DE.plg_captcha_recaptcha.ini
- [x] de-DE.plg_captcha_recaptcha.sys.ini
- [x] de-DE.plg_captcha_recaptcha_invisible.ini
- [x] de-DE.plg_captcha_recaptcha_invisible.sys.ini
- [x] de-DE.plg_content_confirmconsent.ini
- [x] de-DE.plg_content_confirmconsent.sys.ini
- [x] de-DE.plg_content_contact.ini
- [x] de-DE.plg_content_contact.sys.ini
- [x] de-DE.plg_content_emailcloak.ini
- [x] de-DE.plg_content_emailcloak.sys.ini
- [x] de-DE.plg_content_fields.ini
- [x] de-DE.plg_content_fields.sys.ini
- [x] de-DE.plg_content_finder.ini
- [x] de-DE.plg_content_finder.sys.ini
- [x] de-DE.plg_content_joomla.ini
- [x] de-DE.plg_content_joomla.sys.ini
- [x] de-DE.plg_content_loadmodule.ini
- [x] de-DE.plg_content_loadmodule.sys.ini
- [x] de-DE.plg_content_pagebreak.ini
- [x] de-DE.plg_content_pagebreak.sys.ini
- [x] de-DE.plg_content_pagenavigation.ini
- [x] de-DE.plg_content_pagenavigation.sys.ini
- [x] de-DE.plg_content_vote.ini
- [x] de-DE.plg_content_vote.sys.ini
- [x] de-DE.plg_editors-xtd_article.ini
- [x] de-DE.plg_editors-xtd_article.sys.ini
- [x] de-DE.plg_editors-xtd_contact.ini
- [x] de-DE.plg_editors-xtd_contact.sys.ini
- [x] de-DE.plg_editors-xtd_fields.ini
- [x] de-DE.plg_editors-xtd_fields.sys.ini
- [x] de-DE.plg_editors-xtd_image.ini
- [x] de-DE.plg_editors-xtd_image.sys.ini
- [x] de-DE.plg_editors-xtd_menu.ini
- [x] de-DE.plg_editors-xtd_menu.sys.ini
- [x] de-DE.plg_editors-xtd_module.ini
- [x] de-DE.plg_editors-xtd_module.sys.ini
- [x] de-DE.plg_editors-xtd_pagebreak.ini
- [x] de-DE.plg_editors-xtd_pagebreak.sys.ini
- [x] de-DE.plg_editors-xtd_readmore.ini
- [x] de-DE.plg_editors-xtd_readmore.sys.ini
- [x] de-DE.plg_editors_codemirror.ini
- [x] de-DE.plg_editors_codemirror.sys.ini
- [x] de-DE.plg_editors_none.ini
- [x] de-DE.plg_editors_none.sys.ini
- [x] de-DE.plg_editors_tinymce.ini
- [x] de-DE.plg_editors_tinymce.sys.ini
- [x] de-DE.plg_extension_joomla.ini
- [x] de-DE.plg_extension_joomla.sys.ini
- [x] de-DE.plg_fields_calendar.ini
- [x] de-DE.plg_fields_calendar.sys.ini
- [x] de-DE.plg_fields_checkboxes.ini
- [x] de-DE.plg_fields_checkboxes.sys.ini
- [x] de-DE.plg_fields_color.ini
- [x] de-DE.plg_fields_color.sys.ini
- [x] de-DE.plg_fields_editor.ini
- [x] de-DE.plg_fields_editor.sys.ini
- [x] de-DE.plg_fields_image.ini
- [x] de-DE.plg_fields_image.sys.ini
- [x] de-DE.plg_fields_imagelist.ini
- [x] de-DE.plg_fields_imagelist.sys.ini
- [x] de-DE.plg_fields_integer.ini
- [x] de-DE.plg_fields_integer.sys.ini
- [x] de-DE.plg_fields_list.ini
- [x] de-DE.plg_fields_list.sys.ini
- [x] de-DE.plg_fields_media.ini
- [x] de-DE.plg_fields_media.sys.ini
- [x] de-DE.plg_fields_radio.ini
- [x] de-DE.plg_fields_radio.sys.ini
- [x] de-DE.plg_fields_repeatable.ini
- [x] de-DE.plg_fields_repeatable.sys.ini
- [x] de-DE.plg_fields_sql.ini
- [x] de-DE.plg_fields_sql.sys.ini
- [x] de-DE.plg_fields_text.ini
- [x] de-DE.plg_fields_text.sys.ini
- [x] de-DE.plg_fields_textarea.ini
- [x] de-DE.plg_fields_textarea.sys.ini
- [x] de-DE.plg_fields_url.ini
- [x] de-DE.plg_fields_url.sys.ini
- [x] de-DE.plg_fields_user.ini
- [x] de-DE.plg_fields_user.sys.ini
- [x] de-DE.plg_fields_usergrouplist.ini
- [x] de-DE.plg_fields_usergrouplist.sys.ini
- [x] de-DE.plg_finder_categories.ini
- [x] de-DE.plg_finder_categories.sys.ini
- [x] de-DE.plg_finder_contacts.ini
- [x] de-DE.plg_finder_contacts.sys.ini
- [x] de-DE.plg_finder_content.ini
- [x] de-DE.plg_finder_content.sys.ini
- [x] de-DE.plg_finder_newsfeeds.ini
- [x] de-DE.plg_finder_newsfeeds.sys.ini
- [x] de-DE.plg_finder_tags.ini
- [x] de-DE.plg_finder_tags.sys.ini
- [x] de-DE.plg_installer_folderinstaller.ini
- [x] de-DE.plg_installer_folderinstaller.sys.ini
- [x] de-DE.plg_installer_packageinstaller.ini
- [x] de-DE.plg_installer_packageinstaller.sys.ini
- [x] de-DE.plg_installer_urlinstaller.ini
- [x] de-DE.plg_installer_urlinstaller.sys.ini
- [x] de-DE.plg_installer_webinstaller.ini
- [x] de-DE.plg_installer_webinstaller.sys.ini
- [x] de-DE.plg_privacy_actionlogs.ini
- [x] de-DE.plg_privacy_actionlogs.sys.ini
- [x] de-DE.plg_privacy_consents.ini
- [x] de-DE.plg_privacy_consents.sys.ini
- [x] de-DE.plg_privacy_contact.ini
- [x] de-DE.plg_privacy_contact.sys.ini
- [x] de-DE.plg_privacy_content.ini
- [x] de-DE.plg_privacy_content.sys.ini
- [x] de-DE.plg_privacy_message.ini
- [x] de-DE.plg_privacy_message.sys.ini
- [x] de-DE.plg_privacy_user.ini
- [x] de-DE.plg_privacy_user.sys.ini
- [x] de-DE.plg_quickicon_extensionupdate.ini
- [x] de-DE.plg_quickicon_extensionupdate.sys.ini
- [x] de-DE.plg_quickicon_joomlaupdate.ini
- [x] de-DE.plg_quickicon_joomlaupdate.sys.ini
- [x] de-DE.plg_quickicon_phpversioncheck.ini
- [x] de-DE.plg_quickicon_phpversioncheck.sys.ini
- [x] de-DE.plg_quickicon_privacycheck.ini
- [x] de-DE.plg_quickicon_privacycheck.sys.ini
- [x] de-DE.plg_sampledata_blog.ini
- [x] de-DE.plg_sampledata_blog.sys.ini
- [x] de-DE.plg_system_actionlogs.ini
- [x] de-DE.plg_system_actionlogs.sys.ini
- [x] de-DE.plg_system_cache.ini
- [x] de-DE.plg_system_cache.sys.ini
- [x] de-DE.plg_system_debug.ini
- [x] de-DE.plg_system_debug.sys.ini
- [x] de-DE.plg_system_fields.ini
- [x] de-DE.plg_system_fields.sys.ini
- [x] de-DE.plg_system_highlight.ini
- [x] de-DE.plg_system_highlight.sys.ini
- [x] de-DE.plg_system_languagecode.ini
- [x] de-DE.plg_system_languagecode.sys.ini
- [x] de-DE.plg_system_languagefilter.ini
- [x] de-DE.plg_system_languagefilter.sys.ini
- [x] de-DE.plg_system_log.ini
- [x] de-DE.plg_system_log.sys.ini
- [x] de-DE.plg_system_logout.ini
- [x] de-DE.plg_system_logout.sys.ini
- [x] de-DE.plg_system_logrotation.ini
- [x] de-DE.plg_system_logrotation.sys.ini
- [x] de-DE.plg_system_privacyconsent.ini
- [x] de-DE.plg_system_privacyconsent.sys.ini
- [x] de-DE.plg_system_redirect.ini
- [x] de-DE.plg_system_redirect.sys.ini
- [x] de-DE.plg_system_remember.ini
- [x] de-DE.plg_system_remember.sys.ini
- [x] de-DE.plg_system_sef.ini
- [x] de-DE.plg_system_sef.sys.ini
- [x] de-DE.plg_system_sessiongc.ini
- [x] de-DE.plg_system_sessiongc.sys.ini
- [x] de-DE.plg_system_stats.ini
- [x] de-DE.plg_system_stats.sys.ini
- [x] de-DE.plg_system_updatenotification.ini
- [x] de-DE.plg_system_updatenotification.sys.ini
- [x] de-DE.plg_twofactorauth_totp.ini
- [x] de-DE.plg_twofactorauth_totp.sys.ini
- [x] de-DE.plg_twofactorauth_yubikey.ini
- [x] de-DE.plg_twofactorauth_yubikey.sys.ini
- [x] de-DE.plg_user_contactcreator.ini
- [x] de-DE.plg_user_contactcreator.sys.ini
- [x] de-DE.plg_user_joomla.ini
- [x] de-DE.plg_user_joomla.sys.ini
- [x] de-DE.plg_user_profile.ini
- [x] de-DE.plg_user_profile.sys.ini
- [x] de-DE.plg_user_terms.ini
- [x] de-DE.plg_user_terms.sys.ini

**DELETE Files:**

- [x] de-DE.plg_authentication_gmail.ini
- [x] de-DE.plg_authentication_gmail.sys.ini
- [x] de-DE.plg_content_geshi.ini
- [x] de-DE.plg_content_geshi.sys.ini
- [x] de-DE.plg_finder_weblinks.ini
- [x] de-DE.plg_finder_weblinks.sys.ini
- [x] de-DE.plg_search_categories.ini
- [x] de-DE.plg_search_categories.sys.ini
- [x] de-DE.plg_search_contacts.ini
- [x] de-DE.plg_search_contacts.sys.ini
- [x] de-DE.plg_search_content.ini
- [x] de-DE.plg_search_content.sys.ini
- [x] de-DE.plg_search_newsfeeds.ini
- [x] de-DE.plg_search_newsfeeds.sys.ini
- [x] de-DE.plg_search_tags.ini
- [x] de-DE.plg_search_tags.sys.ini
- [x] de-DE.plg_search_weblinks.ini
- [x] de-DE.plg_search_weblinks.sys.ini
- [x] de-DE.plg_system_p3p.ini
- [x] de-DE.plg_system_p3p.sys.ini

**Comment by zero-24** [comment]
All PRs have been done. :)
