### ISSUE TITLE
[4.0] administrator/language generally

### ISSUE THREAD

**Issue by tecpromotion** [joomlagerman/joomla#808]
1. Fork this repo
2. Check local file diff with joomla/joomla-cms with diffmerge or https://www.diffchecker.com/
3. Rename file
4. Commit file with a reference to this issue

**CHANGE Files:**

- [x] de-DE.lib_joomla.ini
- [x] de-DE.localise.php
- [x] install.xml
- [x] joomla.ini
- [x] langmetadata.xml

**Comment by zero-24** [comment]
Hier die ersten drei Dateien: https://github.com/joomlagerman/joomla/pull/823 bei den anderen sollten wir abwarten wie wir die im Frontend übersetzen.

**Comment by tecpromotion** [comment]
@zero-24 magst du dir mal die lib_joomla.ini vornehmen?

**Comment by tecpromotion** [comment]
@zero-24 I refer here to issue #1106

**Comment by zero-24** [comment]
https://github.com/joomlagerman/joomla/pull/1260
