### ISSUE TITLE
[Repo] Milestones

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#85]
Hallo @sisko1990 

hast du bewusst den Milestone `3.3.7v1` genommen?

https://github.com/joomlagerman/joomla/issues?q=milestone%3A3.3.7v1+is%3Aclosed

Es wird keine 3.3.7 mehr geben das nächste Release wird die 3.4.0 sein.

**Comment by sisko1990** [comment]
Ja, habe ich erst bewusst genommen, falls es doch noch ein BugFix-Release gibt, in dem schon teilweise Änderungen drin sind. Halte ich jetzt bei der Masse an Änderung aber auch für unwahrscheinlich.
Kein Problem... ich kann den Meilenstein ja zum Glück hier zentral umbenennen.
