### ISSUE TITLE
[4.0] Beispieldaten übersetzen

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#851]
plg_sampledata_multilang.ini
plg_sampledata_multilang.sys.ini

plg_sampledata_blog.ini
plg_sampledata_blog.sys.ini

**Comment by chmst** [comment]
plg_sampledata blog muss übersetzt wrden. Ich war aber sehr vorsichtig und habe nur ganz wenig zum Übersetzen eingebaut

**Comment by chmst** [comment]
@tecpromotion Wo sind die Übersetzungen der Beispieldaten uas früheren Versionen? Ich glaube dass es mal deutsche Beispieldaten gab?

**Comment by zero-24** [comment]
Jein es gab mal [SQL Übersetzungen](https://github.com/joomlagerman/joomla/blob/3.3.0v1/installation/sql/mysql/sample_data_de.sql) aber meines Wissens nach nie eine Übersetzung vom Plugin Ansatz.

**Comment by tecpromotion** [comment]
mit #2016 erstmal in sync with core
