### ISSUE TITLE
Tips and Tricks : Doc benötigt

### ISSUE THREAD

**Issue by ThomasFinnern** [joomlagerman/joomla#910]
### Was darf/soll verbessert/korrigiert werden ?

Eine kleine Anleitung *.md im Root - Verzeichnis für Unterstützer mit Hinweisen wäre schön.

Es geht nicht direkt um pull request sondern eher wie gehe ich mit den Übersetzungen um
Wobei ein Hinweis zu " issue raussuchen -> ? reservieren ? / -> geänderte Dateien finden -> übersetzen -> pull request " auch hilfreich wäre

Ich stelle mir folgende Fragen:

* Wenn das Englische Original z.B. master J!4 eine andere Reihenfolge hat darf ich das DE umsortieren
* Wenn das DE mehr Zeilen als der Master hat dürfen diese gelöscht werden ?
* Dürfen nur die Zeilen aus dem Issue geändert werden oder dürfen auch weitere Zeilen aus dem englischem original übersetz werden? 

? Weiteres ?

Man könnte sie "Tip und Tricks" nennen, dann fällt es nicht so auf dass man den Unterstützer an Regeln bindet

**Comment by zero-24** [comment]
Hört sich gut an. Hab ich mir auf die To-do Liste gesetzt. Wenn @tecpromotion schneller ist hab ich natürlich auch nichts dagegen ;)

**Comment by tecpromotion** [comment]
> ### Was darf/soll verbessert/korrigiert werden ?
> Eine kleine Anleitung *.md im Root - Verzeichnis für Unterstützer mit Hinweisen wäre schön.
> 
> Es geht nicht direkt um pull request sondern eher wie gehe ich mit den Übersetzungen um
> Wobei ein Hinweis zu " issue raussuchen -> ? reservieren ? / -> geänderte Dateien finden -> übersetzen -> pull request " auch hilfreich wäre
> 

Generell haben @zero-24 und ich ein Auge auf die merged PRs von joomla/joomla-cms und legen diese als Issues an. Vertipper oder so ist jeder selbst für einen neuen Issue verantwortlich. Möglichst kein PR ohne Issue. Quasi Issue-first Prinzip.

> Ich stelle mir folgende Fragen:
> 
> * Wenn das Englische Original z.B. master J!4 eine andere Reihenfolge hat darf ich das DE umsortieren

joomla/joomla-cms branches sind generell der MASTER, es gibt Ausnahmen (wie immer).
Achte hier aber ganz genau auf die Branches. Der joomla/joomla-cms/staging ist bei uns der master!

> * Wenn das DE mehr Zeilen als der Master hat dürfen diese gelöscht werden ?

Generell arbeiten wir die Issues von joomla/joomla-cms nach. Somit siehe oben.

> * Dürfen nur die Zeilen aus dem Issue geändert werden oder dürfen auch weitere Zeilen aus dem englischem original übersetz werden?

Bitte nur Issue-relevante Anpassungen, sonst wird das ein riesen Chaos!

> 
> ? Weiteres ?
> 
> Man könnte sie "Tip und Tricks" nennen, dann fällt es nicht so auf dass man den Unterstützer an Regeln bindet

@ThomasFinnern ich habe dazu mal etwas aufgeschrieben als Hilfe zum [Starten](.github/CONTRIBUTING.md)

**Comment by zero-24** [comment]
Der Link ist: https://github.com/joomlagerman/joomla/blob/master/.github/CONTRIBUTING.md @tecpromotion :D

**Comment by tecpromotion** [comment]
> Der Link ist: https://github.com/joomlagerman/joomla/blob/master/.github/CONTRIBUTING.md @tecpromotion :D

das macht github echt noch nicht so gut.

**Comment by ThomasFinnern** [comment]
Danke, soviel Aufwand wollte ich ja gar nicht :-)
Bislang ist es ja eher generell.
Mir ging es ja eher um das kleingedruckte. Fakten/Fragen siehe oben können  übernommen werden.
