### ISSUE TITLE
[4.0] Align order of translations matching en-GB files

### ISSUE THREAD

**Issue by ThomasFinnern** [joomlagerman/joomla#949]
### Was soll verbessert / korrigiert werden

Die Reihenfolge der Übersetzungen in den Deutschen Dateien stimmt in wenigen Dateien nicht mehr mit dem englischen Original überein. "Besser wäre es erstmal die ganzen Files auf Stand zu bringen. Dann haben wir keinen Mischmasch in den PRs."

### Zusätzlichen Informationen

* Es gibt hier Übersetzungen die im Englischen Original nicht mehr vorhanden sind. Sie wurden evtl. in eine andere Datei verschoben oder müssen noch verschoben werden.  Diese wurden dann unten mit Kommentar hinzugefügt

**Comment by tecpromotion** [comment]
Hallo Thomas,
danke für die Info. Wie bereits erklärt, sitzen wir ja derzeit an den offenen Issues hier.
Wenn die durch sind, ist wieder alles von selbst auf Stand.
Ich schließe daher diesen Issue.

**Comment by ThomasFinnern** [comment]
Schade, hatte gerade meinen ersten Pull request vorbereitet.

Abgelehnt wurde bislang das ihr kein skript braucht.
>> "Das ist manuelle Arbeit in dem Fall."

Ich denke nicht, dass bei der Einpflege von Joomla 4 pull request Texten sich die Reihenfolge automatisch einstellt.

Mein tool ist bereit. Kann jederzeit starten

**Comment by tecpromotion** [comment]
@ThomasFinnern das _Problem_ sind die offenen Issues und PRs.
Da wird ja ganz viel erstmal umgebaut und auf Stand gebracht. Dann ist das automatisch identisch!

**Comment by tecpromotion** [comment]
@ThomasFinnern ich würde mich freuen, wenn du mir das beim nächsten Treffen zeigst.

**Comment by zero-24** [comment]
Hört sich nach einem guten Plan an. 👍
