### ISSUE TITLE
[4.0] Token authentication for the API application

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#967]
https://github.com/joomla/joomla-cms/pull/27021/files

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/pull/28486

**Comment by tecpromotion** [comment]
@zero-24 #967 is still done. see revision number 1e5ce386e3451b5b9eba5fcdafbcd5cbb76ce6a5

and should be completely done with PR #1006 and PR #1007

**Comment by tecpromotion** [comment]
@zero-24 I have closed this issue. Should I have forgotten or overlooked something please reopen it. Thanks.
