### ISSUE TITLE
[4.0 ] Vorschlag Eintrag vs. Beitrag

### ISSUE THREAD

**Issue by gerryfrancis** [joomlagerman/joomla#999]
### Was soll verbessert / korrigiert werden
`JGLOBAL_EDIT_TITLE`
`JGLOBAL_PRINT_TITLE`

### Wo wird/werden der/die Sprachstring(s) angezeigt (Frontend/Backend)
Frontend

### Was wäre eine bessere Übersetzung / Bezeichnung(en)
`JGLOBAL_EDIT_TITLE="Beitrag bearbeiten"`
`JGLOBAL_PRINT_TITLE="Beitrag ausdrucken < %s >"`

### Joomla Version & Version der deutschen Sprachdatei
3.9.16/3.9.16.1

### Zusätzlichen Informationen
Abgeleitet von der Original-Sprachdatei "en-GB.ini":
`JGLOBAL_EDIT_TITLE="Edit article"`
`JGLOBAL_PRINT_TITLE="Print article < %s >"`

**Comment by tecpromotion** [comment]
Hallo @gerryfrancis 
Danke für deinen Vorschlag, wir können dies gerne für 4.0 diskutieren.
In 3.9/3.10 werden wir dies nicht mehr umsetzen.
Dafür ist zu viel Literatur etc anzupassen und verwirrt die Leute.

Das sind insgesamt viel mehr Stellen im gesamten Repo die dann nachgezogen werden müssen.

**Comment by gerryfrancis** [comment]
Hallo @tecpromotion ,
Ist OK, es sind ja nur marginale Abweichungen.
LG, Gerald

**Comment by tecpromotion** [comment]
Das hat relativ großen Einfluß.
Es sind mehr als 30 Strings die Eintrag enthalten. Das muss genau geprüft werden.

**Comment by gerryfrancis** [comment]
@tecpromotion Was das englische Wort "article" (für Beitrag) betrifft, habe ich nur diese beiden Strings gefunden.
Wie auch immer, ich habe gerade zwei Overrides angelegt, um es "für mich" zu beheben. Falls es doch noch irgendwann für Version 3 geändert wird, kann ich die Overrides ja wieder entfernen.
LG, Gerald

**Comment by tecpromotion** [comment]
@gerryfrancis das Community-Interresse hält sich in Grenzen.
Ich schließe diesen ISSUE mal vorerst.
